### ISSUE TITLE
Motan是否会考虑服务层实现通过注解方式

### ISSUE THREAD

**Issue by simplechen** [weibocom/motan#103]
服务对外的暴露是否考虑采用如题方式，毕竟目前大多人还是习惯了注解方式。

**Comment by rayzhang0603** [comment]
会提供注解配置的，目前已经有同学提了相关pr，目前还在review中https://github.com/weibocom/motan/pull/101

**Comment by rayzhang0603** [comment]
注解功能已经合并到master，欢迎试用
