### ISSUE TITLE
NettyJaxrsServer中的maxRequestSize大小问题

### ISSUE THREAD

**Issue by pitli** [weibocom/motan#1032]
项目为motan+spring发布接口，通过接口上传文件时，如果文件大小超过10M，会导致TooLongFrameException，但在配置中无法修改该数据大小，修改spring的附件大小限制也无法解决该问题，通过排查，这个maxRequestSize在项目启动时便会按照默认大小10M配置，无法修改。所在包是motan-protocol-restful这个包引入的resteasy-netty这个包。

**Comment by rayzhang0603** [comment]
可以通过设置motan:protocol配置中的`maxContentLength`来设置最大运行请求大小。比如demo中[部分server配置](https://github.com/weibocom/motan/blob/2280e11907f04d5fd8af8d771afbcf8ed85ea0ef/motan-demo/motan-demo-server/src/main/resources/motan2_demo_server.xml#L40C49-L40C65)就设置了这个参数.

这个配置项在restful协议中是在[这里](https://github.com/weibocom/motan/blob/2280e11907f04d5fd8af8d771afbcf8ed85ea0ef/motan-extension/protocol-extension/motan-protocol-restful/src/main/java/com/weibo/api/motan/protocol/restful/support/netty/NettyEndpointFactory.java#L36)生效的。

**Comment by pitli** [comment]
@rayzhang0603 

    <motan:protocol id="demoRest" name="restful" endpointFactory="netty"/>

    <motan:protocol id="demoMotan" name="motan" default="true" maxServerConnection="80000"
					maxContentLength="52428800" payload="52428800"
					maxWorkerThread="800" minWorkerThread="20"/>

    
    <motan:basicService export="demoRest:8082,demoMotan:8805"
                        group="motan-demo-rpc" accessLog="false" shareChannel="true" module="motan-demo-rpc"
                        application="myMotanDemo" registry="registry" id="serviceBasicConfig"/>
这是我的motan-server.xml配置，这里已经配置了的，但是并不会生效。在解析motan:protocol标签时并不会进入[这里](https://github.com/weibocom/motan/blob/2280e11907f04d5fd8af8d771afbcf8ed85ea0ef/motan-extension/protocol-extension/motan-protocol-restful/src/main/java/com/weibo/api/motan/protocol/restful/support/netty/NettyEndpointFactory.java#L36)，只有在解析motan:basicService标签时才会进入，但是这个标签没有maxContentLength这个参数的。

**Comment by pitli** [comment]
@rayzhang0603 
![0T`(PGH4EO2TCDVC{7YH{9M](https://github.com/weibocom/motan/assets/52992576/abfd2d97-7ac9-48a4-bd8a-edc9839e1192)
这是我在启动后断点进入的截图，只有motan:basicService中的参数进入到这个工厂类中进行初始化了。

**Comment by rayzhang0603** [comment]
url会分别从protocol、basicService、service配置中合并参数的。把maxContentLength加到`demoRest`这个protocol中试一下，这个protocol才是对restful协议的配置。

```
<motan:protocol id="demoRest" name="restful" endpointFactory="netty" maxContentLength="52428800"/>

<motan:protocol id="demoMotan" name="motan" default="true" maxServerConnection="80000"
				maxContentLength="52428800" payload="52428800"
				maxWorkerThread="800" minWorkerThread="20"/>

<!-- 同时提供restful协议和motan协议 -->
<motan:basicService export="demoRest:8082,demoMotan:8805"
                    group="motan-demo-rpc" accessLog="false" shareChannel="true" module="motan-demo-rpc"
                    application="myMotanDemo" registry="registry" id="serviceBasicConfig"/>
```

**Comment by pitli** [comment]
按照这个配置可以正常修改maxRequestSize，非常感谢@rayzhang0603。但我还有个问题，看xml中都是protocol配置，原代码中也没有找到哪里会进行区分啊，为什么加在id为demoMotan的protocol中会起不到作用呢。

**Comment by rayzhang0603** [comment]
`export="demoRest:8082,demoMotan:8805"`这里指明了用什么协议在什么端口对外提供服务。其中的demoRest和demoMotan都是protocol bean的id。

restful场景中使用的是`demoRest`的protocol配置，所以需要在`demoRest`中设置相关参数。

`demoMotan`中配置的参数，只会在motan协议中生效的。
