### ISSUE TITLE
DefaultResponseFuture#getValueOrThrowable抛出MotanServiceException

### ISSUE THREAD

**Issue by jasonsuzhou** [weibocom/motan#1064]
caused by 具体报错的是方法返回的类不存在java.lang.ClassNotFoundException
但是这个类实际是存在的， 并且不管是重启客户端还是服务端都能恢复。
下面是报类找不到的错误堆栈， jdk用的是21的版本
![企业微信截图_17167759832944](https://github.com/weibocom/motan/assets/5878409/057d6d8d-fd7e-464e-aa9d-3eb89713b57f)

debug细节发现用这个currentThread的方式去加载就加载不到， 直接用Class.forName是可以加载到的
![image](https://github.com/weibocom/motan/assets/5878409/5441792b-27dd-43a2-91a9-2b95c4192f2d)

![image](https://github.com/weibocom/motan/assets/5878409/f42e7195-bf8d-4e9f-b17f-219ac941eea0)

**Comment by rayzhang0603** [comment]
与#1063 重复
