### ISSUE TITLE
关于service限制服务端连接池工作线程数的问题

### ISSUE THREAD

**Issue by hexian55** [weibocom/motan#107]
配置portocol如下
motan:protocol id="demoMotan" name="motan" maxWorkerThread="10" minWorkerThread="2" 我在service中，怎么让这个protocol配置的maxWorkerThread在server中生效呢？还在只需要再server.xml里面加上这一行？我直接加了这个配置是不行的。need help.....感谢

**Comment by sunnights** [comment]
确认service的export前缀和protocol的id “demoMotan”一致即可生效

**Comment by hexian55** [comment]
感谢，已解决
