### ISSUE TITLE
关于client  group和server  filter两个问题

### ISSUE THREAD

**Issue by hexian55** [weibocom/motan#108]
一、
client能不能支持请求多个server分组？比如我有20个server，分成两组，但是我希望所有的client都能访问到这两组server，以便实现灰度、stop部分server，而不影响client端

二、server filter是不是我自己实现一个javax.servlet.Filter，然后直接配置上就ok了？

先谢谢大家了

**Comment by sunnights** [comment]
1. 目前可以通过配置流量切换指令来请求多个分组，但我觉得要实现你说的功能没必要分两组， @qdaxb  @rayzhang0603 帮忙看下
2. 请参考 #75

**Comment by hexian55** [comment]
我尝试了你说的这种方法，但是流量没有切过来
我server分成两组，单机指向不同的端口，client只连了group1，然后将group1的流量切换到group2，但是没有生效

**Comment by sunnights** [comment]
你是不是用的maven中的jar包，目前maven中的zookeeper版本还不支持指令功能，可以编译最新的源码，替换旧的zookeeper包应该就可以了

**Comment by hexian55** [comment]
是的，这个版本大概什么时候会更新呢？如果自己编的话，是吧motan-registry-zookeeper替换成最新的zookeeper编译就行？

**Comment by sunnights** [comment]
对，把编译后的jar包导入就可以

**Comment by hexian55** [comment]
现在主干上的代码用的zk是3.4.8，我直接编这个快照版也行是吧

**Comment by sunnights** [comment]
可以的

**Comment by rayzhang0603** [comment]
0.1.2版本已经支持
