### ISSUE TITLE
调试motan自带的demo时，发现每次client启动后，都会发送一个toString方法到服务端

### ISSUE THREAD

**Issue by PriestsHsiung** [weibocom/motan#115]
服务端和客户端都在本机，采用 directUrl方式。
客户端启动后就会发送一个toString方法到服务端，跟踪调用发现是在RefererConfig.java:137行调用后发出的请求。但不知道是怎么调用的和这么设计的意图，请指教，谢谢

**Comment by PriestsHsiung** [comment]
idea调用toString方法后，似乎没有走到RefererInvocationHandler::invoke(77行)代码这里。请问，这个方法后调用后，是哪个类的方法被调用了，谢谢 @rayzhang0603

**Comment by rayzhang0603** [comment]
远程方法都会从你说的这个位置进行调用的，在这个位置断点应该可以调试到

**Comment by qdaxb** [comment]
no update for over two months, close.
