### ISSUE TITLE
关于motan-admin以及zk的问题

### ISSUE THREAD

**Issue by Harrytion** [weibocom/motan#117]
是这样的，我的zk集群配到了motan-admin上不能用，请问是我的zk的问题吗，还是说多个zkurl之间用什么符号分隔。还有什么时候可以支持spring-boot呀

**Comment by sunnights** [comment]
请提供一下manager中zk的配置信息

**Comment by Harrytion** [comment]
registry.type=zookeeper
registry.url=192.168.32.130:2181,192.168.32.133:2181,192.168.32.134:2181 
我不知道这样写对不对，请指点，谢谢

**Comment by sunnights** [comment]
这样写是可以的，只配其中一个zk的ip也可以
我刚在本地起zk集群测了下可以正常连接的，请确认zk集群是否启动成功
