### ISSUE TITLE
请问这个实现Thrift协议需要如何改造？

### ISSUE THREAD

**Issue by luohoufu** [weibocom/motan#118]
想改造成支持thrift协议的，有人能提供一个大概的思路吗？

**Comment by rayzhang0603** [comment]
原来motan是有适配thrift计划，也实现了一个简单的版本，由于在内部没有什么使用场景，没有继续进行。
目前我们在做yar协议适配，稍后才会进行grpc和thrift的适配工作。
也欢迎提thrift协议的pr，大概的思路是实现一个ThriftProtocol（参照DefaultRpcProtocol）、实现Thrift transport（参照motan-transport-netty模块），在thrift协议中使用thrift的thransport进行远程调用。

**Comment by qdaxb** [comment]
see [wiki](https://github.com/weibocom/motan/wiki/zh_developguide#编写一个motan扩展) for more details, closed.
