### ISSUE TITLE
请问一下，目前RPC服务是默认先找本地，有什么参数可以指定不找本地的？

### ISSUE THREAD

**Issue by igool** [weibocom/motan#119]
我这边运行DEMO，client,server放在同台机器没有问题，如果分开放的话，就有问题。请问哪里有详细的配置说明？

**Comment by sunnights** [comment]
1. 默认的loadbalance策略是activeWeight（低并发优先），其他方式可参考[这里](https://github.com/weibocom/motan/wiki/zh_userguide#%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1)
2. 能否提供错误日志？

**Comment by wangwei418** [comment]
无论什么策略 都会先查一下本地么？现在各种都尝试了 但在log中发现，每次都会先找本机服务 。这个怎么解释呢@ @sunnights

**Comment by sunnights** [comment]
你是不是用直连方式调的呀，有没有用注册中心呢

**Comment by wangwei418** [comment]
@sunnights  用的是consul作为注册中心。
跟代码发现 ClusterSupport 中  88行
  // client 注册自己，同时订阅service列表
            Registry registry = getRegistry(ru);
            registry.subscribe(subUrl, this);

这段代码 注册自己   是什么意思？

现在启动log：


11-24 19:13:35 [main] INFO  info[55] - CommandFailbackRegistry subscribe. url: motan://本机ip:0/com.***Service?group=motan_news_rpc_test
11-24 19:13:51 [main] INFO  info[55] - CommandServiceManager init url:motan://本机ip:0/com.***Service?singleton=true&haStrategy=failover&module=media-wechatfetch&maxClientConnection=20&minClientConnection=2&loadbalance=roundrobin&check=true&nodeType=service&version=1.0&throwException=false&accessLog=false&retries=2&protocol=motan&isDefault=true&application=wechatfetch&refreshTimestamp=1511522014307&id=userNewsService&requestTimeout=3000&group=motan_news_rpc_test&
11-24 19:13:51 [Thread-7] INFO  info[55] - start group lookup thread. lookup interval: 30000ms, group: motan_news_rpc_test
11-24 19:13:51 [main] INFO  info[55] - CommandFailbackRegistry discover. url: motan://本机ip:0/com***Service?group=motan_news_rpc_test


理论上 不应该在本机 去subscribe

**Comment by wangwei418** [comment]
@sunnights  loadbalance使用的 loadbalance="roundrobin"

**Comment by sunnights** [comment]
subscribe是订阅服务，可以在consul后台确认下其他服务节点是否正常
本地可在RoundRobinLoadBalance中打断点确认客户端发现的服务节点是否正确

**Comment by wangwei418** [comment]
@sunnights   服务调用都是正常的 就是启动的时候  订阅本机感觉怪怪的 像查下到底什么问题。
另外对于loadbalance  好像只有hash的进了断点 其他的都没进去  不知道什么情况

**Comment by wangwei418** [comment]
1，// client 注册自己，同时订阅service列表
Registry registry = getRegistry(ru); 

代码里的 注册自己  还没明白是什么意思     
2，subscribe是订阅服务  但为什么要去找本机的呢，本机是作为调用者启动的

3，1.0 版本现在支持consul 多地址配置了吗？

**Comment by sunnights** [comment]
1. 注册自己的行为跟注册中心相关，使用zk的时候client会注册自己，使用consul不会
2. 这个log指的是本机的这个client对应的url，要订阅服务端节点信息，会进行init、discover等操作，并不是去本机查找service
