### ISSUE TITLE
使用Consul作为注册中心address是否可以配置多个

### ISSUE THREAD

**Issue by gooking** [weibocom/motan#121]
https://github.com/weibocom/motan/wiki/zh_userguide

说明中，使用 Zookeeper 座位注册中心，可以配置多个以避免 registry 的单点故障问题

那么，使用 Consul 作为注册中心，似乎不能配置多个地址，如何避免 Consul registry  的单点故障问题？

另外一个问题：

![image](https://cloud.githubusercontent.com/assets/7286469/16178113/81f07212-3672-11e6-8672-ba91cefffcb9.png)

这个图中，“

> 当Server发生变更时，Registry会同步变更，Client感知后会对本地的服务列表作相应调整。

”  这句话应该如何理解？

client 感知是自动感知还是被动感知？ 是需要和定期轮训去检测服务状态吗？还是注册中心主动推送服务状态的改变？

**Comment by sunnights** [comment]
client感知需要根据不同注册中心的特点来决定，可以轮询也可以被动通知，
consul中使用轮询的方式主动感知，zookeeper中使用订阅节点变更事件的方式被动感知

**Comment by gooking** [comment]
> 使用 Zookeeper 作为注册中心，可以配置多个以避免 registry 的单点故障问题
> 
> 那么，使用 Consul 作为注册中心，似乎不能配置多个地址，如何避免 Consul registry 的单点故障问题？

这个问题还没回复呢

**Comment by rayzhang0603** [comment]
使用consul作为注册中心时，地址一般配置为local的consul agent，consul server的高可用由consul 自身的机制保证。

**Comment by gooking** [comment]
服务端可以配置 local的consul agent ，那么， client 端去发现服务的时候，应该可以配置多个 consul agent 吧，否则一个consul 异常，客户端就无法发现服务了

**Comment by rayzhang0603** [comment]
我们在调研一下consul注册中心多地址的需求，后续考虑增加多地址的支持。不过，我们推荐不论是client端还是server端都部署consul agent，注册中心地址配置为local的。
