### ISSUE TITLE
你们的RPC的netty版本为什么会依赖两个？

### ISSUE THREAD

**Issue by igool** [weibocom/motan#122]
1其中transport-netty的版本为3.2.5
2其中registry-zookeeper的版本为3.7.0

**Comment by rayzhang0603** [comment]
motan-tansport-netty模块使用的netty版本为3.2.5。registry-zookeeper中的netty是通过zookeeper间接依赖的，实际使用中两个版本都可以。

**Comment by netboynb** [comment]
1、registry-zookeeper的版本为3.7.0
   这个依赖是zookeeper自身的通信依赖，zookeeper客户端与zookeeper服务端的集群通信，比如说心跳维系、创建节点、查询节点等 均有使用netty实现的方式，当然也有简单的不使用netty的http模式。目前zookeeper的3.4.8版本中依赖的是netty 3.7.0.final版本，
不过请注意：两者的包路径是不同的 

<dependency>
    <groupId>io.netty</groupId>
    <artifactId>netty</artifactId>
    <version>3.7.0.Final</version>
</dependency>

<dependency>
    <groupId>org.jboss.netty</groupId>
    <artifactId>netty</artifactId>
    <version>3.2.5.Final</version>
</dependency>

2、transport-netty的版本为3.2.5
    这里的netty  是用于motan的客户端与服务端之键网络通信使用，在你本地进行rpc时，背后其实是通过netty实现的tcp通信进行的。该版本是比较旧的依赖，属于历史遗留问题，旧版本的netty 和新版本的netty在接口和包路径上很多地方是是不兼容的。

如果有包冲突问题的话，可以将zookeeper依赖的那个netty排掉，我记得默认zookeeper是使用http进行通信的，除非用户指定使用netty

**Comment by igool** [comment]
我想说，能不能直接统一使用3.7.0

**Comment by rchzzjcn** [comment]
而且在https://github.com/weibocom/motan/blob/master/motan-transport-netty/src/main/java/com/weibo/api/motan/transport/netty/StandardThreadExecutor.java 中用到了netty的一个internal class:
import org.jboss.netty.util.internal.LinkedTransferQueue;

这个class在netty的高版本中已经删除掉了。

强烈建议统一升级到netty3的当前版本 (3.10.5.Final)。

**Comment by rchzzjcn** [comment]
有些项目里同时依赖netty3和netty4，还是可以理解的。但一个项目里同时依赖两个不同的netty3版本，感觉非常奇怪

**Comment by qdaxb** [comment]
@rchzzjcn 目前我们准备升级到netty4，3的版本暂时就不修改了。

**Comment by rchzzjcn** [comment]
@qdaxb，嗯，统一升级到netty4也是一个好主意。谢谢！

**Comment by Harrytion** [comment]
@qdaxb 什么时候升级至netty4 啊，好像netty4 和3的话，有些类已经删的差不多了，但是原理还是那个原理。

**Comment by ijaychang** [comment]
表示netty3还没了解透。。。⊙﹏⊙b汗

jaychang@aliyun.com

发件人： Harrytion
发送时间： 2016-07-11 09:48
收件人： weibocom/motan
主题： Re: [weibocom/motan] 你们的RPC的netty版本为什么会依赖两个？ (#122)
@qdaxb 什么时候升级至netty4 啊，好像netty4 和3的话，有些类已经删的差不多了，但是原理还是那个原理。

**Comment by qdaxb** [comment]
see #16 ,close
