### ISSUE TITLE
使用zk作为注册中心，链接中断后临时节点无法再建立

### ISSUE THREAD

**Issue by RedRush-Misery** [weibocom/motan#123]
使用zookeeper作为注册中心时，应用与注册中心链接中断超过一个sessionTimeout时间，应用与zookeeper的链接恢复后该应用注册的临时节点消失

**Comment by rayzhang0603** [comment]
感谢反馈！我们确认一下，如果是bug会尽快修复。

**Comment by rayzhang0603** [comment]
已经在0.1.2版本中修正了该问题，请使用最新版本进行测试。感谢支持
