### ISSUE TITLE
感觉和dubbo差不多啊

### ISSUE THREAD

**Issue by simpleSOA** [weibocom/motan#13]
首先非常感谢motan开源，顺便请问一下，看了下demo代码，感觉和dubbo差不多，请问motan和dubbo相比有什么优势？

**Comment by superleo-cn** [comment]
确实差不多。最主要还是dubbo官方早就不维护了，如果将来这个motan周边配套都成熟了，迁移也方便了。

**Comment by qdaxb** [comment]
Dubbo 功能上比较丰富，与 Dubbo 的分层来对比，Motan 的模块层次要更简单一些，没有 exchange 和 directory 等。从我们压测的结果来看，在我们的业务场景下Motan的性能比dubbo要好一些。

并且像 @superleo-cn 说的，dubbo已经不维护了。

**Comment by ccc-rrr** [comment]
“和dubbo差不多”也能方便、少成本地转移过来。

**Comment by coswind** [comment]
赞一个，层次确实简单明晰

**Comment by simpleSOA** [comment]
赞一个，希望不要像dubbo那样坑，生态好了就没人维护了，希望以后Motan能把dubbo干下去

**Comment by kazaff** [comment]
当当的dubbox算是一种dubbo的延续，更新了相关的库版本，增加了rest api等特性。motan的很多依赖技术的选择上和dubbo都一致，是否可以理解成为了性能或代码简洁性而做的一种重构？

**Comment by kazaff** [comment]
@simpleSOA  我觉得dubbo[x]的代码还是有在维护的，而且从社区关注度上来看是很好的
