### ISSUE TITLE
不支持jdk7，报错如下

### ISSUE THREAD

**Issue by huangruisheng** [weibocom/motan#130]
Caused by: java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView

\at com.weibo.api.motan.util.ConcurrentHashSet.iterator(ConcurrentHashSet.java:49) ~[motan-core-0.1.2-20160622.094718-13.jar:na]

**Comment by sunnights** [comment]
这应该是编译和使用的jdk版本不一致导致的，请确认一下mvn编译的jdk版本和执行时使用的jdk版本

**Comment by qdaxb** [comment]
确认一下是否使用jdk8编译，jdk7运行？由于jdk8使用了新的`ConcurrentHashMap`实现，导致jdk8编译后的代码在jdk7下无法运行。
