### ISSUE TITLE
0.1.1版本DEMO的Client端getBean返回为null

### ISSUE THREAD

**Issue by tanjian11** [weibocom/motan#131]
在使用0.1.1版本demo时，服务端没有报错，client端在读取完配置文件后getBean返回为null，未取到代理类

**Comment by rayzhang0603** [comment]
有没有error或warn相关的日志？如果使用zk作为注册中心，请确认server端启动后，有没有执行MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
执行开关后才会正式提供服务

**Comment by tanjian11** [comment]
ApplicationContext applicationContext = new ClassPathXmlApplicationContext(new String[] {"classpath:spring/spring-core.xml"});
        MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
        System.out.println("server start...");

注册中心使用的是zk,服务器启动是使用这段代码执行的，并且控制台打印Server start 没有报错
在客户端调用的只有一个空指针，根据断点查看，getBean返回的对象是空对象，
而在同一个配置文件里面的普通bean对象是可以通过getBean的方式获得的

**Comment by rayzhang0603** [comment]
能提供一下具体配置吗？在zk中能查到对应的server节点吗？路径为/motan/{group}/{service}/availableServer/

**Comment by qdaxb** [comment]
no response for over two months, closed.
