### ISSUE TITLE
配合Spring-data-jpa使用的问题

### ISSUE THREAD

**Issue by wydream** [weibocom/motan#132]
在client调用就会出现“Exception caught when method invoke: java.lang.NullPointerException”，只要是通过jpa拿数据的地方，都会。而且错误应该是出在服务端的，是不是不兼容？

**Comment by rayzhang0603** [comment]
感谢反馈，我们测试一下。看异常应该server端具体实现类在进行invoke的时候遇到npe，能在具体描述一下server端的使用方式吗？server端的具体实现类bean是如何配置的？

**Comment by wydream** [comment]
@rayzhang0603 
就是最普通的方式，一个User类
`public interface UserRepository extends JpaRepository<User, Long> {
}`

`public interface UserService {
    User getUserById(Long id);
}`

Impl里面
`public User getUserById(Long id) {
        return userRepository.findOne(id);
    }`

**Comment by feilaoda** [comment]
UserRepository没有通过spring注入？

**Comment by wydream** [comment]
@feilaoda 注入了的

**Comment by rayzhang0603** [comment]
经过测试，motan和spring-data-jpa是兼容的。你异常中的npe应该是server使用的UserRepository没有正确注入，可以通过debug来进行确认UserRepository是否为空。
motan和其他使用spring bean方式的项目结合时，需要重点确认**motan和其他spring bean是否在同一个spring context中**，可以从motan的xml加载方式、其他spring bean的加载方式进行排查。如果是注解类型的，一般需要添加@ImportResource("classpath:motan_server.xml")引入motan中的bean
