### ISSUE TITLE
数据传递问题

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#136]
案例：
Server 环境：部署在linux上，web应用，接口返回一个object
Client 环境 ：本地windows，eclipse，独立类调用

通过日志输出，确定Server端接口已经返回数据，但是client端没有收到
Server端如果在本地跑的话，client端是能正常收到数据的

不知道有可能是什么问题？
hessian版本是一致的4.0.38

**Comment by rayzhang0603** [comment]
按下面思路试试
1、序列化对象类型的返回值需要实现java.io.Serializable接口，可以check一下
2、有没有warn或error日志
3、网络环境是否正常，有无防火墙设置、可以在client端抓包看一下
4、debug client端FrameDecoder->messageReceived()方法，看netty是否接收到返回值，如果没有，从网络层面找原因，如果接收到返回值，就逐步调试一下。

**Comment by thisxulz** [comment]
确认是resin版本的问题，服务器部署使用的是resin，用tomcat就没有问题，不知道sina内部用的是什么部署？

**Comment by rayzhang0603** [comment]
sina没有使用resin。能提供一下resin的版本号吗，我们测试一下，看是否有兼容性问题。

**Comment by thisxulz** [comment]
resin pro 3.1

**Comment by rayzhang0603** [comment]
好的，感谢

**Comment by rayzhang0603** [comment]
测试确认resin-pro-3.1.15可以正常使用。
我觉得可以从我前面提的第四点，看看netty是否接收到了返回值。或者分别从server端和client端tcpdump一下请求看看。

**Comment by thisxulz** [comment]
我把resin升级到4.0后就可以了，肯定不是网络的问题，服务器上的resin也是老版本了，看报错还是hessian反序列化错误，很尴尬，暂时决定用4.0版本了
