### ISSUE TITLE
能否替换fastjson为jackson?

### ISSUE THREAD

**Issue by siminture** [weibocom/motan#137]
项目中已经使用了jackson序列化，能否替换掉motan中的fastjson？

**Comment by rayzhang0603** [comment]
motan在FastJsonSerialization、RpcCommandUtil中使用了fastjson，如果确认不需要使用指令控制和fastjson序列化的话，可以把fastjson excludes掉。
如果没有冲突的话，不建议替换。

**Comment by tangdu** [comment]
我还是觉得jackson好用

**Comment by kris-zhang** [comment]
请问什么场景下你们需要使用json协议做RPC调用
