### ISSUE TITLE
关于泛型序列化问题

### ISSUE THREAD

**Issue by houhou2020** [weibocom/motan#139]
motan现在不支持方法返回泛型结果吗？无论是泛型对象和泛型容器都是反序列化为hashmap了

**Comment by rayzhang0603** [comment]
能详细描述一下使用场景，或者给一个具体使用方式的例子吗？类似这样的范型是支持的。

```
public interface FooService{
    public <T> T testGenerics(T t);
}    
```

或者

```
public interface FooService<T>{
    public T testGenerics(T t);
}  
```

**Comment by houhou2020** [comment]
这种
public interface FooService{
    public List<Person> getPersons();
}
或者
public interface FooService<T>{
    public T testGenerics(T t);
}
麻烦看下

**Comment by houhou2020** [comment]
这种
public interface FooService{
    public List < Person > getPersons();
}

遍历List时候取到的是 hashmap 麻烦看下

**Comment by rayzhang0603** [comment]
list的范型也可以正常支持的，例如下面这种：

```
public List<T> testListGenerics(List<T> list);
```

你可以确认一下Person是否实现了java.io.Serializable，或者确认一下server端返回的具体对象是什么

**Comment by andot** [comment]
我看了一下 Serialization 接口的定义：

``` java
@Spi(scope=Scope.PROTOTYPE)
public interface Serialization {
    byte[] serialize(Object obj) throws IOException;
    <T> T deserialize(byte[] bytes, Class<T> clz) throws IOException;
}
```

发现这个 deserialize 反序列化接口方法确实是不支持泛型的，如果把接口改为：

``` java
@Spi(scope=Scope.PROTOTYPE)
public interface Serialization {
    byte[] serialize(Object obj) throws IOException;
    Object deserialize(byte[] bytes, Type type) throws IOException;
}
```

就可以支持泛型反序列化了。

因为 Class<T> 这个类型信息里面不包含泛型，而 Type 是可以包含泛型信息的。

Hprose 是通过对 Type 的支持来实现对泛型的类型的准确反序列化的。如果把反序列化接口方法改成带有 Type 类型的，对诸如：`List<Map<String, List<Map<String, String>>>>` 这样的多层嵌套的泛型数据会支持的更好。
