### ISSUE TITLE
support PHP yar protocol

### ISSUE THREAD

**Issue by qdaxb** [weibocom/motan#14]
[Yar](https://github.com/laruence/yar) is a widely used php rpc framework. We could implement the protocol of yar to support cross-language invocation.

There might be three steps:
- Support yar protocol for Motan server, then a php yar client could call java services
- Support yar protocol for Motan client. It might be a little harder because of we need to support short connection on Motan client side.
- Support long connection on php side to improve performance, maybe http/2 is a good option.

**Comment by ghost** [comment]
this function is what i am looking for! very very great ! exciting!

**Comment by chaneychan** [comment]
cool，We are waiting for this feature.

**Comment by rayzhang0603** [comment]
yar protocol will supporting soon！you can try it in here https://github.com/weibocom/motan/tree/feature/yar
please let me know if you have any problems.

**Comment by qdaxb** [comment]
done 
#160
