### ISSUE TITLE
请问这个实现 Hprose 协议需要如何改造？

### ISSUE THREAD

**Issue by andot** [weibocom/motan#140]
[Hprose](https://github.com/hprose) 现在支持跨语言，而 Motan 提供了很好的服务治理，想把 Motan 加上对 Hprose 协议的支持。这样就不用单独做 Hprose 的服务治理了。请问 Motan 有计划支持 [Hprose for Java](https://github.com/hprose/hprose-java) 吗？或者怎么做才能支持 [Hprose 协议](https://github.com/hprose/hprose/blob/master/spec_zh_CN.mediawiki)。

**Comment by rayzhang0603** [comment]
暂时还没有相应的排期。欢迎PR。
支持的方式可以参照DefaultRpcProtocol，实现server端的Exporter和client端的Referer。
Exporter监听服务端口，将请求转换为motan的Request，然后找到对应的provider调用服务，并将motan的response转换为Hprose的response。
Referer过程类似。

**Comment by andot** [comment]
好的，谢谢，有时间研究一下。

**Comment by qdaxb** [comment]
done with #162
