### ISSUE TITLE
service export的问题

### ISSUE THREAD

**Issue by ruixiu** [weibocom/motan#141]
<motan:service interface="com.weibo.motan.demo.service.MotanDemo1Service"
                   ref="motanDemoServiceImpl" export="demoMotan:8001" basicService="serviceBasicConfig">
    /motan:service
    <motan:service interface="com.weibo.motan.demo.service.MotanDemo2Service"
                   ref="motanDemoServiceImpl" export="demoMotan:8002" basicService="serviceBasicConfig">
    /motan:service
如上配置，export不能使用相同的端口吗？如果在一个项目中存在多个service，就需要规划好端口的使用。有没有更好的办法可以处理呢？

**Comment by ruixiu** [comment]
追问：感觉使用方法有些类似于dubbo，那么目前Motan的服务端口暴露方式比dubbo有哪些优势呢？

**Comment by rayzhang0603** [comment]
使用相同端口可以把export配置放在motan:basicService标签中，并设置shareChannel="true"

```
<motan:basicService id="serviceBasicConfig" export="demoMotan:8002" shareChannel="true".../>
<motan:service interface="interface1" basicService="serviceBasicConfig"... />
<motan:service interface="interface2" basicService="serviceBasicConfig"... />
```

basicService和servcie标签的配置项基本一致的，凡是多个service的通用属性都可以配置在basicService中。
如果某个service的某个配置项不需要使用basic的配置时，在这个service中单独声明即可。
