### ISSUE TITLE
请问motan服务治理有实现服务的升降级功能？在什么地方实现的

### ISSUE THREAD

**Issue by huangruisheng** [weibocom/motan#143]
谢谢！

**Comment by rayzhang0603** [comment]
降级功能可以通过配置SwitcherFilter实现，通过设置开关状态控制是否处理request。
配置方法

   <motan:referer id="***" filter="switcher" ..../>

或者

```
<motan:service  filter="switcher" ..../>
```

目前可以通过MotanSwitcherUtil设置开关状态控制降级。
后续版本会在manage后台增加通用的控制功能。
