### ISSUE TITLE
请问客户端对同一个服务端会有多个链接吗？

### ISSUE THREAD

**Issue by sandyfog** [weibocom/motan#144]
我有个疑问，客户端订阅一个服务就会和提供这个服务的服务端建立链接；那如果客户端订阅多个服务的话，两个以上服务可能存在于同一个服务端，那是不是客户端就和这个服务端建立多个链接还是共用同一个链接？

**Comment by rayzhang0603** [comment]
这个问题主要还是复用与隔离的权衡，目前的策略是建立多个链接，使不同服务尽量隔离。
