### ISSUE TITLE
异常隔离在哪里实现的？

### ISSUE THREAD

**Issue by q11112345** [weibocom/motan#145]
我看网上的介绍说 motan实现了高可用策略

高可用策略：失败重试（Failover）、快速失败（Failfast）、异常隔离（Server 连续失败超过指定次数置为不可用，然后定期进行心跳探测）

代码里面只看到 Failover Failfast， 异常隔离在哪里呢？

**Comment by rayzhang0603** [comment]
这个异常隔离是在transport模块实现的，可以参考NettyClient类。在网络异常时会发生作用。
后续版本中还会增加一些快速失败策略的扩展，敬请关注。

**Comment by fdx321** [comment]
@rayzhang0603  看了代码，Failfast 好像实现的比较粗糙，只是简单的refer.call(...). 这和普通的调用一样啊，并不是Failfast吧？
