### ISSUE TITLE
motan:method问题

### ISSUE THREAD

**Issue by tanxiaolong77** [weibocom/motan#146]
我看源码发现里面能在motan:referer里定义子节点motan:method 这个是用来干嘛的？一般调用指定的方法都封在request里，然而motan:method里面定义的方法和参数被放到了Referer里，但也没有起到作用，不知道是用来干嘛的这个标签 能说明下吗？谢谢了

**Comment by rayzhang0603** [comment]
这个标签用来精细控制同一个service下的不同方法配置，例如方法级别的超时控制。
