### ISSUE TITLE
motan 如何配置日志？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#147]
nohup java  -Djava.ext.dirs=./lib -jar  order-service-0.0.1-SNAPSHOT.jar >log.txt &

目前是采用这种方式。但是这样的话所有的日志都在一个文件里面。请问我怎么配置日志，就像log4j那样？

**Comment by sunnights** [comment]
把log4j配置文件加到classpath下就可以使用啊

**Comment by JianSphere** [comment]
非常感谢，确实是这样。这样就不用重定向了
