### ISSUE TITLE
关于配置的疑问

### ISSUE THREAD

**Issue by ruixiu** [weibocom/motan#148]
motan的配置信息是在一起的，如果才能准确区分哪些配置项是应用在服务端的，而哪些是应用在客户端的呢？

**Comment by sunnights** [comment]
服务端启动的时候加载的配置文件中的配置项会应用在服务端，
客户端加载的配置文件会应用在客户端
具体各项信息可参考[配置清单](https://github.com/weibocom/motan/wiki/zh_configuration)

**Comment by ruixiu** [comment]
motan:protocol/是公用的吧，可是有些配置是在服务端用的，有些是在客户端用的

**Comment by sunnights** [comment]
不是公用的，服务端和客户端分别都有各自的配置文件

**Comment by ruixiu** [comment]
配置项都完全一样呀。怎么区分哪些配置项在服务端用，哪些在客户端用呢？是不是会在之后的开发指南上有说明？

**Comment by rayzhang0603** [comment]
protocol是整个协议的配置，包含server端和client端两部分。其中的参数有一部分是在server端和client端都可以使用的（例如 serialization、endpointFactory等），一部分是只在某一端使用的（例如，maxClientConnection只在client端生效、maxServerConnection只在server端生效）。

在既提供rpc server，又使用rpc client的场景下可以通过protocol统一配置。如果只配置server或只配置client时，只有对应的参数才会生效。

后面会在开发指南中标注各参数在哪一端生效。

**Comment by ruixiu** [comment]
多谢回复
