### ISSUE TITLE
如何关闭客户端使得服务端不报错

### ISSUE THREAD

**Issue by BlueRhino** [weibocom/motan#149]
刚开始研究motan，简单问题请见谅。我在使用客户端调用服务端接口后怎么关闭客户端，直接kill会报“netty错误”，“远程主机强迫关闭了一个现有链接”。试了试MontanSwitcherUtil，没解决。

**Comment by rayzhang0603** [comment]
如果使用spring方式，client的生命周期由spring进行管理，可以参考spring销毁bean的方式。
如果使用api方式，可以直接调用RefererConfig的destroy方法

**Comment by qdaxb** [comment]
no update for two months, close.
