### ISSUE TITLE
transport模块能保持更新么？

### ISSUE THREAD

**Issue by happygao521** [weibocom/motan#15]
简单看了一下，发现transport层netty版本有点老 还是3.2.5版本
这个后续会有升级么？

**Comment by qdaxb** [comment]
我们正在准备升级到netty4，motan使用3.x的版本netty比较稳定，目前正常使用应该不会有什么大问题。

netty4模块测试稳定之后会发布出来。

**Comment by qdaxb** [comment]
add new issue #16
