### ISSUE TITLE
在不使用spring的情况下，如何使用motan，有无试例代码

### ISSUE THREAD

**Issue by BlueRhino** [weibocom/motan#150]
由于项目需要，一样客服端和服务端都不包含spring，请问如何直接使用motan，不依赖spring

**Comment by rayzhang0603** [comment]
motan-demo模块中的MotanApiClientDemo、MotanApiExportDemo是通过api方式使用motan的例子，可以参考

**Comment by qdaxb** [comment]
no update for two months, close.
