### ISSUE TITLE
关于spring annotation

### ISSUE THREAD

**Issue by Harrytion** [weibocom/motan#151]
我看到提交上来的代码中有支持spring的注解，主持spring注解的新特性以及kryo的序列化是否会合并到下一个版本中。

**Comment by rayzhang0603** [comment]
会合并到下一个版本中的。

**Comment by Harrytion** [comment]
@rayzhang0603 我看到已经合并了，也就是说可以考虑支持spring boot了吗？能否出点例子呢？

**Comment by feilaoda** [comment]
@Harrytion spring boot本来就支持的

@SpringBootApplication
@ImportResource("classpath:soa-server.xml")
public class RpcApp {

```
public static void main(String[] args) {
    SpringApplication.run(RpcApp.class, args);
    MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);
}
```

}

**Comment by Harrytion** [comment]
@feilaoda 嗯，谢谢，请问你对于spring的理解是不是比较深啊。spring 的annotation 是你新提交的功能。你对spring的理解应该还可以吧。我如果有spring不懂得问题可以通过这个邮箱去问你吗。

**Comment by Harrytion** [comment]
@feilaoda 嗯，谢谢，请问你对于spring的理解是不是比较深啊。spring 的annotation 是你新提交的功能。你对spring的理解应该还可以吧。我如果有spring不懂得问题可以问你吗。

**Comment by Harrytion** [comment]
@rayzhang0603 我觉得序列化那块还是个硬伤，望改进序列化的那块

**Comment by rayzhang0603** [comment]
@Harrytion 目前的hessian序列化方式在我们生产环境一直使用的，稳定性和性能都还不错。
关于序列化这块有什么改进建议吗？

**Comment by Harrytion** [comment]
@rayzhang0603 我在测试kryo的性能，和稳定性。如果可以的话，可以考虑protobuf，但是protobuf坑太多了。

**Comment by rayzhang0603** [comment]
我们原来做过FST、kryo、msgpack的序列化测试，在不预定义schema的情况下和hessian2性能不会相差太大；如果需要配置schema的话，使用上就没那么方便了，所以还是选择对java更友好一些的hessian了。
也欢迎提序列化模块的扩展的PR，方便不同场景选用

**Comment by Harrytion** [comment]
我昨天试了kryo了，感觉坑特别多。所以现在我也在尝试搞pb吧

**Comment by andot** [comment]
使用 hprose 序列化，比 hessian2 要快一倍，而且跟 hessian 一样，不需要 schema，使用上很方便。

**Comment by rayzhang0603** [comment]
@andot 好的，我们也调研一下hprose序列化。欢迎提供hprose序列化的PR :)

**Comment by andot** [comment]
好的，一会儿我加一个。

**Comment by Harrytion** [comment]
@andot @rayzhang0603 有个问题，当有Map的时候，hprose序列化前和反序列化后的结果的顺序不统一。这也是个坑。你们觉得呢？

**Comment by andot** [comment]
@Harrytion
Map 默认是反序列化为 HashMap，而 HashMap 本身就是没顺序的，所以这个确实不能保证顺序。要保证顺序，需要把类型明确指定为 LinkedHashMap。所以，我觉得这个不能算是坑。

这两天我正在重写 Hprose 序列化和反序列化，重写之后，用户可以自定义某些特殊类型的序列化和反序列化。并且代码会有更好的可读性和可维护性。

你说的这个问题，我可以在新版本中将 Map 反序列化的默认类型从 HashMap 改为 LinkedHashMap，这样就可以保证顺序了，而且 LinkedHashMap 是 HashMap 的子类，也不影响兼容性。就是在反序列化的效率上可能会有所降低。

**Comment by andot** [comment]
@Harrytion Hprose 2.0.12 版本已发布了。更新了序列化和反序列化的实现。你说的这个 Map 的“坑”也填平了。而且还增加了对用户自定义泛型类的序列化和反序列化支持。（不过这个功能在 motan 上用不了，因为 motan 的反序列化接口不支持泛型。）
