### ISSUE TITLE
几个困惑希望大神解答

### ISSUE THREAD

**Issue by T-baby** [weibocom/motan#154]
1、motan支持哪些协议？以及demo？
2、有交流QQ群吗？
3、如果从美国的客户端去连接中国的注册中心并且调用美国的服务，那么这个连接会受到注册中心的影响吗？
4、支持同个服务多次注册吗？
5、建议在配置清单中写明支持哪些配置以及作用。阿里嘎多。

**Comment by sunnights** [comment]
感谢关注，
1. 目前支持自身的motan协议和正在测试的yar协议，后续有支持grpc的计划
2. 暂时没有官方QQ群
3. 客户端只有在第一次调用时向注册中心查询服务信息，获取服务列表后直接向服务发起调用，与注册中心无关，注册中心只提供服务变更、指令变更通知等功能
4. 同一服务多次注册时只要配置不同的ip或端口号即可

**Comment by T-baby** [comment]
那可以是同名的多个服务注册吗？

**Comment by sunnights** [comment]
服务名是接口类的全名，不存在同名的多个服务

**Comment by sunnights** [comment]
服务名是接口类的全名，不存在同名的多个服务

**Comment by T-baby** [comment]
那比如深圳和北京都从镜像中生成实例，各有一个AccountService都注册到同一个注册中心可以么？该怎么做。

**Comment by sunnights** [comment]
直接注册就可以，每个ip+port代表一个服务实例

**Comment by T-baby** [comment]
soga，明白了，那如果一个服务下有多个实例，那么是如何分配的呢？就近原则吗还是？

**Comment by sunnights** [comment]
Motan提供了多种负载均衡策略，也可自行扩展，请参考[配置说明](https://github.com/weibocom/motan/wiki/zh_userguide#%E8%B4%9F%E8%BD%BD%E5%9D%87%E8%A1%A1)

**Comment by T-baby** [comment]
发现一个小bug，在管理后台的右上角名字上悬浮，点击profile想要打开profile.html但这个页面并不存在。
