### ISSUE TITLE
LocalFirstLoadBalance疑似bug，麻烦看一下？

### ISSUE THREAD

**Issue by wps886** [weibocom/motan#155]
doc说“当不存在本地服务，但是存在远程RPC服务，则根据ActivWeight获取远程RPC服务”

然后第72行开始：
`
        if (localReferers.isEmpty()) {
            referers = localReferers;
        }
`

是否应该是：

`
        if (!localReferers.isEmpty()) {
            referers = localReferers;
        }
`

**Comment by rayzhang0603** [comment]
感谢反馈，这里确实是错误的，在下个版本中会修改这个问题

**Comment by rayzhang0603** [comment]
0.2.0版本已修复
