### ISSUE TITLE
0.1.3什么时候会发布

### ISSUE THREAD

**Issue by gooking** [weibocom/motan#156]
新的项目即将启动，打算用这个

问一下，0.1.3 预计什么时候会发布？

**Comment by eatgrass** [comment]
+1

等0.1.3的maven更新了，就可以干掉那一堆的xml了..

**Comment by rayzhang0603** [comment]
目前正在项目中试用yar协议相关功能，准备在下一个版本中一起发布，预计8月初吧。
btw，下一个版本可能是0.2.1，后续的命名规则会是第二位发布新功能、最后一位只做bug修复等改进。

**Comment by eatgrass** [comment]
Hi, @rayzhang0603 , 昨天提了[PR#157](https://github.com/weibocom/motan/pull/157), 提供Java code based配置方式，是否考虑合入呢？ 实在不想加任何xml配置文件了。

**Comment by rayzhang0603** [comment]
@eatgrass 感谢对motan的关注。目前主干的注解方式已经可以做到0 xml配置，使用@EnableAutoConfiguration或者@SpringBootApplication、@ComponentScan("package name")，然后在声明一下   AnnotationBean就可以了。

```
@Bean
public AnnotationBean motanAnnotationBean() {
    AnnotationBean motanAnnotationBean = new AnnotationBean();
    motanAnnotationBean.setPackage("quickstart");
    return motanAnnotationBean;
}
```

稍后我们会更新demo模块，增加相应的demo，如果有什么好的想法和建议，欢迎一起讨论

**Comment by eatgrass** [comment]
Oh, 原来是要这样子,  👍 , close吧。不过仍旧觉得@EnableMotan更帅一些 🙃

**Comment by hellokaton** [comment]
坐等0.1.3发布，我准备使用springboot+motan搭建微服务基础平台。

**Comment by rayzhang0603** [comment]
已发布0.2.0版本
