### ISSUE TITLE
一个服务可以既是服务提供者又是服务消费者吗？

### ISSUE THREAD

**Issue by zfvipgit** [weibocom/motan#159]
我现在有两个服务A和B，他们既是服务提供者，又是消费者，
A消费B，B消费A，这样导致服务在启动的是否报：从服务发现组件中不能获取服务列表的错误，请问有什么好的处理办法吗

**Comment by feilaoda** [comment]
这样设计系统不合理

**Comment by zhaiyuyong** [comment]
可以的 服务相互依赖是不可避免存在的，dubbo在启动时候可以讲check服务存在开关关掉就可以，相信motan应该有这样的实现

**Comment by rayzhang0603** [comment]
referer配置中设置check＝false时是可以启动。
这种互相依赖的情况推荐从业务流程上解决
