### ISSUE TITLE
Add netty 4 transport module

### ISSUE THREAD

**Issue by qdaxb** [weibocom/motan#16]
Netty 3 is TOO old, we should add a module for netty 4.

**Comment by ccc-rrr** [comment]
一些其它的三方库也可以考虑升级到最新，比如log4j2（还能配合disruptor）代替log4j，zkclient，Commons Pool2等等。
motan-springsupport/pom.xml里的spring-web还是3.2.3.RELEASE，demo里用的倒是4.2.4.RELEASE。
能否“motan-springsupport”改为"motan-spring-support"，和其他的模块不一致呢。

**Comment by qdaxb** [comment]
@ccc-rrr 感谢建议。

其它第三方库我们会考虑在有需要的时候升级，log4j的依赖我们未来考虑尽量使用slf4j管理而不关心具体实现，其它依赖目前没有具体升级计划。

spring-web里的依赖已经提了pr #18 修复。

motan-springsupport是一个独立模块，这个名字应该不会改。

**Comment by simpleSOA** [comment]
以后起码要三方模块要考虑升级下，有些包太老了

**Comment by sumory** [comment]
Netty4支持大概会什么时候放出来?

**Comment by qdaxb** [comment]
@simpleSOA 目前我们没有遇到依赖版本太老导致的问题，如果觉得哪个依赖急需升级可以提issue或pr。

@sumory netty4的支持还在规划中，可能要过上一段时间。

**Comment by ghost** [comment]
log4j2自己可以添加支持，只需要在maven中把自带的log相关的jar排除，并增加log4j2相关的实现即可
`<dependency>
    <groupId>com.weibo</groupId>
                <artifactId>motan-registry-zookeeper</artifactId>
                <version>${motan.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-api</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.slf4j</groupId>
                        <artifactId>slf4j-log4j12</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>`

**Comment by ghost** [comment]
“log4j的依赖我们未来考虑尽量使用slf4j管理而不关心具体实现” 这个设计思路是对的。

**Comment by syndory** [comment]
```
private static InternalLoggerFactory newDefaultFactory(String name) {
        InternalLoggerFactory f;
        try {
            f = new Slf4JLoggerFactory(true);
            f.newInstance(name).debug("Using SLF4J");
        } catch (Throwable t1) {
            try {
                f = new Log4JLoggerFactory();
                f.newInstance(name).debug("Using Log4J");
            } catch (Throwable t2) {
                f = new JdkLoggerFactory();
                f.newInstance(name).debug("Using java.util.logging");
            }
        }
        return f;
    }
```
有打算加一个util模块以解决上面这种类似问题的打算吗？

**Comment by louyuting** [comment]
加入netty4的支持，有没有有这个想法的？现在在实施吗？
