### ISSUE TITLE
motan的异常是不是有些粗暴了些？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#164]
我在server端配置的是自定义的异常。结果所有的异常到了客户端都是

`error_message: NettyResponseFuture request timeout: serverPort=127.0.0.1:16551 requestId=1541517695123456001`
实际上是连接成功了，是服务端抛了异常，结果到了客户端全是连接失败的异常。而不是服务端自定义的异常。请问如何配置自定义的异常？

**Comment by rayzhang0603** [comment]
这异常表示client端没有正确获取到server端的返回结果，正常情况下client端会抛出server的自定义异常的。client端日志中是否还有其他的异常？

**Comment by kashuocom** [comment]
这个是server端未能在配置的时间内返回结果，可以把client端的requestTimeout配大一点

**Comment by JianSphere** [comment]
楼上的各位是这样的。由于是远程调用的支付服务，所以比较耗时。设置为500ms就Ok了

**Comment by kris-zhang** [comment]
这个应该跟框架没有关系吧？超时异常，你还要自定义啥？设置大一点timeout嘛
