### ISSUE TITLE
 motan:registry  不支持多 consul / zookeeper 地址

### ISSUE THREAD

**Issue by yelllowhat** [weibocom/motan#166]
在 cluster 模式中， server 注册协调地址是单一的，即不支持多地址，为什么这么说
因为存在  consul / zookeeper 挂掉的情况， 服务确正常还在,这个时候，服务还是不能正常访问
1.   motan:registry  不支持多 consul / zookeeper 地址
2.   如果协调者挂掉， motan server  会多久重新注册?

**Comment by Harrytion** [comment]
不可能不支持的。vmware下面会有一点问题，请用真实的环境

**Comment by rayzhang0603** [comment]
1、motan支持配置多个registry，一个registry也支持配置多个地址（consul目前暂不支持，consul推荐使用本地agent），address配置多个地址时使用逗号进行分隔。
2、zk使用多个注册中心地址时的重新注册机制取决于具体ZkClient的实现

**Comment by yelllowhat** [comment]
谢谢 @rayzhang0603 @Harrytion   两位的解答，zookeeper 是支持多地址的，同时也是支持定义多个 register的,  和  rayzhang0603  说的一样，consul 不支持多地址·

我的场景:
server provider ->  127.0.0.1:8500   ( client 模式启动consul ) , 

这个时候如果 consul 节点停止或被 kill 掉, consul cluster 是发现不了这个服务，也就是出现服务不可用了

测试时，重新拉起 consul client 节点，发现服务是不会被重新注册的

原因分析:
1.  consul pid 会不断的检察 local list 已经注册的接口，不过每个接口的 consul 会自动匹配一个 port 去检测，因为重新启动过，针对接口 port 的探测 已经不是原有注册时的 port ，所以导致一直不成功

说明：这里说的检察 port 不是服务真实的 port ,而是 consul 针对 server provider 分配的检测 port 

解决方式有3 种
1.  给每一个 consul client 注册的服务定义 check{} 配置
缺点：服务发布众多，针对每个配置，都要需要 consul 端改动 check config
1.  由 motan 框架支持自动检察注册, 注册节点失败，定期重新注册 
   缺点：要轮询监听, 正常情况下是多余的
2.  consul 多地址注册 
   优点：即使一个 consul pid 挂掉，其他服务 node 继续发现 Real server 不影响  user client 使用

consul cluster 对 node 节点做到了同步一致性,  但对于 consul node 节点的信息，没有实现 一致性, 所以在 register 这个地方，是一个单点问题

在 log 中未发现，断开 registry 中有日志提醒，这其实需要在 motan frame  中添加日志告警

备注：
通常情况下，我们的服务是多节点部署的，不会存在 我们刚才说的这种情况，在 motan-registry-xx模块
应该支持 断开重连机制，尽量在 frame 层面解决可用性问题

**Comment by rayzhang0603** [comment]
@yelllowhat 非常感谢您的建议，我们会在之后的版本中考虑添加consul的重新注册机制。
local agent一般作为节点监控使用的，如果local agent挂掉，推荐从运维层面对节点及节点上发布的服务进行回收然后重新部署。

**Comment by realskyzou** [comment]
跟踪了下代码，多地址配置下：
RegistryConfig:<motan:registry address="192.168.1.220:2181,192.168.1.220:2182,192.168.1.220:2183" name="registry" connectTimeout="2000" regProtocol="zookeeper" id="registry" />
addr:192.168.1.220:2181,192.168.1.220:2182,192.168.1.220:2183
RegistryConfig->RegistryUrl:zookeeper://192.168.1.220:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc
注册地址只会转换成一个注册中心资源地址，可以确认是个bug。

**Comment by rayzhang0603** [comment]
注册中心多地址和多个注册中心是两个概念。多个地址的意思是只有一个注册中心，这个注册中心有多个backup地址，由注册中心的client处理多个地址的动态切换，例如zkclient。
如果需要多个注册中心，可以配置多个registry，每个使用不同的地址。
