### ISSUE TITLE
motan:protocol 支持 http 协议吗

### ISSUE THREAD

**Issue by yelllowhat** [weibocom/motan#167]
motan 的开源同学们， motan:protocol 支持 http 协议吗 ， 针对同样的服务，切到 motan 框架上来，原有 http 对外服务是不能使用了，需要替换client 引入  motan client 

base netty 可以实现 http 协议，不知 motan 中是否支持, 我查看源码中没有作类似的支持，但在网上看别人介绍，又说motan 支持 http 请问这是内部版本支持吗？

场景： 一般情况下， 内部服务使用  tcp 作为服务协议, 对外在提供 http 应用接口，针对这种情况,需要一个二次包装， 实际上都是一样的服务

**Comment by rayzhang0603** [comment]
目前暂不支持http协议。后续会考虑增加http协议支持，欢迎PR

**Comment by rayzhang0603** [comment]
如果是跨语言调用，欢迎关注yar协议扩展及后续的grpc协议扩展，这两个是基于http/http2的

**Comment by yelllowhat** [comment]
@rayzhang0603  好的谢谢
