### ISSUE TITLE
setSwitcherValue的问题

### ISSUE THREAD

**Issue by T-baby** [weibocom/motan#168]
上面说可以调用

MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true)

来关闭，可是注册好像也是这个吧？

**Comment by sunnights** [comment]
这只是个开关，默认是false
注册的时候要改成true才会对外提供服务
停止服务的时候设成false就可以了

**Comment by Kiplina** [comment]
我设置false以后，还是可以调用服务，是怎么回事

**Comment by rayzhang0603** [comment]
@PangDing389 设置成false后，注册中心会把对应的server状态改为不可用，client收到注册中心变更后，就不会在调用这个server。可以在管理后台查看对应server的状态是否为不可用。
另外，直连方式不受这个开关影响。
