### ISSUE TITLE
客户端首次调用服务端的方法时总是要好久，第二次就快多了，有没什么办法解决？

### ISSUE THREAD

**Issue by zhbgs2000** [weibocom/motan#170]
首次调用：
test_sendsms()结果=test
[INFO]: 2016-08-12 22:02:22 
     |_[MESSAGE]: 耗时:11.02秒,succ=1 

第二次调用：
test_sendsms()结果=test
[INFO]: 2016-08-12 22:02:24 
     |_[MESSAGE]: 耗时:0.038秒,succ=1

**Comment by rayzhang0603** [comment]
你可以先确认一下首次调用的耗时是不是server端处理业务的耗时。一般首次调用时会进行一些类加载，包括框架中的类（如序列化）和业务中的类，框架中的类首次加载大约耗时50～60ms。可以通过跑motan的demo来测试一下耗时情况。
另外，后续会增加预热功能，会在启动时预加载部分框架中的类。请关注

**Comment by zhbgs2000** [comment]
服务端无任何业务处理逻，只是简单的把日志打出来，是通过公网方式访问，内网会快点

**Comment by zhbgs2000** [comment]
服务端无任何业务处理逻，只是简单的把日志打出来，是通过公网方式访问，内网会快点
