### ISSUE TITLE
框架是否支持安全认证或者服务端如何获取客户端连接信息并进行控制？

### ISSUE THREAD

**Issue by zhbgs2000** [weibocom/motan#172]

**Comment by rayzhang0603** [comment]
框架没有提供默认安全认证机制，认证可以通过filter机制进行扩展，通过认证filter在client端添加认证信息到request的attachment中，在server端获取认证信息，并进行认证，认证通过在进行后续调用。可以参考com.weibo.api.motan.filter包下的一些filter实现。

附SPI扩展方法：
1 实现SPI扩展点接口
2 实现类增加注解
@Spi(scope = Scope.SINGLETON)  扩展加载形式，单例或多例
@SpiMeta(name = “motan")  name表示扩展点的名称，根据name加载对应扩展
@Activation(sequence = 100) 同类型扩展生效顺序，部分扩展点支持。非必填
3 增加SPI实现声明 
${classpath}/MATA-INF/services/${SPI interface fullname}文件中添加对应SPI接口实现类全名。
可参照motan-core模块/MATA-INF/services/下的配置
