### ISSUE TITLE
Motan客户端启动

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#174]
服务端提供service接口

客户端通过spring注解注入服务端的service，这时候如果服务端未启动或挂掉的状态下，客户端是无法启动成功的

问题：
客户端是否能在服务端未启动成功的状态下保持成功启动呢？

**Comment by jqs1124** [comment]
我们也遇到了同样问题，client端是否有服务发现设置，如果有怎么设置，如果没有，之后版本有加进去的打算吗

**Comment by rayzhang0603** [comment]
referer配置中设置check＝false时是可以启动

**Comment by rayzhang0603** [comment]
@jqs1124 可以参考https://github.com/weibocom/motan/wiki/zh_overview 具体使用例子请参考demo模块。服务发现支持zk、consul作为注册中心

**Comment by jqs1124** [comment]
@rayzhang0603   我不是这个意思，我的意思是如果先启动client端，client端启动成功后再启动服务端，这个时候client端调用服务端一直都是失败的，这个如何解决

**Comment by rayzhang0603** [comment]
@jqs1124 referer配置中设置check＝false时，没有可用server时可用启动

```
<motan:referer id="motanDemoReferer"
check = "false"....
```

**Comment by thisxulz** [comment]
可以的，配置了即可启动！自动连上服务端，没细看配置列表。。唉

**Comment by jqs1124** [comment]
@will-xlz 你配置是怎么样写的，我们还是不行。
报：NettyChannel connect to server timeout
我看了源码在重试链接的时候connected一直是false（服务端起来的情况下，if语句也执行进去了）
boolean connected = false;
  if(channleFuture.getChannel() != null){
         connected = channleFuture.getChannel().isConnected();
   }
