### ISSUE TITLE
服务端通过路由器映射到公网而出现的问题

### ISSUE THREAD

**Issue by zhbgs2000** [weibocom/motan#175]
路由器暴露18002端口并映射到内网服务器的8002端口
1）当客户端配置中的referer不配置directUrl="公网地址:18002",走注册中心找服务时，获取的为内网服务器192.xxx.xxx.xxx:8002，导致客户端连接服务端失败；
2）当客户端配置的referer配置directUrl="公网地址:18002"，即绕开注册中心来获取服务，则调用服务接口正常。

针对1）出现的现象，有没有什么办法可以通过服务端的配置来解决？

服务端部分配置：
......
`<motan:service interface="com.bob.soa.api.SOAServiceI" accessLog="true" registry="zookeeper_registry"
                   ref="SOAServiceImpl" export="soaService:8002" shareChannel="true" timeout="30000" basicService="serviceBasicConfig">
    </motan:service>`

客户端部分配置：
......
`<motan:referer id="SOAService" interface="com.bob.soa.api.SOAServiceI" basicReferer="motantestClientBasicConfig"
        connectTimeout="30000" requestTimeout="30000" accessLog="true" />`

**Comment by rayzhang0603** [comment]
可以在server端的service配置中增加host配置，server端回把host参数的地址作为server地址注册到注册中心。

```
<motan:service host="公网ip"
```
