### ISSUE TITLE
motan:referer设置了version但在地址里没看到

### ISSUE THREAD

**Issue by jqs1124** [weibocom/motan#176]
error_message: NettyChannel connect to server timeout url: motan://192.168.1.30:30001/com.xxx.Test, cost: 1005, result: false, success: false, connected: false, status: 503, error_code: 10001,r=

我看服务端是：motan://192.168.1.30:30001/v1.0.0/com.xxx.Test，但是client调用端没有

**Comment by rayzhang0603** [comment]
这个报错是建立链接失败，确认client可以连接到server。
设置版本号时需要保证server和client端设置的版本号一致。可以分别贴一下server端和client端的具体配置

**Comment by jqs1124** [comment]
@rayzhang0603 谢谢，是我server设置了host
