### ISSUE TITLE
是否可以控制客户端重连？

### ISSUE THREAD

**Issue by zhbgs2000** [weibocom/motan#178]
已通过spi filter的机制扩展实现了安全认证，现在想要做的是当客户端认证失败，如何来控制禁止重连？

**Comment by rayzhang0603** [comment]
暂时没有禁止建立连接的方法。
这个认证机制是为了防止恶意调用，还是单纯需要控制某些client端不能访问某些server？如果要防止恶意调用只能在认证filter中进行控制。如果是控制client端调用不同server可以通过设置不同group实现。例如groupA的client 只会访问groupA的server，不会访问groupB的server
