### ISSUE TITLE
关于优雅的停止服务的问题

### ISSUE THREAD

**Issue by cheniqit** [weibocom/motan#182]
motan提供了地址服务的口子。

`MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true)`

但我的问题是，为什么默认不设置为true呢？

每次启动服务之后还需要去调用该代码，这样的做法是基于什么考虑的？

**Comment by rayzhang0603** [comment]
motan是通过这个开关控制是否对外提供rpc服务的。
一般正式环境使用时是需要验证服务正常后才正式对外提供服务的，防止有问题的服务注册到线上。另外在停机的时候，可以先通过开关暂停服务，等没有请求后在进行shutdown。

**Comment by tangkai007** [comment]
小白咨询几个问题：
1.服务端启动必须要执行这段代码才能正常的调用， 这样是出于什么样的考虑，比如实际的应用场景，当我的新服务注册到注册中心，是出于什么样的场景考虑才默认设置为false
2.优雅关机，是不是可以使用流量切换的方式，将所有的流量请求分派到其他的机器

MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true)
