### ISSUE TITLE
motan如何做zookeeper安全验证的的

### ISSUE THREAD

**Issue by jqs1124** [weibocom/motan#184]
现在想对zookeeper的访问做安全验证，在motan里怎么配置
如果用motan加filter是否意味着，通过dubbo等连接zookeeper是被拒绝掉的

**Comment by rayzhang0603** [comment]
目前motan的zkregistry不支持digest 类型acl配置，后续版本会增加相应功能。如果需要做安全验证，可以在zookeeper服务端使用ip类型的acl

**Comment by jqs1124** [comment]
@rayzhang0603   用ip类型的acl具体怎么配置

**Comment by jqs1124** [comment]
@rayzhang0603  服务接口向zookeeper里注册也是通过motan，设置zookeeper服务端使用ip类型的acl  不也是在motan配置里设置的吗？  这个怎么配置

**Comment by rayzhang0603** [comment]
acl 是zookeeper的安全机制，通过配置zookeeper的acl限制哪些ip能访问/motan或者/motan/${group}路径
可以参考http://zookeeper.apache.org/doc/trunk/zookeeperProgrammers.html#sc_ZooKeeperAccessControl
