### ISSUE TITLE
motan yar 如何以 服务注入的方式引用

### ISSUE THREAD

**Issue by yelllowhat** [weibocom/motan#186]
在 0.2.2 版本中增加了 yar 方式发布服务，是以 http 方式暴露出来服务接口， 在 demo 示例中, 
直接采用 http 方式引用 如下：
String result = yarClient.call("http://127.0.0.1:8003/openapi/yarserver/test", "testString", String.class,
                "yar");
这种方式是很不 优雅的，而且一但服务发布，client 需要知道具体的 ip 与 port , 来引用服务, 在服务管理中不应该这样操作，如同原始的 rpc java app 一样，服务间 通过 ref service 来组装新的服务和应用

我试一下通过 ref service 来引用 yar 服务

一直报 404 ，请问该如何正确引用,还是说不支持 

参考配置：
1. motan_demo_server_yar.xml 示例按demo 配置不做改动
2. motan_demo_client_yar.xml // 增加配置

< motan:registry regProtocol="local" name="registry" />

```
<!-- 协议配置。为防止多个业务配置冲突，推荐使用id表示具体协议。 -->
< motan:protocol id="demoYar" default="true" name="yar"
    maxServerConnection="80000" maxContentLength="1048576"
    maxWorkerThread="800" minWorkerThread="20" />

<!-- 通用referer基础配置 protocol="demoYar"  -->
< motan:basicReferer requestTimeout="200" accessLog="true"
    retries="2" group="motan-demo-rpc" module="motan-demo-rpc"
    application="myMotanDemo" registry="registry"
    id="motantestClientBasicConfig" throwException="true" check="true" />

<!-- 具体referer配置。使用方通过beanid使用服务接口类 -->
< motan:referer id="yarService"
    interface="com.weibo.motan.demo.service.YarService" connectTimeout="300"
    requestTimeout="300" basicReferer="motantestClientBasicConfig" />
```

client java 代码

ApplicationContext ctx = new ClassPathXmlApplicationContext(
                new String[] { "classpath:motan_demo_client_yar.xml" });

```
    YarService service = (YarService) ctx.getBean("yarService");
    for (int i = 0; i < Integer.MAX_VALUE; i++) {
        System.out.println(service.hello("motan" + i));
        Thread.sleep(1000);
    }
    System.out.println("motan demo is finish.");
    System.exit(0);
```

启动异常;

 Error creating bean with name 'yarService': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: ClusterSupport No service urls for the refer:yar://192.168.1.73:0/motan-demo-rpc/com.weibo.motan.demo.service.YarService/1.0/referer, registries:[local://127.0.0.1:0/com.weibo.api.motan.registry.RegistryService?group=default_rpc], status: 404, error_code: 10101,r=null

排查:
 查看示例代码中，通过 http 方式 call 的方式引用服务，跟踪代码 ， 一直是 纯的  http 请求操作， header + body ，跟服务引用已经没有关系了

**Comment by rayzhang0603** [comment]
motan暂不支持以服务注入方式引用yar 服务（使用motan作为yar client）。
目前yar协议主要解决java与php互通的问题，当java作为服务端，php作为client端，php可以在不做任何修改的情况下通过yar 协议使用java的服务。
而使用php做server、java做client的场景下（一般这种场景比较少），php的yar server不支持注册服务等功能，所以java作为client 时也没有必要通过motan调用服务。yarclient是个单独的小模块，是个类似httpclient这样的简易客户端，只能通过域名或ip访问yar服务。
如果server端和client端都使用java，不建议使用yar协议。

**Comment by yelllowhat** [comment]
嗯，好的谢谢！

为什么我有这样的尝试，说一下背景

1,  传统以 Reset 方式发布的服务 // 因为除了基础的 service , 还存在一些高级的服务应用
2.  rpc -service  <->  rest api 之间相互引用时， 存在不一致性,不能像 抽象成服务一样, 统一看待
3.  服务隔离性 // 无论是 tcp / 还是 http 协议，同一组的服务引用自动隔离

基于以上两点所以需要 motan 支持 http 注入方式  来协调应用，  要么全部服务化取消这种场景( 需要时间，也需要全部改造完成  )

另外在改造过程中，不能一下子到位的全部服务化， 部分应用还是以 rest 的方式提供，如果能平稳的将 rest 应用移植到 motan 中并提供 http 服务，将会是一件美事 ( 有时候 一些功能需要 同时支持  rpc 与 rest 接口 )。

同样的 http 协议，我们也希望 得到统一的管理，即服务自动隔离引入 (自动引用同一 group 的服务 ), 而不是由 client 来维护我需要引用哪些服务. ( 这个看起来虽然跟 motan 没有什么太大的关系 )

我们通过 motan 的  统一group -module 名称 来隔离 发布服务， 如同样的服务发布 3 份, dev , test , product 等

不知在计划中，会不会支持 http 方式发布 ,并支持服务注入 功能, 有这样的累计需求与计划吗?

**Comment by rayzhang0603** [comment]
感谢建议，我们会评估一下这个需求。

**Comment by yelllowhat** [comment]
感谢 @rayzhang0603  耐心的回复

也可以告诉我一下，如何实现的思路

站在 frame 的角度，如果只是提供一个 http 协议，而没有服务治理，是没有意义的
如同本例 demo 当中  由 client 指定 url 访问 motan http service  . 通常这种方式是不可靠的

思考:
java 多个 http service provider 的场景
1.   client 如何 负载调用  // 通过引入 f5 , nginx ,  haproxy 做代理负载
2.   client 如何动态维护服务列表  //  服务的添加 与删除, 这里需要额外的 script 来实现动态监控 借助 consul 监测服务, 来动态改动配置

如果这样做了，就显的南辕北辙了, 笨重而不可维护 , 而且也与 motan 的初衷不符合， 面向 service 架构 

同样使用 Yar_Client / http client 调用  motan http service 要实以上功2点功能，也需要进行二次的封装来实现一致性和可靠性

**Comment by rayzhang0603** [comment]
目前php的yar协议并没有统一的服务发现机制，所以php的yar server和php的yar client无法支持motan的服务发现机制。目前的yar协议适配主要完成了java与php的yar协议交换，通过nginx或者其他代理方式能够实现与现有php yar协议一致的交互。
php client增加服务发现机制需要开发php扩展来实现，目前还没有相关开发排期。
对于跨语言的服务发现机制，后续考虑会添加agent本地代理方式实现，以减少不同语言客户端的开发，agent方式与目前的nginx等代理方式是可以无缝切换的。
