### ISSUE TITLE
请问，开发指南还要多久可以编写好啊？

### ISSUE THREAD

**Issue by mygreat** [weibocom/motan#189]
请问，开发指南还要多久可以编写好啊？

**Comment by rayzhang0603** [comment]
最近因为业务开发任务较重，还没有编写完成，十分抱歉！尽量下周先把如何开发spi扩展的部分先添加到wiki，后续再逐步完善

**Comment by jqs1124** [comment]
@rayzhang0603  可以让一些外部有兴趣的人一起加入完成

**Comment by rayzhang0603** [comment]
好啊，有兴趣的小伙伴都可以一起加入，可以整理成markdown文档，我们更新到wiki中

**Comment by qdaxb** [comment]
@jqs1124 https://github.com/weibocom/motan/wiki/zh_developguide 
正在逐步完善文档，欢迎加入。

**Comment by loveri** [comment]
菜鸟问题，按照github里motan的介绍使用maven搭建了一个demo环境，结构为：demo-api,demo-client,demo-server,zookeeper做注册中心。同步调用没有问题，当我在demo-api里的接口上加入@MotanAsync注解，并将target/generated-sources/annotations手动设置为source path后，compile后motan并没有自动生成一个以Async结尾的类，也没报错，请问是什么原因呢，是我哪里还没有配置到吗？附上demo-api的pom文件，请高手指教：
`<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.global.common.service</groupId>
  <artifactId>motan-api</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>motan-api</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <motan.version>RELEASE</motan.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>test</scope>
    </dependency>
    <dependency>  
        <groupId>com.weibo</groupId>  
        <artifactId>motan-core</artifactId>  
        <version>${motan.version}</version>  
    </dependency>  
    <dependency>  
        <groupId>com.weibo</groupId>  
        <artifactId>motan-transport-netty</artifactId>  
        <version>${motan.version}</version>  
    </dependency>  
  
    <dependency>  
        <groupId>com.weibo</groupId>  
        <artifactId>motan-registry-zookeeper</artifactId>  
        <version>${motan.version}</version>  
    </dependency>  
  
    <dependency>  
        <groupId>com.weibo</groupId>  
        <artifactId>motan-springsupport</artifactId>  
        <version>${motan.version}</version>  
    </dependency>  
    <dependency>  
        <groupId>org.springframework</groupId>  
        <artifactId>spring-context</artifactId>  
        <version>4.2.4.RELEASE</version>  
    </dependency>  
    <dependency>  
        <groupId>org.slf4j</groupId>  
        <artifactId>slf4j-api</artifactId>  
        <version>1.5.8</version>  
    </dependency>  
  
    <dependency>  
        <groupId>org.slf4j</groupId>  
        <artifactId>slf4j-log4j12</artifactId>  
        <version>1.5.8</version>  
    </dependency>  
  
    <dependency>  
        <groupId>log4j</groupId>  
        <artifactId>log4j</artifactId>  
        <version>1.2.14</version>  
    </dependency>
  </dependencies>
  
  <build>
  <pluginManagement>
  	<plugins>
  		<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.10</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/annotations</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
  	</plugins>
  	</pluginManagement>
  </build>
</project>`

**Comment by loveri** [comment]
接上
<build>
  <pluginManagement>
  	<plugins>
  		<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.10</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/annotations</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
  	</plugins>
  	</pluginManagement>
  </build>

**Comment by loveri** [comment]
`<build>
  <pluginManagement>
  	<plugins>
  		<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>1.10</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/annotations</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
  	</plugins>
  	</pluginManagement>
  </build>`
