### ISSUE TITLE
NettyChannelHandler channelDisconnected

### ISSUE THREAD

**Issue by jqs1124** [weibocom/motan#191]
NettyChannelHandler channelDisconnected: remote=/10.141.221.191:33826 local=/10.141.126.113:30001 event=UpstreamChannelStateEvent

请问这个问题如何解决

**Comment by rayzhang0603** [comment]
能描述一下具体使用场景吗？这个就是netty的断开链接异常，正常情况下会进行重连，不会对业务产生影响

**Comment by jqs1124** [comment]
@rayzhang0603   admin管理后台对用户推送消息（motan client端），调用消息发送系统（motan server端），然后有些推送成功有些异常，就是上面的异常

**Comment by rayzhang0603** [comment]
有没有超时异常？如果使用公网可以适当调大请求超时时间？如果业务上能够支持重试，可以配置重试机制。
protocol标签中配置haStrategy="failover"，在basicreferer或者具体的referer标签中配置retries="2"，表示重试次数
