### ISSUE TITLE
Failed to bind to: 0.0.0.0/0.0.0.0:8002

### ISSUE THREAD

**Issue by T-baby** [weibocom/motan#193]
不知道为什么老是出现这个问题，而且换了端口也没有用。我也查过并没有被占用。

**Comment by T-baby** [comment]
多个rpc服务不能使用同一个端口？

**Comment by yelllowhat** [comment]
你好，在使用 motan 发布服务时，同一 goup / module 的服务，不能多次发布在同一个 port 上，多个服务是可以使用一个 port 的，请检察一下 port 占用情况，注意同一个包名相同的接口试为同一下接口

**Comment by rayzhang0603** [comment]
共享端口的service需要配置shareChannel=true
