### ISSUE TITLE
请问motan支持隐式传参么?

### ISSUE THREAD

**Issue by sunxiang0918** [weibocom/motan#196]
也就是 在调用远程接口前,在上下文中设置一些辅助的参数.然后服务端能接受到这些参数来进行使用. 类似于Rest调用中的 Header传值. 

类似于dubbo中的此项功能: http://dubbo.io/User+Guide-zh.htm#UserGuide-zh-隐式传参 

谢谢啊~

**Comment by rayzhang0603** [comment]
目前不支持。motan有attachment参数传递机制，但是是面向filter扩展的，只能在框架层使用，业务层无法使用。如果是通用参数建议通过filter spi机制进行统一处理。
后续计划在支持异步调用时开放这个功能。
