### ISSUE TITLE
关于motan manage问题

### ISSUE THREAD

**Issue by maxiaoguang8011** [weibocom/motan#198]
1.能否提供一个 motan-manage.war的管理后台。我这把一直编译报错。
2.我把所有的开源项目一起导入到了myeclipse里， motan-demo这个项目报错：failed to read artifact descriptor for de.ailis.phe   。 但是这个de.ailis.phe一直没找到在哪里？能否提供一下jar包？
3.

**Comment by rayzhang0603** [comment]
第一个问题能提供一下编译报错信息吗
第二个问题可能是maven仓库配置的问题，可以在项目中配置一下如下maven仓库

```
<repositories>
    <repository>
        <id>ailis-releases</id>
        <name>Ailis Maven Releases</name>
        <url>http://nexus.ailis.de/content/groups/public/</url>
    </repository>
</repositories>
```
