### ISSUE TITLE
请问motan可不可以选择logback作为日志框架

### ISSUE THREAD

**Issue by angelala00** [weibocom/motan#201]

**Comment by feilaoda** [comment]
可以。去掉log4j

**Comment by rayzhang0603** [comment]
motan默认使用的slf4j，支持logback的

**Comment by angelala00** [comment]
去掉log4j之后 zkclient 的日志貌似就有问题了  它只支持log4j

**Comment by thermosym** [comment]
用 log4j-over-slf4j 可以把 zkclient 的 log4j 日志调用转过去

**Comment by Tom-Goong** [comment]
楼上正解。

slf4j只是日志的接口，具体实现选用log4j或者logback都可以。zkclient的问题，可以使用桥接器。相似的其他桥接可以参考这里。有实现原理。http://www.slf4j.org/legacy.html
