### ISSUE TITLE
现在有哪些公司在使用motan，有粗略的统计吗？

### ISSUE THREAD

**Issue by xingkaihu** [weibocom/motan#203]
现在有哪些公司在使用motan，有粗略的统计吗？

**Comment by rayzhang0603** [comment]
没有相关统计，目前已知的有 B站、有信等已经在部分服务中使用，其他还有搜狐视频、央视网等一些公司和部门在做相关调研与试用

**Comment by JianSphere** [comment]
请问有没有微信交流群或者QQ群？
