### ISSUE TITLE
请问motan如何做限流？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#205]
请问motan如何做限流？限制某个IP的调用次数。我该怎么做呢？

**Comment by rayzhang0603** [comment]
可以通过filter扩展来实现，自定义个limitFilter，可以在server端过滤request请求，具体可以参考com.weibo.api.motan.filter包下的filter实现，以及https://github.com/weibocom/motan/wiki/zh_developguide#扩展机制
