### ISSUE TITLE
问一个比较菜鸟的问题。

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#206]
假设A服务使用 ip1，ip2 然后B服务依赖A服务。最后A服务需要升级，于是将ip1 ip2换成了 ip2，ip3
请问这个对B服务来说是透明的吗？B服务是不是不需要做任何改变就能调用A服务？A服务要改变IP需要做什么？比较菜鸟了。。希望大神们解答

**Comment by srmsh** [comment]
不需要啊   用consul

**Comment by JianSphere** [comment]
zookeeer不行么？

**Comment by srmsh** [comment]
可以吧   我用的是consul   zk我没有用过

**Comment by rayzhang0603** [comment]
A服务ip变更，B服务不需要做任何处理

**Comment by yelllowhat** [comment]
这里需要注意，如更换了部署 ip ,原有 ip 的服务在 consul 任然存在， 需要手工去清理，不存在服务部署节点，  @rayzhang0603  这块有没有相应的工具类呢？还是要自已实现清理呢

**Comment by rayzhang0603** [comment]
@yelllowhat 我们确认一下这个场景，如果确认是bug会在后续版本中修复。目前没有相应的清除工具，后续考虑在manage模块中提供删除功能。

**Comment by yelllowhat** [comment]
@rayzhang0603  你好

说明： rc ( registry center )
这个问题首先不是一个功能问题,  是个运维问题, 当然也可以考虑框架中实现更加智能/简洁

1. 当我们发布新的 server 节点上线的时候，陆陆续续会向注册中心添加节点信息, 这个时候 rc 中心会记录这些服务节点 list 

2. 当已经注册的 list 列表中的服务发生转移，如 将原有 A 服务部署在 192.168.0.5 机器上应用，迁移到了   
    192.168.0.6  ,  等类似的情况服务的物理位置发生了变动  
  ( 将来在 docker 中动态发布的场景会很多 )

问题： 

对于 rc 来说，他不能够确认 service list 中的服务哪些是迁移的哪些是真正 down 掉的
所以他会一直保持这些历史的  service list  , 对于这些 真正被 move 的服务无法得到清理,将一直保存, 直到手工进行清理服务例表才可以保持干净

Q：
1. 每当 clent 启动的时候，还会scan 这些服务列表
2.  RC 相对应的也要检察这些 move 的 service  
以上操作实际是没有必要.

结论： 
所以有必要在  manage 增加管理功能，增加反向，维护能力，来维护  service list 功能

**Comment by rayzhang0603** [comment]
嗯，后续计划会在manager模块中增加注销服务的能力。也会在registry中增加unregisterAll()方法，提供server本机注销的能力
