### ISSUE TITLE
consistent 也有数组越界bug

### ISSUE THREAD

**Issue by srmsh** [weibocom/motan#207]
如题

![image](https://cloud.githubusercontent.com/assets/11769478/18780691/645e2174-81b1-11e6-9961-b7a838af0f96.png)

**Comment by leizhiyuan** [comment]
这个取余数之后不会越界吧。。
你说的是consistentHashReferers 这个的大小可能是0？然后被0除的情况？

这种情况代码中好像确实没有判断。如果是这样的话，可以在这里判断，如果consistentHashReferers的size=0，可以直接返回。

**Comment by srmsh** [comment]
取模之前的数可能是负数啊

**Comment by rayzhang0603** [comment]
确实存在越界bug，下一版本将会修复，感谢反馈！
