### ISSUE TITLE
在SpringMVC中使用注解调用对象为null

### ISSUE THREAD

**Issue by iFighter** [weibocom/motan#208]
**motan_client配置**
 
    <motan:protocol name="motan" haStrategy="failover"
                    loadbalance="roundrobin" maxClientConnection="10"  minClientConnection="2" requestTimeout="1000" />

```
<!-- zookeeper注册中心 -->
<motan:registry regProtocol="zookeeper" name="my_zookeeper" address="192.168.1.18:2181"/> 

<motan:basicReferer id="clientBasicConfig" requestTimeout="1000" accessLog="false"
                    retries="0" group="motantest_service" module="motantest_service"
                    application="motantest_service" protocol="motan" registry="my_zookeeper"
                     throwException="false" check="true"/>   

<motan:annotation package="com.navy.service.webapi"/>
```

**Controller代码**
package com.navy.service.webapi;
import com.navy.service.api.SampleService;
import com.navy.service.helpers.AppConfig;
import com.navy.service.helpers.BaseKeyValuePair;
import com.navy.service.helpers.KeyValuePair;
import com.navy.service.helpers.OkHttpUtils;
import com.navy.service.helpers.ResultCallback;
import com.navy.service.proxy.SampleServiceProxy;
import com.weibo.api.motan.config.springsupport.annotation.MotanReferer;

@Controller
@RequestMapping("/Test")
public class TestController {
    Logger logger = Logger.getLogger(TestController.class); 
    **@MotanReferer(basicReferer = "clientBasicConfig")
    SampleService sampleService;**

```
/*@Autowired
SampleService sampleService;*/  

/**
 * sayHello
 * @param name
 * @return
 */
@RequestMapping(value = "/sayHello", method = RequestMethod.GET)
@ResponseBody
public String sayHello(String name) {
    logger.info(sampleService == null);
```

//      return sampleService == null?"SampleService为空":"SampleService不为空";
        return sampleService.sayHello(name);
    }

**调用显示，SampleService为空**

但是，在配置中以常用的单个Bean的方式配置(motan referer)
然后Controller中直接使用Autowired，如下
@Autowired
SampleService sampleService;

则服务可以正常调用了。

**Comment by yelllowhat** [comment]
请确认配置 motan_clien 文件加载顺序，应该在扫描 包前加载

尝试采用以下两种方式：
1.   MotanReferer 填写完整的 group dirurl , 
@MotanReferer(basicReferer = "motantestClientBasicConfig", group = "testgroup", directUrl = "127.0.0.1:8002")
1. 在  添加类 @Component 注释, 

@Component
public class DemoRpcHandler {
    @MotanReferer
    private MotanDemoService motanDemoService;
}

motan_demo_client_annotation.xml
<context:component-scan base-package="com.weibo.motan.demo"/>
<motan:annotation package="com.weibo.motan.demo.client"/>

**Comment by iFighter** [comment]
@yelllowhat 谢谢您的解答！

**Comment by mark988** [comment]
你好，我也这样写的：

```
@Autowired 
@MotanReferer(basicReferer = "motantestClientBasicConfig" , group = "motan-demo-rpc", directUrl = "127.0.0.1:9000")
private UsersServiceI  usersSerice;
   这个对象也是NULL 。。。。。
```
