### ISSUE TITLE
Hessian 對於 java8 的 time 無法支援

### ISSUE THREAD

**Issue by smallufo** [weibocom/motan#209]
我看到 motan 使用 hessian 4.0.38 作為底層溝通機制，但是 hessian 已經很久沒有 maintain。其對於 java8 內新的的 classes 無法支援，例如 LocalDateTime 等，會改用 UnsafeSerializer ，請問 motan 對於這點該怎麼處理？如果 object 包含 java.time.\* ，會怎麼辦呢？

**Comment by andot** [comment]
改为使用 hprose 或者 fastjson 序列化就行了。这两种序列化对 java8 的时间类型都支持。
