### ISSUE TITLE
服务版本化控制怎么实现

### ISSUE THREAD

**Issue by thermosym** [weibocom/motan#211]
服务A依赖服务B，当B服务更新版本的时候，比如接口返回的对象增加、改变了某些字段，更极端情况下某些老接口的签名不兼容了，这种情况下motan似乎没法控制那些还没有更新客户端的A服务实例去访问老接口的B服务实例。

如果无法实现，是否就意味着：
1. 要么，如果破坏了兼容性，部署就必须联动一起，无法解决
2. 要么，尽量不破坏兼容性，服务A自行选择更新客户端接口的时间

**Comment by rayzhang0603** [comment]
service升级时可以按以下任意一种方式进行兼容升级：
1、新旧server配置不同的group
2、新旧server还使用相同group，但是配置不同的version，如新版本设置version=0.2
3、server接口中新增加method，原有method不作变更。新服务使用新的method，等client端全部更新后在下掉旧的method

**Comment by thermosym** [comment]
感谢，[文档](https://github.com/weibocom/motan/wiki/zh_userguide#%E6%9C%8D%E5%8A%A1%E6%8F%90%E4%BE%9B%E6%96%B9)里只有关于group配置的描述，在代码 [AbstractInterfaceConfig.java](motan/motan-core/src/main/java/com/weibo/api/motan/config/AbstractInterfaceConfig.java) 有发现version字段可配置
