### ISSUE TITLE
在zookeeper上注册的ip是内网ip？

### ISSUE THREAD

**Issue by T-baby** [weibocom/motan#214]
如题，因为zookeeper跟应用是在不同云服务商的，但是motan在zookeeper上注册是192.168.0.2:8002内网地址

**Comment by T-baby** [comment]
已解决这个问题，请问要怎么以eth1网卡的ip来注册

**Comment by rayzhang0603** [comment]
如果需要指定ip可以在配置中设置host参数，也可以设置server的hostname。目前没有方法直接指定某个网卡ip

**Comment by T-baby** [comment]
能给个配置例子么，灰常感谢。

**Comment by rayzhang0603** [comment]
host属性可以配置在basicservice中，也可以配置在具体的service中

```
 <motan:basicService export="demoMotan:8002" host="192.168.1.11"
                    group="motan-demo-rpc" .../>
```

**Comment by T-baby** [comment]
谢谢撒。我自己关闭这个问题吧。
