### ISSUE TITLE
通过motan方法被执行三遍

### ISSUE THREAD

**Issue by T-baby** [weibocom/motan#215]
我在web服务上连接了motan，http调用服务时只运行了一遍这个服务，但是写了一个@Test的测试类，通过motan调用时就会调用方法三遍，这是为啥

**Comment by rayzhang0603** [comment]
可以确认一下是不是配置了haStrategy="failover"，并且设置了retries＝2
这个策略会在请求超时或失败时最多重试retries次。重试时有warn日志，关键字为“FailoverHaStrategy Call false for request”
如果非幂等的方法，可以配置haStrategy="failfast"，失败不会重试

**Comment by T-baby** [comment]
太爱你了，已解决
