### ISSUE TITLE
<motan:protocol name="" ></motan:protocol> 之后如何调用？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#220]
是 <motan service> 中的group吗？

另外请问motan中的组和moudle有什么区别呢？

**Comment by rayzhang0603** [comment]
moudel是一个更细粒度的划分，一个server属于一个group，一个server上可能跑了多个moudel，每个moudel提供若干service。统计信息的时候以moudel为单位进行统计。
实际使用中一般不用区分moudel，moudel和group配置成相同的即可。

**Comment by JianSphere** [comment]
group 提现的是集群的概念吗？一个Group可不可以有多个 protocol？

**Comment by JianSphere** [comment]
并且motan中的group与 dubbo 服务分组 是不是类似的呢？

**Comment by rayzhang0603** [comment]
motan中的group与 dubbo 服务分组是不同的概念，motan中group主要用来做流量管理，一般group由机房和业务线组成，相同group的server和client才可以访问，这样可以做到同机房就近访问以及核心非核心服务的隔离。

例如：group可以是电信机房＋核心服务、电信机房＋非核心服务、联通机房＋核心服务、联通机房＋非核心服务。。。
一个group下可以有多个服务，每个服务可以使用不同protocol，不同group下也可以有相同服务，例如每个group下都可以有userService服务

**Comment by JianSphere** [comment]
非常感谢
