### ISSUE TITLE
如何方便的docker化？ 我看好多服务配置，IP，注册的地址都是通过配置文件

### ISSUE THREAD

**Issue by ninyjun** [weibocom/motan#221]
如何方便的docker化？ 我看好多服务配置，IP，注册的地址都是通过配置文件
如果直接打在镜像里的话部署就不太方便，能否支持环境变量的方式传入？

**Comment by rayzhang0603** [comment]
这些配置中只有注册中心需要配置地址，一般是配置成内部域名或vip即可。
如果需要指定主机地址可以通过配置hostname实现
如果需要动态配置参数可以使用spring的placeholder方式，实现自定义的替换规则。这个不太容易通用化，不太适合集成到RPC框架中。
另外，微博的DCP混合云平台后续有开源计划，欢迎关注
