### ISSUE TITLE
请问motan如何做负载均衡？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#224]
如果使用Zookeeper的话，motan该如何做负载均衡呢? 如果不使用zookeeper的话。直接使用motan的话能不能做到负载均衡。不需要zookeeper

**Comment by qdaxb** [comment]
请参考：[不使用注册中心](https://github.com/weibocom/motan/wiki/zh_userguide#不使用注册中心)

此模式下服务优雅关闭无法使用。

**Comment by JianSphere** [comment]
那负载均衡是motan自己实现的吗？

**Comment by rayzhang0603** [comment]
可以通过loadbalance进行配置，请参考https://github.com/weibocom/motan/wiki/zh_userguide#负载均衡
