### ISSUE TITLE
<motan:basicService>中的注册中心是什么意思？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#226]
```
<motan:basicService requestTimeout="220" export="motan:8002"
    group="motan-demo-rpc" accessLog="false" shareChannel="true" module="motan-demo-rpc"
    application="myMotanDemo" registry="motanServer" id="serviceBasicConfig" />

```

运行以后直接报错：

---

APPLICATION FAILED TO START

---

Description:

A component required a bean named 'motanServer' that could not be found.

Action:

Consider defining a bean named 'motanServer' in your configuration.

应该是注册中心找不到。请问这个注册中心是个什么东东？

**Comment by rayzhang0603** [comment]
注册中心用来发现提供服务的具体server地址。不使用注册中心可以按quickstart配置，使用zk注册中心请参考motan－demo模块，server 端运行DemoRpcServer，client端运行DemoRpcClient
