### ISSUE TITLE
试了试quickstart的使用注解方式配置motan，报了一些错。

### ISSUE THREAD

**Issue by lexburner** [weibocom/motan#231]
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fooServiceImpl' defined in file [C:\sinosoft\workspace\springboot_demo\target\classes\com\example\myproject10\service\FooServiceImpl.class]: Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'motan' is defined
>     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:776) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:861) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:541) ~[spring-context-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
>     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
>     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
>     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.4.0.RELEASE.jar:1.4.0.RELEASE]
>     at com.example.myproject10.SpringBootRpcServerDemo.main(SpringBootRpcServerDemo.java:20) [classes/:na]
> Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'motan' is defined
>     at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:702) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1180) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at com.weibo.api.motan.config.springsupport.util.SpringBeanUtil.getMultiBeans(SpringBeanUtil.java:21) ~[motan-springsupport-0.2.1.jar:na]
>     at com.weibo.api.motan.config.springsupport.AnnotationBean.postProcessAfterInitialization(AnnotationBean.java:223) ~[motan-springsupport-0.2.1.jar:na]
>     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:422) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1583) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-4.3.2.RELEASE.jar:4.3.2.RELEASE]
>     ... 15 common frames omitted

我没有引用到motan这个类，是内部自动加载的？还是我漏了什么配置？希望大神指点

**Comment by lexburner** [comment]
是在启动server时就报的错

**Comment by lexburner** [comment]
谢谢，试了一下，改成  @Bean(name = "demoMotan")=>@Bean(name = "motan")之后可以正常运行
我是参考的quickStart上的demo来测试的，不知道是否是quickStart有误?

@Bean(name = "demoMotan")
    public ProtocolConfigBean protocolConfig1() {
        ProtocolConfigBean config = new ProtocolConfigBean();
        config.setDefault(true);
        config.setName("motan");
        config.setMaxContentLength(1048576);
        return config;
    }

```
@Bean(name = "registryConfig1")
public RegistryConfigBean registryConfig() {
    RegistryConfigBean config = new RegistryConfigBean();
    config.setRegProtocol("local");
    return config;
}

@Bean
public BasicServiceConfigBean baseServiceConfig() {
    BasicServiceConfigBean config = new BasicServiceConfigBean();
    config.setExport("demoMotan:8002");
    config.setGroup("testgroup");
    config.setAccessLog(false);
    config.setShareChannel(true);
    config.setModule("motan-demo-rpc");
    config.setApplication("myMotanDemo");
    config.setRegistry("registryConfig1");
    return config;
}
```

**Comment by rayzhang0603** [comment]
export配置中配置的是protocol bean的name和端口。所以定义protocol的bean时 bean name必须与export中的一致。
quickstart上的basicservice的export配置的是"demoMotan:8002"，因此ProtocolConfigBean的bean name就是demoMotan。
你的异常中寻找的bean name是motan，所以ProtocolConfigBean的bean name就需要配置成motan。

**Comment by lexburner** [comment]
嗯，我知道config.setExport("demoMotan:8002");与@Bean(name = "demoMotan")要一致，我就是一致的，但我这么配置之后：
@Bean(name = "demoMotan")
public ProtocolConfigBean protocolConfig1() {
ProtocolConfigBean config = new ProtocolConfigBean();
config.setDefault(true);
config.setName("motan");
config.setMaxContentLength(1048576);
return config;
}

@Bean(name = "registryConfig1")
public RegistryConfigBean registryConfig() {
    RegistryConfigBean config = new RegistryConfigBean();
    config.setRegProtocol("local");
    return config;
}

@Bean
public BasicServiceConfigBean baseServiceConfig() {
    BasicServiceConfigBean config = new BasicServiceConfigBean();
    config.setExport("demoMotan:8002");
    config.setGroup("testgroup");
    config.setAccessLog(false);
    config.setShareChannel(true);
    config.setModule("motan-demo-rpc");
    config.setApplication("myMotanDemo");
    config.setRegistry("registryConfig1");
    return config;
}
会报我所提问的：找不到motan类这个异常

两边同时改成config.setExport("motan:8002");与@Bean(name = "motan")之后，才能正常运行，是否在其他地方引用到了name=motan的Bean?

**Comment by rayzhang0603** [comment]
嗯，是这个原因，是配置具体的@MotanService(export = "8002")没有指定protocol，这时默认会加载bean name是motan的默认协议。我修改一下wiki吧. 感谢反馈！

**Comment by ghost** [comment]
motan-demo 也要及时修改啊，耽误了一上午的时间。。。

**Comment by rayzhang0603** [comment]
motan-demo已经修改提交了。不过demo模块中是有name=motan的protocol声明的，直接在demo中运行SpringBootRpcServerDemo也是正常的
