### ISSUE TITLE
nested exception is com.weibo.api.motan.exception.MotanServiceException: error_message: Please config local server hostname with intranet IP first!, status: 500, error_code: 20004,r=null

### ISSUE THREAD

**Issue by lexburner** [weibocom/motan#232]
window下，启动SpringBootRpcServer，如果没有插网线，并且没有连接无线网，使用ipconfig获取不到本地ip时,会出现这个异常，想问下是在什么地方Motan需要加载本地ip?config local server hostname with intranet IP是如何config?源码没看，原理不太清楚，希望简单回复下

**Comment by rayzhang0603** [comment]
motan查询本机ip的策略是hostname对应的ip --> 根据连接目标端口得到的本地ip --> 轮询网卡
这个异常是没有获取的本机ip或获取的ip不合法。可以通过调试方式看NetUtils.getLocalAddress获取的ip是否正确。
也可以通过在xml配置中添加host="192.168.11.11"这样的方式指定自己的localip
