### ISSUE TITLE
增加spring aop导致service无法注册到consul中

### ISSUE THREAD

**Issue by huanyuxiaoxiao** [weibocom/motan#233]
service上加了@MotanService   同一个包下有多个service 
但是启动server端以后只有一个service注册成功  使用的consul

**Comment by huanyuxiaoxiao** [comment]
找到问题了  因为我又加了 spring-aop
变成了只能注册一个service 这个有办法解决吗

**Comment by huanyuxiaoxiao** [comment]
自己配置了aop以后 

增加了spring配置文件

aop:aspectj-autoproxy/

客户端访问出现以下错误
2016-10-14 17:40:41,065 ERROR error (DefaultLogService.java:79) :ProviderProtectedMessageRouter handler Error: provider not exist serviceKey=fengzheng/com.wangtiansoft.begz.api.service.TestService/1.0 requestId=1548157495279616001 interface=com.wangtiansoft.begz.api.service.TestService method=sayHello(void)

配置了自己的aop  会导致Motan连接异常
注释掉spring文件中的  aop:aspectj-autoproxy/
就能正常访问   怎么破

**Comment by rayzhang0603** [comment]
异常中的serviceKey由group、interfaceName、version这三部分组成，client通过serviceKey查找具体服务，如果是server端添加配置引起的，可以debug ProviderMessageRouter的addProvider方法，看service是否正常注册了

**Comment by huanyuxiaoxiao** [comment]
如果不增加自己定义的aop是正常的没有任何问题

**Comment by huanyuxiaoxiao** [comment]
需求：
想再server的 impl中增加aop功能，对server端的imp参数增加校验、运行时间监控等功能

问题 ：
增加了配置了spring-aop以后，serviceimpl注册到spring工厂的所有接口实现类全部变成了由jdk代理的
，导致jdk的动态代理无法没有注解，从而导致bean的@MotanService注解获取不到，serviceImpl无法被识别成MotanService,客户端调用会报错。 接口未注册。

第一次的issue 的timeout是因为办公环境的网络突然不好，导致之前的10秒超时不够用 (再这吐槽下)，之后调整到60秒就不再出现

解决方案：
使用了原生的apsectj 不用spring-aop即可
