### ISSUE TITLE
Service端配置了protocol。客户端再指定protocal有什么用？

### ISSUE THREAD

**Issue by JianSphere** [weibocom/motan#234]
比如说在客户端我指定了protocol是motan。那么再配置protocol的其他选项是否有用？比如在客户端的protocol设置最大连接数？
另外，服务端可以一个service可以配置多个protocol吗，客户端通过protocol.setName来选择

**Comment by JianSphere** [comment]
应该是客户端只需要指定注册中心的id和协议的类型吧。像那些参数什么的客户端应该不需要配置

**Comment by rayzhang0603** [comment]
client端的protocol必须和server端的一致才能进行调用。protcool中的参数有些是针对server端的，有些是针对client端的，只配置自己需要配置参数即可。例如，protocol可以简单的只配置name＝“motan”
