### ISSUE TITLE
每个接口都需要一个端口号吗？

### ISSUE THREAD

**Issue by Xuchengen** [weibocom/motan#24]
如题

**Comment by sumory** [comment]
@Xuchengen 不需要啊，一般都是按服务划分的，看你的“服务”是怎么定义和包装的了

**Comment by qdaxb** [comment]
不需要，在server配置时export相同的端口就可以了。

**Comment by Xuchengen** [comment]
视乎是不行。

**Comment by qdaxb** [comment]
@Xuchengen 忘了说了，需要在配置service时增加shareChannel="true"

**Comment by qdaxb** [comment]
两周没有回复，暂时关闭。
