### ISSUE TITLE
我使用的zookeeper客户端配置后一直报错，无法启动  （直连可以启动成功）

### ISSUE THREAD

**Issue by mark988** [weibocom/motan#241]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:motan="http://api.weibo.com/schema/motan"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
       http://api.weibo.com/schema/motan http://api.weibo.com/schema/motan.xsd">

```
<motan:registry regProtocol="zookeeper" name="registry" address="127.0.0.1:2181" connectTimeout="2000"/>

<!-- motan协议配置 -->
<motan:protocol default="true" name="motan" haStrategy="failover"
                loadbalance="roundrobin" maxClientConnection="10" minClientConnection="2"/>

<!-- 通用referer基础配置 -->
<motan:basicReferer requestTimeout="200" accessLog="false"
                    retries="2" group="motan-demo-rpc" module="motan-demo-rpc"
                    application="myMotanDemo" protocol="motan" registry="registry"
                    id="motantestClientBasicConfig" throwException="false" check="true"/>

<!-- 具体referer配置。使用方通过beanid使用服务接口类 -->
<motan:referer id="usersSerice"
               interface="com.mxg.base.service.users.UsersServiceI"
               connectTimeout="300" requestTimeout="300" basicReferer="motantestClientBasicConfig"/>
```

</beans>

帮忙看一下，哪里有错误.客户端启动一直报错。报UsersServiceI 没有办法注入。
@autowired 
private   UsersServiceI  usersServiceI;   这一行一直报错。。。

**Comment by rayzhang0603** [comment]
先把demo运行起来，看能不能正常运行。
demo运行成功后，再在demo的基础上修改为自己的代码。
估计跟spring上下文加载有关。你的spring上下文中可能没有加载这份配置。

**Comment by mark988** [comment]
你好，可以加一下你的QQ吗？或者你加我一下也可以（80692072）
