### ISSUE TITLE
  @MotanReferer 	  private UsersServiceI      usersServiceI ;  

### ISSUE THREAD

**Issue by mark988** [weibocom/motan#246]
我在controller 里写的，usersServiceI 一直为NULL 。谁知道怎么解决？

**Comment by mark988** [comment]
@MotanReferer(basicReferer = "motantestClientBasicConfig", group = "testgroup", directUrl = "127.0.0.1:8002")
    UsersServiceI usersSerice;  我写成这样的方式也不行。 这个对象还是NULL 。。

**Comment by rayzhang0603** [comment]
参照https://github.com/weibocom/motan/wiki/zh_quickstart#使用注解方式配置motan ，先把motan－demo模块下的SpringBootRpcServerDemo、SpringBootRpcClientDemo运行起来，然后再在这个demo基础上逐步修改自己的代码试试。

**Comment by mark988** [comment]
好的，我试试运行。

**Comment by Kevinboy2020** [comment]
楼主能跑么？同样的问题

**Comment by rayzhang0603** [comment]
@guochao205 可以先参照代码中的motan－demo模块下的SpringBootRpcServerDemo、SpringBootRpcClientDemo运行起来，然后在demo的基础上逐步修改为自己的代码试试
