### ISSUE TITLE
motan规划

### ISSUE THREAD

**Issue by XuJun0909** [weibocom/motan#25]
motan后续计划是什么？是否考虑集成spring cloud相关组件，比如config server, zuul, 以及进一步完善服务治理...

**Comment by qdaxb** [comment]
我们接下来会做一些文档方面的工作，并提升服务的管理和监控能力，php client支持也在计划中。

我是spring boot的忠实粉丝，spring cloud的特性确实也很吸引人，不过它目前还支撑不了微博内部服务的需求，我们目前在试用和观望中。如果sping cloud未来的发展不错并且足够稳定的话，我觉着支持spring cloud是个不错的方向。

**Comment by i5ting** [comment]
@qdaxb  把协议整理出来，这样大家也可以开发其他client，跨语言是个很大的卖点

https://github.com/weibocom/motan/blob/master/motan-core/src/main/java/com/weibo/api/motan/protocol/rpc/DefaultRpcCodec.java  这个以外还有别的么？
