### ISSUE TITLE
"process thread pool is full, reject"，提交的任务被线程池拒绝了

### ISSUE THREAD

**Issue by catslave** [weibocom/motan#250]
程序之前一直正常运行，使用benchmark压力测试后，程序就无法调用了，查看代码出错原因是在处理请求的时候，线程池报错，抛出了RejectedExecutionException异常。现在正常调用程序也会报这个错误，请问如何解决？

**Comment by rayzhang0603** [comment]
看一下server端的debug日志，查找关键字“process thread pool is full”，类似这样的日志“process thread pool is full, reject, active={} poolSize={} corePoolSize={} maxPoolSize={} taskCount={} requestId={}”中包含线程池的大小、并发运行任务的数量等信息，看看是不是线程池配置等过小了。

可以配置server端 protocol中的maxWorkerThread、 minWorkerThread参数。
例如：

```
<motan:protocol id="demoMotan" default="true" name="motan"
                maxServerConnection="80000" maxContentLength="1048576"
                maxWorkerThread="800" minWorkerThread="20"/>
```

**Comment by catslave** [comment]
@rayzhang0603 修改线程池配置，明白。这里是想问，服务端的线程池是一直被占有着吗？现在只要是不管过多久后再调用服务端，都会抛出“process thread pool is full”。

**Comment by rayzhang0603** [comment]
这个要看业务处理是否一直占用着worker线程。worker线程只是负责调用具体的业务服务，服务处理完就交还线程池
