### ISSUE TITLE
将motan服务打包成jar部署

### ISSUE THREAD

**Issue by estn** [weibocom/motan#254]
请问如何将motan的服务打包成一个jar呢 然后直接使用java -jar运行启动一个服务
比如dubbo和spring boot都提供了maven插件方法

**Comment by JianSphere** [comment]
motan可以直接和spring-boot结合。打成一个可以运行的jar包。

**Comment by mark988** [comment]
怎么搞？

**Comment by estn** [comment]
恩是的 已经看到了  在motan-demo中有~ 谢谢

**Comment by mark988** [comment]
那个地方啊？

**Comment by estn** [comment]
https://github.com/weibocom/motan/blob/master/motan-demo/motan-demo-server/src/main/java/com/weibo/motan/demo/server/SpringBootRpcServerDemo.java  这个地方哈

**Comment by mark988** [comment]
HelloController 这个怎么测试一下？有做出来的吗？

**Comment by estn** [comment]
这个我还在研究哈

**Comment by mark988** [comment]
我觉得放在MVC中 是不是使用的比较多一些啊？这个controller 调用一直没研究出来。
