### ISSUE TITLE
关于motan的一些个人观感

### ISSUE THREAD

**Issue by ling4** [weibocom/motan#258]
因为使用dubbo而关注到motan，也尝试把motan集成到项目中，但目前只作为dubbo的备用方案，没有启用。motan虽然开源了，社区不够活跃，基本还是由开发者在维护；这跟人气固然不无关系，但我觉得关键还是本身开源举动的目的和定位问题。

现在开源的服务治理框架，dubbo已经被证明足够优秀，要尝试一个新框架需要一个理由。一般来讲，我们做产品，在软件选型的时候，满足基本条件的前提下可能考虑的两大因素，一个是稳定性，一个是效率性。

首先是稳定性：motan背后是新浪微博，稳定性应该是有保证的，只是作者也不能否认的是开源版本跟原来版本之间存在一定改动，这些改动的稳定性是有保留的。所以如果要基于稳定性因素选择motan，我会希望了解新浪微博内部正在服役的实际版本情况，比如motan开源对应的版本以及配套序列化的工具采用（hessian/jdk/etc.）、注册中心（zookeeper/consul）等等。这样我的实际部署环境就能尽可能贴合一个经过稳定实践的部署。

其次是效率性：作为有点geek精神的技术人员，性能效率就是我们的诗和远方。在新鲜技术框架层出不穷的今天，相比不再维护的dubbo，motan其实可以承担多一些新技术尝试，去主动集成一些已经过实践的高效率工具，比如thrift、netty4、kryo等等。作为小项目选型，个人认为效率性和先进性是一个更好的理由，去充分感受最新的技术潮流，也不惮于因此牺牲掉一部分稳定性。也因为这样，这些通过社区不断的尝试和改进最终可以演变为稳定性的实践。这也是开源项目从社区开源到从社区汲取营养的一个良性过程。

希望将来有一个很明快的理由去使用motan，而不只是一个备胎：）

cheers!

**Comment by mark988** [comment]
其实，我觉得维护人员能创建一个QQ群，实时回答一些提问。

**Comment by rayzhang0603** [comment]
@ling4 非常感谢您的关注与宝贵意见，motan会不断进行改良，集成进新的功能（包括yar、grpc协议支持、hystrix、zipkin等适配都在开发与试用中），也非常希望广大开源爱好者一起参与共同完善motan。

**Comment by estn** [comment]
最近也一直在研究dubbo、motan、spring cloud。感觉在微服务框架的选择上motan还是面临了不小的挑战 尤其是spring boot的兴起带动spring cloud的发展

**Comment by thermosym** [comment]
Ray, 目前使用motan时需要容错保护，考虑用hystrix 这样的熔断器，你们在开发中的hysttix 集成是以SPI方式？目前感觉方便的似乎可以用spring集成的hysteric 在rpc 调用上再封装一层

**Comment by rayzhang0603** [comment]
可以考虑spi扩展HaStrategy接口或者通过filter方式使用hystrix，这样可以针对某个具体的server做快速失败

**Comment by hifishzlj** [comment]
@rayzhang0603 我尝试着扩展HaStrategy中使用hystrix，现在的难点是如何对MotanBizException处理让其针对性的不触发熔断和fallback
