### ISSUE TITLE
现在的版本能用于生产环境吗？

### ISSUE THREAD

**Issue by siminture** [weibocom/motan#26]
感觉相比dubbo更轻量，这点我很喜欢。正好有新项目要上，
1. 能否在生产环境中使用？
2. 有无交流的QQ群或微信群？
3. 有无事件流的机制？
4. 有无rxjava\event sourcing\lmax disruptor 等扩展或计划？

**Comment by qdaxb** [comment]
1. 目前motan支持了微博的绝大部分底层核心业务，目前看来还是比较稳定的。但是不排除会有一些在开源过程中的修改（例如去除内部依赖等）或者环境不一致造成的问题，建议最好还是测试一下再应用到生产环境。
2. 目前没有qq群，还是以github issue为主。
3. 目前不支持。
4. motan目前对代码几乎没有侵入，而rxjava这类异步框架对代码的侵入性太强。现阶段motan更关注协议互通和服务治理，所有目前把motan和异步框架当做独立的两个框架或许更合适一些。我们也在考虑如何更优雅的引入并发和异步机制，如果有任何想法欢迎回复。

**Comment by lordzoucl** [comment]
补充个问题，开源的motan与微博使用的版本是否存在差异？存在哪些差异？

**Comment by qdaxb** [comment]
@lordzoucl 核心逻辑是一样的，差异主要是微博内部的服务发现使用的是consul或自研的注册中心，还有去掉了一些内部框架的依赖。
