### ISSUE TITLE
序列化方式默认支持hession,目前还有其他选择吗?

### ISSUE THREAD

**Issue by lexburner** [weibocom/motan#260]
主要是项目迁移,之前序列化是使用的fastjson，jackson这些,每个实体返回类没必要实现串行化接口,用了hession的话，是不是得每个实体类都要implements Serializable?

**Comment by andot** [comment]
@lexburner 你可以将 motan 序列化方式配置成 fastjson 或者 hprose，这些不需要定义 implements Serializable。hession 只是默认的方式，不是唯一的方式。

**Comment by lexburner** [comment]
@andot 谢谢,试了下可以成功的。顺便问下,我看了一下dubbo,感觉不如motan轻便,想深入学习一下motan,但是目前并没有开发指南，是不是只能通过阅读源码来学习了?
