### ISSUE TITLE
请问， motan 有没有一个具体的发展规划呢?

### ISSUE THREAD

**Issue by gavinage** [weibocom/motan#263]
比如后期是否要计入trace， 服务编排，服务统计，服务监控等功能？

**Comment by rayzhang0603** [comment]
后续这些功能都会陆续添加，欢迎一起完善motan。
目前下一个版本会先实现grpc协议的支持，下下个版本预计会增加zipkin的支持。motan的跨语言客户端也在开发调试中，敬请关注
