### ISSUE TITLE
请问，如何通过motan传输文件？

### ISSUE THREAD

**Issue by catslave** [weibocom/motan#269]
场景：A.服务发布接口提供文件保存服务，B接收用户的文件上传，将文件传输给A，A进行保存返回保留路径。
方案：尝试过服务端发布FIleItem或者InputStream，客户端传输都会报错，不能转换。请问我这种思路是否正确？

**Comment by rayzhang0603** [comment]
motan支持可序列化的对象传输，建议直接传输byte[]。注意配置requestTimeout和maxContentLength。

**Comment by catslave** [comment]
@rayzhang0603 OK，解决了，谢谢！本来有想过byte来传输，不过考虑到byte文件的大小问题，就先放弃然后尝试inputstream或者其他方式来传输。
