### ISSUE TITLE
如果节点是存活状态，那么没必要走心跳  这段代码可以优化

### ISSUE THREAD

**Issue by mhfc007** [weibocom/motan#272]
// 如果节点是存活状态，那么没必要走心跳
 if (endpoint.isAvailable()) {
     continue;
 }
  HeartbeatFactory factory = entry.getValue();
 endpoint.heartbeat(factory.createRequest());

---------------------------------------------------
节点存活状态,只能说明我  zk 心跳正常   zk客户端端口 和 zk服务端  保持心跳,不被断.

而我motan客户端端口 和 服务端 端口没有心跳  一直没数据,tcp就被断了.   所以我就是要保持心跳才避免被断.     

这样子写就导致了我  zk 连接正常,  服务tcp可能断.   而我这个心跳就是为了防止断. 代码却用一个 一直有心跳的    来决定  另外一条线路是不是做心跳动作.      那配置里头的心跳就没有意义了.而且断的概率和不配置心跳间隔的概率是一样的.

**Comment by rayzhang0603** [comment]
你的理解是错误的。client和server是通过tcp的keepAlive保持长链接的，不是通过这里的心跳。这里的available是指远程server的状态，与zk等注册中心无关。
当一个server在注册中心是working状态，但是client连续请求10次都是失败的情况下，client端会暂时把这个server的available状态置为不可用，这时会触发motan自身的心跳机制，如果心跳发送成功，说明对应的server可以连通，然后恢复为可用状态。

**Comment by rayzhang0603** [comment]
你的理解是错误的。client和server是通过tcp的keepAlive保持长链接的，不是通过这里的心跳。这里的available是指远程server的状态，与zk等注册中心无关。
当一个server在注册中心是working状态，但是client连续请求10次都是失败的情况下，client端会暂时把这个server的available状态置为不可用，这时会触发motan自身的心跳机制，如果心跳发送成功，说明对应的server可以连通，然后恢复为可用状态。

**Comment by rayzhang0603** [comment]
你的理解是错误的。client和server是通过tcp的keepAlive保持长链接的，不是通过这里的心跳。这里的available是指远程server的状态，与zk等注册中心无关。
当一个server在注册中心是working状态，但是client连续请求10次都是失败的情况下，client端会暂时把这个server的available状态置为不可用，这时会触发motan自身的心跳机制，如果心跳发送成功，说明对应的server可以连通，然后恢复为可用状态。

**Comment by rayzhang0603** [comment]
你的理解是错误的。client和server是通过tcp的keepAlive保持长链接的，不是通过这里的心跳。这里的available是指远程server的状态，与zk等注册中心无关。
当一个server在注册中心是working状态，但是client连续请求10次都是失败的情况下，client端会暂时把这个server的available状态置为不可用，这时会触发motan自身的心跳机制，如果心跳发送成功，说明对应的server可以连通，然后恢复为可用状态。

**Comment by rayzhang0603** [comment]
你的理解是错误的。client和server是通过tcp的keepAlive保持长链接的，不是通过这里的心跳。这里的available是指远程server的状态，与zk等注册中心无关。
当一个server在注册中心是working状态，但是client连续请求10次都是失败的情况下，client端会暂时把这个server的available状态置为不可用，这时会触发motan自身的心跳机制，如果心跳发送成功，说明对应的server可以连通，然后恢复为可用状态。

**Comment by rayzhang0603** [comment]
你的理解是错误的。client和server是通过tcp的keepAlive保持长链接的，不是通过这里的心跳。这里的available是指远程server的状态，与zk等注册中心无关。
当一个server在注册中心是working状态，但是client连续请求10次都是失败的情况下，client端会暂时把这个server的available状态置为不可用，这时会触发motan自身的心跳机制，如果心跳发送成功，说明对应的server可以连通，然后恢复为可用状态。

**Comment by rayzhang0603** [comment]
你的理解是错误的。client和server是通过tcp的keepAlive保持长链接的，不是通过这里的心跳。这里的available是指远程server的状态，与zk等注册中心无关。
当一个server在注册中心是working状态，但是client连续请求10次都是失败的情况下，client端会暂时把这个server的available状态置为不可用，这时会触发motan自身的心跳机制，如果心跳发送成功，说明对应的server可以连通，然后恢复为可用状态。

**Comment by mhfc007** [comment]
你好  确实是我没认真看.    available是远程server的chanel的状态.    

我的应用是 在公网上调用  是不是可能keeplive可能保持不了连接?
因为我遇到过这样 调用出错3次,然后心跳成功,然后就好了.    如此隔一段时间重复一次这种过程.

所以我想的是能不能,直接用更上层的业务心跳来保持连接?

**Comment by rayzhang0603** [comment]
可以试试对心跳探测部分进行修改，根据业务或网络情况把心跳周期加大，定期发送心跳，根据心跳成功与否置available状态

**Comment by mhfc007** [comment]
好的  大体明白了    谢谢你了   我目前是自己写个方法几秒调下
