### ISSUE TITLE
AccessStatisticFilter 统计清零问题

### ISSUE THREAD

**Issue by estn** [weibocom/motan#273]
项目中配置AccessStatisticFilter过滤器后，通过日志查询统计功能，但是统计数据会在一定时间内清空~
有两个问题问题：
1.什么时间会调用AccessStatisticItem.reset方法
2.这么设计的原因是什么

**Comment by rayzhang0603** [comment]
log统计信息的时候会调用clearStatistic方法进行重置。统计周期是30秒，统计日志反应的是这30秒内的调用情况。
