### ISSUE TITLE
优雅关机的问题

### ISSUE THREAD

**Issue by estn** [weibocom/motan#275]
现在有个疑惑就是无法优雅的关机，根据官方文档上描述的设置了REGISTRY_HEARTBEAT_SWITCHER为false后就不会处理请求了，但是我模拟的场景依然可以处理请求数据。操作步骤如下

1.在192.168.199.195上启动一个服务并设置REGISTRY_HEARTBEAT_SWITCHER为true，此时在管理后台可以查询到服务列表，并且也处于server状态

2.在192.168.199.103的客户端去调用该服务，可以成功返回

3.设置192.168.199.195上的REGISTRY_HEARTBEAT_SWITCHER为false，此时在管理后台查询服务时，Unavailable Server = 1.说明设置成功

4.在192.168.199.103的客户端去调用该服务依然可以成功返回

预期第四步应该是没有返回才对的，请帮忙解答一下

**Comment by rayzhang0603** [comment]
REGISTRY_HEARTBEAT_SWITCHER为false的作用是不在给注册中心发送心跳，这样注册中心就会把这个server标注为不可用，当client感知后就不会在请求这个server了。
所以这个优雅关机的作用是通知client端不要在进行调用了，但是server实际的处理能力并不会受影响。在没有client调用的情况下，就可以停止服务了。

**Comment by estn** [comment]
哦 OK 我理解了 也是就是设置成了false之后该server就从注册中心下线了.新加入的client端是无法感知的~ 但是由于原来的client端已经在本地缓存了server信息，所以原来的client端还是可以调用成功的

**Comment by rayzhang0603** [comment]
原来的client端也应该会感知，也不会在调用这个server了。
不过有一种情况例外，就是当只有一个server时，如果这个server在注册中心下线了，这时可用server是0，client端有保护机制，会自动忽略server为0的变更

**Comment by estn** [comment]
明白了 那我这边出现的就是上面描述的那种情况~ 我先试试多个server下线其中一个试试 看下线的server还是否处理请求

**Comment by jiankewuming** [comment]
优雅关闭的例子，我测试了一下，用了两个服务端，服务端通过addShutdownHook钩子方式调用MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, false);，客户端不停的调用服务，然后通过kill -15 pid的方式停掉其中一个服务端，但是客户端仍然会去调用这个停掉的服务端。报错信息如下
MotanServiceException: error_message: NettyChannel send request to server Error: url=motan://xxxx:8003/com.xxx.news.core.svr.NewsService local=/xxxxx:52567 requestId=1634125053809394184 interface=com.xxx.news.core.svr.NewsService method=findIdsGreater(long,int), status: 503, error_code: 10001,r=null

**Comment by wangwei418** [comment]
@rayzhang0603  MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, false); 
之后  注册中心通知 到消费者 的周期有参数设置吗？或者默认是多少。目前看持续十几秒客户端还在请求这台server，请问有没有例子 来解决线上服务发布，重启的问题。现在重启过程中会有很多请求打到server重启中的节点，就算通过这种方法 吧server下线，周期很久的话，要等到没有请求再停机 业务场景上也不合适

**Comment by rayzhang0603** [comment]
@jiankewuming 不要使用shutdownhook的方式调用心跳开关，这样调用开关时rpcserver可能已经先停止服务了。

建议的做法是服务本地暴露一个管理端口，准备停机前先通过管理端口关闭心跳开关，这时rpc服务还是可以正常使用的，等client端收到server节点变更通知后，会不再调用server节点，然后server节点在执行停机操作。

**Comment by rayzhang0603** [comment]
@wangwei418 使用的哪种注册中心？如果是zk的话应该很快就会收到通知。如果是consul的话，默认心跳周期是30s，可以通过consul中ConsulConstants.TTL来修改。

server端关闭心跳开关后，client端具体的生效时间可以查看client端的info日志，关键词`ClusterSupport config change notify` ，看看client端什么时间收到的server节点变更通知。

**Comment by wangwei418** [comment]
@rayzhang0603  ，注册中心是consul， ConsulConstants.TTL是在server端启动，还未注册到注册中心 的时候直接对这个变量重新赋值么？比如我在项目启动类第一行 设置  ConsulConstants.TTL=3；这个时候有什么注意的吗？  HEARTBEAT_CIRCLE 取了TTL 的2/3，会不会增加consul的压力

**Comment by wangwei418** [comment]
> @rayzhang0603 ，注册中心是consul， ConsulConstants.TTL是在server端启动，还未注册到注册中心 的时候直接对这个变量重新赋值么？比如我在项目启动类第一行 设置 ConsulConstants.TTL=3；这个时候有什么注意的吗？ HEARTBEAT_CIRCLE 取了TTL 的2/3，会不会增加consul的压力

消费者是否也需要调整 ConsulConstants.TTL 的值？

**Comment by rayzhang0603** [comment]
@wangwei418 要在motan初始化之前修改TTL，SWITCHER_CHECK_CIRCLE也需要重新调整一下。消费方不用修改

**Comment by wangwei418** [comment]
> @wangwei418 要在motan初始化之前修改TTL，SWITCHER_CHECK_CIRCLE也需要重新调整一下。消费方不用修改

SWITCHER_CHECK_CIRCLE = HEARTBEAT_CIRCLE / MAX_SWITCHER_CHECK_TIMES
这个值不是根据ttl 算出来的吗？如果单独调整的话 是怎么调整？ 比如 现在 ConsulConstants.TTL=3，根据公式算出来的 SWITCHER_CHECK_CIRCLE  只有0.2秒了。需要调整到什么值合适？
我现在在启动时候只调整ConsulConstants.TTL=3  发现无法注册到consul了。
有没有完整的例子看下如何解决这个问题。
weibo内部服务重启 应该也会有这些问题吧，有没有好的解决方案

**Comment by rayzhang0603** [comment]
3秒超时的话SWITCHER_CHECK_CIRCLE可以调整到1-2s吧，只要保证在周期内能够checkpass就可以。

一般服务的上线、重启等最好由运维系统来管理，分批次进行，这样就不会对服务变更的感知时间有那么强的要求了
