### ISSUE TITLE
Motan如何抛出自定义异常信息

### ISSUE THREAD

**Issue by estn** [weibocom/motan#277]
Motan如何抛出自定义异常信息
比如在调用注册服务时，会判断用户名是否存在，服务方会返回一个固定的异常代码代表用户名已存在~
怎么把自定义的异常信息加入到motan中，使异常更准确

**Comment by rayzhang0603** [comment]
server端的业务异常motan会序列化并传递到client端的，直接在业务里抛自定义的异常就可以。前提条件是client端有这个异常类，这样才能反序列化

**Comment by estn** [comment]
哦现在可以了 太感谢~  需要client端也有这个异常类！今天尝试的时候客户端没有改异常类，所以一直抛的就是Motan定义的异常信息
