### ISSUE TITLE
motan 不会自动发现服务？一定要通过directUrl来指定吗？

### ISSUE THREAD

**Issue by ZhouXunYou** [weibocom/motan#280]
FYI

**Comment by estn** [comment]
可以通过basicReferer来指定通用的

**Comment by ZhouXunYou** [comment]
@estn 谢谢你的建议，我是在虚拟机上做的实验，将网络改为桥接方式后可正常暴露服务，并且需要将虚拟网卡全部禁用。
虚拟机我用的是virtualbox，原有的网络方式是host-only。
是否是因为该情况导致？

**Comment by rayzhang0603** [comment]
有可能跟获取server ip有关。可以在注册中心看一下server注册的ip地址是什么。
motan获取本机ip的策略是hostname对应的ip --> 根据连接目标端口得到的本地ip --> 轮询网卡
如果motan获取到的ip不是你希望的ip，可以通过设置server的hostname或者在server配置文件中使用host参数配置为正确的ip

**Comment by ZhouXunYou** [comment]
有些不解，IP地址的信息已经在zookeeper上注册了，为什么还要去轮询网卡？

**Comment by rayzhang0603** [comment]
是指server先要获取自己的ip信息，在把这个ip信息注册到注册中心，如果server获取的ip不对（例如你的虚拟机网卡ip），那么注册的ip也就不正确，client就无法访问到这个ip
所以可以确认一下server在注册中心注册的ip是不是可以访问的
