### ISSUE TITLE
怎么样配置不输出serviceStatsLog日志

### ISSUE THREAD

**Issue by nsspw** [weibocom/motan#281]
11:20:18.268 INFO  serviceStatsLog - [motan-statisticCallback]日志太多了，怎样配置不让输出?
我尝试在motan:basicService配置accessLog="false"，也不起作用。
另外一个是检查服务提供者是否存在问题，在Client端的motan:basicReferer中我配置了配置check="false"，但任然会检查。请帮忙解答，谢谢！

**Comment by estn** [comment]
貌似从源代码来看是没法通过设置一个参数来控制的~ 也有可能是自己没有理解透彻哇
但是可以通过配置日志文件特定logger的日志级别来控制比如

```
<logger name="serviceStatsLog" level="WARN"/>
```

**Comment by rayzhang0603** [comment]
如@estn所说的，没有专门的参数控制，可以通过配置logger来控制

**Comment by nsspw** [comment]
谢谢，确实可行
