### ISSUE TITLE
com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support错误

### ISSUE THREAD

**Issue by nsspw** [weibocom/motan#294]
客户端与服务端采用直连的调用方式，在服务端时不时出现：
com.weibo.api.motan.exception.MotanFrameworkException: error_message: NettyDecoder transport header not support, type: 18245, status: 503, error_code: 20001,r=null
请解答，谢谢！

**Comment by rayzhang0603** [comment]
这个异常表示server端收到的不是motan rpc请求。
可以看看是不是有什么其他http调用到rpc的接口了。例如有没有什么服务存活探测之类的

**Comment by nsspw** [comment]
OK，感谢
