### ISSUE TITLE
二个疑问hessian序列化BigDecimal值为0的问题，如果client和server不在同一台机器上第一次连接要长达4秒

### ISSUE THREAD

**Issue by somnus-lin** [weibocom/motan#299]
你好，公司准备用motan做远程的促销服务，在使用的工程中遇到了2个问题，第一个是使用hessian序列化BigDecimal的时候反序列化的时候解析成0了，目前已解决这个问题，像hessian的jar包下添加Deserializer和Serializer补丁，还有一个问题比较疑惑就是client和server不在一台机器上的时候第一次的连接长达4秒，跟踪了一下代码发现NettyClient 中的MessageHandler很久才会被调用，希望能帮忙解答一下这个问题

**Comment by rayzhang0603** [comment]
首次请求时会有类加载等额外开销，可以考虑在首次启动后进行一下简单的预热

**Comment by somnus-lin** [comment]
非常感谢您的解答，现在的处理方法是在接口中添加一个心跳方法，在项目启动的时候去调用一次

**Comment by liuguozhuchina** [comment]
其实motan可以提供一个预热接口

**Comment by rayzhang0603** [comment]
@liuguozhuchina 嗯，后续的版本中会考虑增加心跳预热功能，不过这种方式不能解决业务类的加载，我们也在考虑一下是否有其他更好的方式，欢迎提供好的建议
