### ISSUE TITLE
服务端与客户端查询结果集不一致

### ISSUE THREAD

**Issue by ren-liang** [weibocom/motan#301]
服务端：
1.Dao层使用jdbcTemplate查询数据
(1)Dao接口
public interface IService{
	List<Map<String, Object>> query(int pageSize, int pageNo);
	int count();
}
(2)Dao实现类
@Repository
public class Dao implements IDao{
	@Autowired
    private JdbcTemplate jdbcTemplate;
	//分页查询
	public List<Map<String, Object>> query(int pageSize, int pageNo){
	   ......................
	   return jdbcTemplate.queryForList(sql.toString());
	}
	//查询总行数
	public int count(){
	   ...........
	   return jdbcTemplate.query(sql.toString(),new Object[]{},Integer.class);
	}
}

2.Service层接口实现类调用Dao层进行数据查询
接口：
public interface IService{
	Map<String, Object> query4Client(int pageSize, Integer pageNo);
}
实现类：
@Service
public class Service implements IService{
	public Map<String, Object> query4Client(int pageSize, Integer pageNo){
	   Map<String, Object> rtnMap = new HashMap<String, Object>();
	   List<Map<String, Object>> rows = dao.query(int pageSize, int pageNo);
	   int total = dao.count();
	   rtnMap.put("rows", rows);
	   rtnMap.put("total", total);
	   System.out.println(rtnMap)
	   //输出{total = 2,rows = [{ID = 1,NAME = "测试1"},{ID = 2, NAME = 测试2}]}
	   return map;
	}
}
3.spring xml motan配置
	………………………………
<motan:service interface="IService" ref="service" requestTimeout="200" basicService="serviceBasicConfig"/>

客户端：
1.Spring xml motan配置
	……………………
<motan:referer id="service" interface="IService"  basicReferer="clientBasicConfig" />

2.客户端在Spring MVC控制器中调用远程RPC服务接口
@RestController
public class MyController {
	@Resource(name = "service")
	private IService service;
	@RequestMapping(value = "list", produces = { "application/json;charset=UTF-8" })
	public String list(Integer pageSize, Integer pageNo){
		Map<String,Object> rtnMap = service.query4Client(pageSize,pageNo);
		System.out.println(rtnMap)
		//{total = 2,rows = [{ID = 0,NAME = "测试1"},{ID = 0, NAME = 测试2}]}
	}
}
说明：数据库中ID为主键，类型为NUMBER
问题：两个System.out.println(rtnMap)输出的内容竟然不一样，debug断点调试发现，服务端查询结果与数据库一致是正常的,
到了客户端神奇现象出现了ID全变成0了，而total总行数却始终是正常的，直接崩溃了，找了一整天还是不知道哪里出问题了……

**Comment by ren-liang** [comment]
``

**Comment by rayzhang0603** [comment]
是不是id的类型是BigDecimal？如果是的化，这个是hession2的bug，可以参考
https://github.com/weibocom/motan/issues/127  在hessian的jar包下添加Deserializer和Serializer补丁，或者把row封装成一个对象，指定id为其他类型。（自定义对象需要声明一下implements Serializable）

**Comment by andot** [comment]
或者换个序列化方式就行了

**Comment by ren-liang** [comment]
@rayzhang0603 就是没有进行RowMapper转换成对象直接返回了，具体JdbcTemplate查询返回Map中对于数据的的number类型到底转换成什么类型作为map的value没仔细研究过，最终无奈只能自己进行RowMapper转换成对象解决了。
