### ISSUE TITLE
motan是否有兴趣加入opentracing标准化追踪？

### ISSUE THREAD

**Issue by wu-sheng** [weibocom/motan#304]
你好，我是OpenTracing组织的中国区成员， OpenTracing已经是CNCF级别的追踪标准。

OpenTracing官网：http://opentracing.io

motan作为RPC框架，面向微服务的框架，希望能够积极加入。
我希望通过你们的帮助，通过RP提交相应的支持模块，保证OpenTracing的兼容性。

如果你们感兴趣，请直接回复我。

**Comment by rayzhang0603** [comment]
你好，非常感谢对motan的关注！tracing对分布式服务框架来说十分重要，我们也正在评估为motan增加通用的tracing能力，OpenTracing的vendor-neutral的标准化方式是个很好的选择，我们会进一步详细了解OpenTracing，并在近期开始相关适配工作。

**Comment by wu-sheng** [comment]
好的，对于RPC Framework支持OT标准，是十分容易的。只需要增加拦截器、carrier和tracer的设置即可完成。

Motan作为Dubbo和Dubbox之后失去维护之后，很受欢迎的一款国内RPC框架，我希望将motan作为中国社区的第一个RPC框架，提供给OT的团队，并将Motan项目加入OT的服务支持列表。

如果有任何问题，希望及时联系。
如果需要，你们可以提供拦截点位置，我向Motan提交相关的RP，完成相关的整合代码。

**Comment by estn** [comment]
了解了下OT，感觉文档或者demo之类的比较少，不容易上手~

**Comment by wu-sheng** [comment]
OT作为一个标准，不包含代码，提供的是接口。Java RPC框架需要依赖 opentracing-java-api: http://search.maven.org/#search%7Cga%7C1%7Copentracing-api

大概步骤如下：
1. 在RPC全局，提供一个设置tracer实现类的入口
1. 在客户端发起调用前，通过tracer创建一个span，并使用inject允许tracer的实现者注入上下文
1. 在服务端接收到请求后，调用extract方法，还原上下文（SpanContext），并通过tracer创建一个span。
1. 在客户端和服务端完成后，调用span.finish() 完成

OT标准的关键不是在于实现tracer的真实逻辑，而是为RPC框架为tracer的实现者提供入口点和友好的进行监控。现在包括[sky-walking](https://github.com/wu-sheng/sky-walking)在内的多数java-tracer都是使用字节码技术实现的分布式追踪。（PS:  **sky-walking已经实现追踪motan，环境合作**），实现OT之后，大家可以更方便的进行监控。

当然，现在的OT标准，还不足以无缝的切换tracer的实现，这个具体做法依赖RPC框架的做法，如：RPC框架如果使用Java Service Provider Interface或者配置文件获取tracer接口的实现类，可以完成和tracer的无缝切换。

如果你们需要demo，可以参考部分gRPC的实现：https://github.com/grpc-ecosystem/grpc-opentracing/tree/master/java
我们可以在一个motan/opentracing-1.0的分支上，针对具体的实现进行讨论，在合适的时候进行合并。

中文文档可参考附件，章节：监控框架
[opentracing-io.pdf](https://github.com/weibocom/motan/files/636058/opentracing-io.pdf)

**Comment by andot** [comment]
@wu-sheng 我看了一下，hprose 可以加入了 opentracing 支持，我开了一个项目：https://github.com/hprose/hprose-opentracing ，这个功能通过添加 hprsoe 中间件可以实现，请问怎么联系。

**Comment by wu-sheng** [comment]
@andot ，已经回复你的项目，可以在你的项目中进行讨论，谢谢。

**Comment by rayzhang0603** [comment]
@wu-sheng ，hi，吴晟，我提交了[feature/opentracing](https://github.com/weibocom/motan/tree/feature/opentracing) 分支,请帮忙看看实现方式有没有问题，有哪些地方需要进一步修改。谢谢！

实现方式是通过SPI扩展motan的filter，通过替换OpenTracingContext中的TracerFactory来实现不同tracer配置。配置方式可以通过spring配置（demo中的server端使用的方式）或直接api实现（demo中的client端使用的方式）。demo在test classpath下的com.weibo.api.motan.filter.opentracing.zipkin.demo包下。

另外，如果默认实现方式不满足使用方需求，可以通过继承OpenTracingFilter实现自定义的SPI 扩展来进一步增强功能。

**Comment by wu-sheng** [comment]
@rayzhang0603 , 我将在周一进行相关的review，到时候和你们沟通。十分感谢你们的积极参与。

**Comment by wu-sheng** [comment]
@rayzhang0603 , 我已经review过实现，我觉得目前这样的实现没有发现明显的问题。

不过我建议你们可以持续关注 java-globaltracer，我个人意见，他们提供了更好的API，来实现context传递。

目前的传递方式，不利于业务逻辑新加入span，或者和其他的rpc框架共享这个context。

他们可以继续讨论一些细节，包括java-globaltracer。此分支应该暂时保留独立状态。

**Comment by rayzhang0603** [comment]
@wu-sheng ok，我会持续关注，如果需要作修改请随时告知

**Comment by wu-sheng** [comment]
@rayzhang0603 , 有一个问题要问你一下。sky-walking在支持motan的的分布式调用追踪，现在有一些小的问题？
motan是不是内部有比较特别的classloader的机制？我们在客户端和服务端拦截哪个类，能达到自动动态增加filter的效果。 我的QQ：258239611

**Comment by wu-sheng** [comment]
@rayzhang0603 , 请提供一下，如何注入tracer的实现。

**Comment by wu-sheng** [comment]
是否可以参考你们利用spi读取filter的类似机制，提供通过spi读取tracer实现的能力。用于集成sky-walking的ot tracer实现，避免使用硬代码的方式依赖。

https://github.com/wu-sheng/sky-walking/tree/master/skywalking-application-toolkit/skywalking-toolkit-opentracing

**Comment by wu-sheng** [comment]
可参考hprose实现：https://github.com/hprose/hprose-opentracing/pull/2

**Comment by rayzhang0603** [comment]
已经提交。https://github.com/weibocom/motan/pull/311/commits/630fab810808f27517c73afa303bce3235290502

**Comment by wu-sheng** [comment]
Congrats and done.

**Comment by misselvexu** [comment]
i have already integrate with zipkin on spring boot ! see see ? 
[aux-motan-zipkin](https://github.com/ivetech/aux-motan-zipkin)
