### ISSUE TITLE
服务注册问题

### ISSUE THREAD

**Issue by Satangelsx** [weibocom/motan#310]
请问motan中同一个服务能同时以两种协议导出吗？
比如：
<motan:registry regProtocol="zookeeper" name="test" address="${zk.address}" default="true" connectTimeout="5000"/>
<motan:protocol id="yarProtocol" name="yar" default="true"/>
<motan:protocol id="motanProtocol" name="motan" default="false"/>

<motan:basicService id="yarBasicService" group="A" module="A"    registry="test" export="yarProtocol:8003" shareChannel="true"/>
    <motan:basicService id="motanBasicSerice" group="B" module="B"
                        registry="test" export="motanProtocol:8002" shareChannel="true"/>

 <motan:service interface="com.test.service.ITestService" ref="testService" basicService="yarBasicService" />
 <motan:service interface="com.test.service.ITestService" ref="testService" basicService="motanBasicSerice" />

**Comment by rayzhang0603** [comment]
可以。可以使用export＝“protocolId1:prot1,protocolId2:port2”方式导出多种协议。

    <motan:protocol id="protocolId1" name="motan" .../>
    <motan:protocol id="protocolId2" name="yar" .../>
    <motan:basicService id="serviceBasicConfig" export="protocolId1:8001,protocolId2:8002" .../>
    <motan:service basicService="serviceBasicConfig" .../>
