### ISSUE TITLE
motan不能在一个端口上暴露多个实现吗？

### ISSUE THREAD

**Issue by ZhouXunYou** [weibocom/motan#317]
FYI

**Comment by ZhouXunYou** [comment]
实现多个接口的方式考虑过，但是感觉实现的接口过多也不是一个好的解决办法啊

**Comment by rayzhang0603** [comment]
这里的多个实现指的什么？如果是在同一个端口export多个接口服务，可以参考https://github.com/weibocom/motan/issues/222
如果是一个接口服务，想用不同协议对外提供服务，例如同一个接口即提供motan协议也提供yar协议，可以参考https://github.com/weibocom/motan/issues/310

**Comment by ZhouXunYou** [comment]
非常感谢，还是没有仔细看文档啊。
