### ISSUE TITLE
ServiceConfigBean继承BeanPostProcessor的目的是什么？目前发现同时使用xml和注解时会有bug

### ISSUE THREAD

**Issue by feilaoda** [weibocom/motan#320]
例如服务端使用XML，同时客户端使用注解，则客户端的Referer没有被注入

原因是创建ServiceConfigBean时AnnotationBean还没有被加入到BeanFactory中，除非AnnotationBean继承接口PriorityOrdered或Ordered。
我感觉ServiceConfigBean继承BeanPostProcessor没什么用途？

**Comment by rayzhang0603** [comment]
server端实现BeanPostProcessor是想让servicebean尽早加载，有没有更深层的原因还需要在分析一下。
如果AnnotationBean继承PriorityOrdered或者Ordered可以解决这个问题，我觉得也是不错的选择，因为如果用户自定义的bean实现了BeanPostProcessor，也同样会有无法注入的问题。
