### ISSUE TITLE
开发过程中怎么调试？

### ISSUE THREAD

**Issue by anjingxz** [weibocom/motan#323]
开发过程中，只要打断点就timeout

**Comment by rayzhang0603** [comment]
一般调试可以通过mock方式分别对client端和serve端进行调试，可以参考https://github.com/weibocom/motan/issues/279
如果想要在实际rpc场景中测试server端具体servcie实现的逻辑，可以把client端超时调大一些

**Comment by anjingxz** [comment]
设置了超时时间也不管用（timeout="600000"）
Exception in thread "main" com.weibo.api.motan.exception.MotanServiceException: error_message: NettyResponseFuture request timeout

**Comment by rayzhang0603** [comment]
这条异常信息中应该有个cost,那个值就是实际生效的requestTimeout，你可以在check一下是否requestTimeout没有生效？

**Comment by anjingxz** [comment]
timeout="600000" connectTimeout="600000"
都设置了也不管用，还是抛出timeout

**Comment by anjingxz** [comment]
ok，多谢，设置requestTimeout管用了
