### ISSUE TITLE
关于tcp长连接的问题

### ISSUE THREAD

**Issue by markray** [weibocom/motan#330]
假如一组服务有1000个节点，那client就要保持和维护1000个长连接
如果client要调用n组这样规模的服务，client端是不是太重了 连接数承受的起吗
求破解思路

**Comment by rayzhang0603** [comment]
维持千级别的长链接代价不算大，不会对性能产生影响。
如果不希望同时链接太多serve的话可以通过group进行拆分，或者spi扩展registry，增加逻辑限制返回的server节点数量。
另外，后续版本也会考虑增加类似maxServerNum之类的配置参数，在ClusterSupport中增加限制逻辑实现类似效果。
