### ISSUE TITLE
关于心跳机制

### ISSUE THREAD

**Issue by markray** [weibocom/motan#332]
client watch zookeeper 中所有server节点的根节点，这样server端有节点变化client就会及时得到通知，
为什么还需要心跳机制呢？心跳是维护谁和谁的心跳，要解决 什么问题呢？

**Comment by rayzhang0603** [comment]
心跳机制是为了实现server的预览以及优雅停机。
server跟zk等注册中心建立链接后，服务是unreachable状态，此时并不会真正对外提供服务。可以在unreachable状态下进行预览，确认服务正常后，在打开心跳开关，正式提供服务。服务下线时也是先停止心跳变为unreachable状态，等确认没有client调用后就可以停止服务了。

**Comment by markray** [comment]
那如果服务挂掉，client端是通过 zk 的watch 感知到，还是通过心跳感知到，并处理呢？

**Comment by rayzhang0603** [comment]
如果服务挂掉是通过zk的watch感知到的。其实使用zk作为注册中心时，服务状态变更就是操作了节点状态，也是基于zk的watch来感知的

**Comment by markray** [comment]
通过开关心跳来预览的功能可以理解，但是优雅停机的功能 值得商榷。比如我关闭心跳了，客户端不会马上感知到，那么在下一个心跳周期内，还会有很多请求打过来，
相反，如果是通过zk的watch，直接下线服务后，客户端感知的会更快一些
不知我的理解对不对呢？

**Comment by markray** [comment]
理解了 多谢

**Comment by netboynb** [comment]
可以在机器节点的data中，添加status字段来标示机器的可用性，-1标示为不可用，0标示为ready，1为可用。在实例启动时，该值默认是是0；测试服务实例正常后，在soa管理平台上，将该实例变更为可用状态，这样所有的客户端通过watcher可以感知到可用实例的加入，然后改实例开始对外提供服务。

**Comment by markray** [comment]
@netboynb  这个思路不错哦 简化了逻辑  这样看心跳机制似乎有些多余了

**Comment by rayzhang0603** [comment]
@netboynb 这个思路挺好的。
motan的心跳机制也是为了兼容非长链类型的注册中心，例如使用redis作为注册中心这种情况。

**Comment by fdx321** [comment]
Motan 心跳有两个部分

**Comment by fdx321** [comment]
看了代码，Motan 心跳包有两种
1. Server 给 注册中心的
2. Client 给 Server的
有个问题请教下，当 Server 服务挂掉的时候，注册中心会感知到，然后就会通知各个订阅者(即2中的Client)。为什么Client 还需要发心跳包检测 Server是否OK呢？

**Comment by rayzhang0603** [comment]
@fdx321 client的心跳是为了应对这种情况：server与注册中心网络正常，server在注册中心状态正常。但是client由于网络原因等无法访问到server，此时client会发送心跳测试与server之间是否可以连调，如果不能连调，则client暂时不会给这个server发送请求。当client与server之间网络恢复，通过心跳可以继续访问这个server
client与server间的心跳在正常状态下是不会发送的，只有异常时才进行探测。

**Comment by fdx321** [comment]
有两个问题不是很理解，谁能帮忙解答下，多谢。 @rayzhang0603 @netboynb 

1.  在使用ZK作为注册中心的时候，只是在开关REGISTRY_HEARTBEAT_SWITCHER状态发生变更的时候去通知一下ZK. 在使用Consul做为注册中心的时候，却有一个单独的线程按照一定的频率去CheckPass, 这是为什么呢？
2. 当 Server 服务挂掉的时候，注册中心会感知到，然后就会通知各个订阅者。那为什么Client 还需要发心跳包检测 Server是否OK呢？

**Comment by rayzhang0603** [comment]
@fdx321 
1、zk和consul的心跳机制是不一样的，consul不是类似zk的长链接，所以需要自己定时进行checkpass。
2、client心跳并不是针对server当机这种情况，而是针对server服务正常，但是client和server之间网络异常这种情况

**Comment by fdx321** [comment]
理解了，十分感谢Ray的解答
