### ISSUE TITLE
Service 配置的时候为什么需要指定port，不能集成到protocol中吗？

### ISSUE THREAD

**Issue by darkfireworld** [weibocom/motan#337]
请问一下

1. 为什么Service配置的时候需要指定port？为何不在protocol中指定一下，然后使用同一个协议的service共享一个端口？

2. 如果多个Service使用同一个port是否会出现问题？还是会共享一个端口号？

**Comment by rayzhang0603** [comment]
motan支持不同server使用相同端口提供服务，也支持使用不同端口提供服务。之所以在service配置时需要指定端口，是因为一个service可能会以多个protocol对外提供服务，不同protocol是不支持在同一个端口提供服务的，这样做是为了方便管理。
如果想在同一个端口export多个接口服务，可以参考#222
如果是一个接口服务，想用不同协议对外提供服务，例如同一个接口即提供motan协议也提供yar协议，可以参考#310

**Comment by darkfireworld** [comment]
嗯，谢谢，还有一个问题，想请教一下，motan支持export随机端口号吗？

**Comment by rayzhang0603** [comment]
不支持。一般可以通过spring 的placeholder配置端口号。

**Comment by darkfireworld** [comment]
谢谢你的解答
