### ISSUE TITLE
什么时候会发布1.0.0版本？

### ISSUE THREAD

**Issue by darkfireworld** [weibocom/motan#343]
请问一下，motan什么时候会发布1.0.0版本？然后，之后的RoadMap会怎么规划？

**Comment by rayzhang0603** [comment]
motan的后续规划主要以跨语言调用和增强服务治理功能为主，目前主要在做跨语言方面的调研与开发

**Comment by darkfireworld** [comment]
请问一下，相比较dubbo，motan准备怎么进行扩展使用率？
