### ISSUE TITLE
Provider端自动发起心跳连接问题？

### ISSUE THREAD

**Issue by darkfireworld** [weibocom/motan#344]
为什么Provider端需要手动调用`MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);`来发起注册？

**Comment by rayzhang0603** [comment]
可以参考https://github.com/weibocom/motan/issues/332
这个心跳开关的命名不是特别合理，可以把这个理解为提供服务的开关。
