### ISSUE TITLE
请问一下service和reference中，module参数的含义是什么？

### ISSUE THREAD

**Issue by darkfireworld** [weibocom/motan#345]
请问一下service和reference中，module参数的含义是什么？

**Comment by rayzhang0603** [comment]
module是指服务模块，是比group更细化的服务管理单位，一个group可以有多个module组成，一个module可以提供若干service；实际使用当中用group来划分service已经满足大部分场景的需求，推荐将module和group配置成相同值。

**Comment by darkfireworld** [comment]
嗯，好的~
