### ISSUE TITLE
motan 管理平台和监控平台

### ISSUE THREAD

**Issue by darkfireworld** [weibocom/motan#346]
1. motan的监控平台怎么搭建？（opentracing）
2. motan的管理平台怎么搭建？下载地址在哪里？

**Comment by rayzhang0603** [comment]
1、motan的opentracing扩展已经合并的到主干，下一个release版本将提供该扩展，opentracing的使用可以参考[opentracing扩展](https://github.com/weibocom/motan/tree/master/motan-extension/filter-extension/filter-opentracing) 模块下的demo；tracing系统的搭建需要参考支持[OT](http://opentracing.io)关于不同tracer的使用demo
2、管理后台参见[管理后台](https://github.com/weibocom/motan/wiki/zh_userguide#管理后台)

**Comment by darkfireworld** [comment]
谢谢
