### ISSUE TITLE
请问weibo内部的registry是使用consul还是zookeeper？

### ISSUE THREAD

**Issue by Asuka4J** [weibocom/motan#35]
RT, Thx!

**Comment by qdaxb** [comment]
微博内部大部分服务使用自研的注册中心，一部分服务使用了consul。

**Comment by Asuka4J** [comment]
了解。

另外再问下，如果是跨IDC调用，是多个IDC共享一个registry，还是各自部署registry，然后额外做一个同步？  另外Client也是点对点直连另外IDC的Server吗，还是会走类似于zuul的汇聚？

**Comment by qdaxb** [comment]
注册中心做了跨机房同步，client直连注册中心。
