### ISSUE TITLE
关于zookeeper数据结构的优化？

### ISSUE THREAD

**Issue by Asuka4J** [weibocom/motan#36]
按照motan的zookeeper-registry设计：
将一个服务的所有params作为value放在ip节点里（key=ip+port，value=params），这样一次客户端更新会伴随着N+1次zk交互。在大规模部署下，一个核心服务的发版可能会有大量的zk交互流量。预估重启一台Server，所有Client与zk的交互次数=Client数量 \* 依赖的Server接口数量 \* 当前server数量。比如600台Client_10个接口_40台Server，就是24万次。
当这40台Server完成一轮发布，总共就是24万*40台=960万次。是笔不小的开销。

是否能这样设计：
server在写入params时，对params计算一个hash值，将hash放到key上（ip+port+hash）
当服务变更时，Client的流程：
1.先拉下来servers的所有子节点
2.判断本地缓存是否存在对应的hash，是则直接使用，否则才去取value里的params，并缓存。
这样，除开Client第一次重启，基本可以去掉N+1查询的N。

（dubbo的zk实现是将ip+port+params都作为key，key会很大。这样一次服务变更也会涉及大量冗余数据的传输，也会有问题）

**Comment by Asuka4J** [comment]
补充下，计算hash时需要去掉ip+port的信息，这样同一份服务的hash就是一样的

**Comment by qdaxb** [comment]
这个优化应该可行，后续我们会考虑做这部分优化 ，感谢建议。

**Comment by chinaboard** [comment]
直接将zk暴露到客户端，这种问题本身就不会被降低非常多，自研注册中心或者不使用tcp长连，应该会好一些
