### ISSUE TITLE
protocol连接数最佳实践推荐

### ISSUE THREAD

**Issue by ivancxj** [weibocom/motan#363]
## server端的协议配置有三个连接数配置
```xml
<motan:protocol id="motan-protocol" default="true" name="motan"
                    maxServerConnection="80000" maxContentLength="1048576" maxWorkerThread="800" minWorkerThread="20"/>
```
分别是: 
1. maxServerConnection(server支持的最大连接数,默认:100000)
2. minWorkerThread(最小工作pool线程数, 默认:20)
3. maxWorkerThread(最大工作pool线程数,默认:200)

## client端的协议配置有二个连接数配置
```xml
<motan:protocol default="true" name="motan" haStrategy="failover"
                    loadbalance="localFirst" maxClientConnection="200" minClientConnection="20"/>
```
分别是: 
1. minClientConnection(client最小连接数,默认:2)
2. maxClientConnection(client最大连接数, 默认:10)

请问以上5个参数,你们官方有没推荐配置
比如什么配置应该需要设置多少参数的建议
谢谢!

**Comment by rayzhang0603** [comment]
这个配置跟业务处理模型和并发处理负载有关，不太容易给出通用的推荐值，一般server端如果处理比较耗时的话，需要适当调大minWorkerThread、maxWorkerThread，例如200、800. 
client端一般使用默认配置就可以，如果在client端并发比较高的话，可以适当调大minClientConnection、maxClientConnection，例如10、20

**Comment by ivancxj** [comment]
非常感谢!

**Comment by ivancxj** [comment]
非常感谢!
另外问一下

1. maxServerConnection与WorkerThread是什么区别,如果maxWorkerThread设置800,那么maxServerConnection默认100000什么条件下会触发限制?
2. WorkerThread 是服务端的并发处理限制吗?如果我的应用服务端(比如tomcat/jetty)设置最大连接是200,那么WorkerThread超过200设置是不是没有意义?
3. maxClientConnection设置为20就算大吗,看这数字感觉还是比较小啊😄

**Comment by rayzhang0603** [comment]
1、maxWorkerThread是指处理请求的worker线程数，决定server的并发处理能力；maxServerConnection是server能够接受的最大链接数，与client的总数有关，默认每个client会建立2-10个链接。
2、默认motan监听的rpc端口使用tcp协议进行通信，motan的WorkerThread与服务容器的最大链接数是互相独立的，没有关联。
3、maxClientConnection是指client链接池的最大链接数，可以理解为跟数据库链接池类似，每一个client最大都可能会建立maxClientConnection个链接，如果client总数不是很大，可以在设置大一些。

**Comment by ivancxj** [comment]
好的明白了,谢谢!
我目前只有一个client,那默认值2-10连接确实小了,记得dubbo默认是100
