### ISSUE TITLE
关于线上发布的问题

### ISSUE THREAD

**Issue by lights8080** [weibocom/motan#366]
1、服务暴露中指明了端口（export="demoMotan:8001"），如果一个机器A暴露五个8001-8005，另一台机器B性能不行只想暴露三个8001-8003，这时候改如何部署，修改配置文件的端口？这样不太现实啊

2、升级服务，为了不影响线上使用，使用两个分组来做流量切换，这同样面临相同的服务不同配置问题，配置文件有了状态。

要把配置文件提到项目之外来解决吗？

**Comment by rayzhang0603** [comment]
可以使用spring的placeholder之类的动态配置方式来进行配置

**Comment by lights8080** [comment]
@rayzhang0603 你好，我觉得你说的这个并不能解决我所说的问题，参数外置化并不能动态配置<motan:service>标签。
还有最新版本的流量切换还是有问题 zookeeper

**Comment by rayzhang0603** [comment]
你所说的暴漏服务端口是指不同的server提供不同的服务对吧？可以考虑使用两份配置文件，用类似maven profile这样打包时生成不同的tag，分别部署。或者增加启动参数或启动配置，根据参数加载不同的配置文件。
流量切换是server配置不同的group，一般用来做同机房就近访问和机房故障应急处理，不同的group一般是通过placeholder配置的

**Comment by lights8080** [comment]
OK 感谢支持
