### ISSUE TITLE
使用zookeeper都是内网IP

### ISSUE THREAD

**Issue by limingnihao** [weibocom/motan#367]
我服务器有内外网IP，但是service和client向zookeeper上线都是他们的内网IP，当我想让不在一个内网的机器的client访问service就不行了。请问有什么办法解决。

**Comment by moyi2016** [comment]
motan:basicService   中可以由host来指定服务IP

**Comment by kevin2f** [comment]
或者host文件中 修改 locahost对应的名字 127.0.0.1 改为当前的外网IP
