### ISSUE TITLE
增加运维及监控和管理文档

### ISSUE THREAD

**Issue by luotianwen** [weibocom/motan#37]
运维及监控 和管理什么时候有文档出来 这些没有的话 不敢上生产啊

**Comment by qdaxb** [comment]
目前[wiki](https://github.com/weibocom/motan/wiki/zh_userguide#运维及监控)里有基本启停服务的说明及日志说明，预计本月内会补充一些更加详细的文档。

**Comment by rundos** [comment]
在学习Motan源码过程中，没有看到有类似dubbo MonitorFilter这样监控的逻辑代码，目前开源的代码是是没有包含这块代码还是在其他的地方设置呢？

**Comment by rayzhang0603** [comment]
@rundos 目前开源版本后台提供了服务状态查看功能，没有提供监控信息收集功能。可以通过SPI进行filter扩展。参见https://github.com/weibocom/motan/wiki/zh_developguide#扩展机制
