### ISSUE TITLE
请问，有没有motan的规划

### ISSUE THREAD

**Issue by chenhangbiao** [weibocom/motan#375]
我们目前正在考虑使用，想了解一下。

**Comment by rayzhang0603** [comment]
近期的规划主要是跨语言调用，包括grpc协议支持以及跨语言的client agent实现。中期的规划主要是跨语言的motan server以及统一服务治理。关于服务治理方面有什么好的建议或者意见欢迎反馈，也非常欢迎提各种PR，一起完善motan。
