### ISSUE TITLE
配置冗余建议

### ISSUE THREAD

**Issue by imhuzi** [weibocom/motan#382]
<motan:basicService/>和 <motan:basicReferer/> 中都有 如下配置信息：

```
application		应用信息
module	模块信息
```

那么我一个服务中既有 service 又有 referer ，这两个信息会优先那个呢？
在dubbo中有一个单独的 ApplicationConfig 用于配置公共配置，motan中是否也可以加入呢？这样更清晰些

**Comment by rayzhang0603** [comment]
service的配置和referer的配置是独立的，互相不会影响，两个配置都会分别对service和referer生效

**Comment by imhuzi** [comment]
@rayzhang0603 referer中的 application 和module的配置信息必须 和 service中声明的一样才可以调用是吧

**Comment by rayzhang0603** [comment]
不是的。这两个字段是业务来源标识和业务模块标识，一般server和client是不同的值，例如，一个application 是movie的client方，调用application为user的服务方提供的userservice。

在调用中起作用的是group、protocol、version，这几个必须一致。

**Comment by imhuzi** [comment]
@rayzhang0603 还有个问题请教，我们业务是做垂直拆分的，某个业务单元(同一个项目)对外提供独立的 RESTful api，内部服务的调用通过motan来做，这样，我们一个service既要被web层调用，也需要暴露成motan服务。那么@MotanService 和spring的 @Service的作用是不是一样的，还是说@MotanService  只是暴露 motan的服务，同一个项目要调用这个service还需要通过spring 的@service注解声明，或者通过motan的 injvm协议

**Comment by imhuzi** [comment]
@rayzhang0603 
> 不是的。这两个字段是业务来源标识和业务模块标识，一般server和client是不同的值，例如，一个application 是movie的client方，调用application为user的服务方提供的userservice。
> 在调用中起作用的是group、protocol、version，这几个必须一致。

我们现在的情况就是: application 是movie的client方，也对外提供服务，然而这个时候，referer和 service中的 application、 module 配置应该是一样的

**Comment by rayzhang0603** [comment]
那就配置成一样的就可以了，我的意思是这两个只是各标识，server端和client端是没有关联的

**Comment by imhuzi** [comment]
@rayzhang0603 非常感谢
