### ISSUE TITLE
motan 第一次链接ZK失败后，不会发起再次链接，导致服务注册失效

### ISSUE THREAD

**Issue by darkfireworld** [weibocom/motan#384]
默认情况下，motan链接zk的超时时间为1000ms，这个时间内如果链接不成功，会导致后续的服务注册失败。

版本号：0.2.2

**希望motan使用curator这个zk client，处理链接不成功的问题。**

**Comment by rayzhang0603** [comment]
可以在registry配置中设置connectTimeout,单位是ms

**Comment by darkfireworld** [comment]
嗯，是的
