### ISSUE TITLE
关于ZookeeperRegistry中doRegister的一个疑问

### ISSUE THREAD

**Issue by chenhangbiao** [weibocom/motan#400]
```java
serverLock.lock();
// 防止旧节点未正常注销
 removeNode(url, ZkNodeType.AVAILABLE_SERVER);
removeNode(url, ZkNodeType.UNAVAILABLE_SERVER);
createNode(url, ZkNodeType.UNAVAILABLE_SERVER);
```
最后为什么create的是ZkNodeType.UNAVAILABLE_SERVER？多谢解答！

**Comment by rayzhang0603** [comment]
服务默认的注册状态是unreachable，需要通过操作心跳开关变更服务为working状态。这样做是便于服务上线预览以及服务验证。
推荐的rpc服务上线流程是
1、服务部署
2、预览验证
3、打开心跳开关提供服务（一般与运维系统对接，通过运维系统操作开关）

打开心跳开关方法

    MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, true);

**Comment by chenhangbiao** [comment]
多谢解答。回答很详细，很贴心！
