### ISSUE TITLE
demo项目打包问题（demo_guide.md文档描述不准确，motan-demo-xxx/src/main/bin缺失）

### ISSUE THREAD

**Issue by ghost** [weibocom/motan#41]
你好，  
根据motan-demo/demo_guide.md的说明，在motan-demo下执行 `mvn clean package` 之后，motan-demo-xxx/target/目录中并没有生成xxx.tar.gz的文件
我看了pom.xml之后发现除了需要执行mvn clean package，还需要进入子模块目录执行 `mvn assembly:single`才会生成xxx.tar.gz。
但是tar.gz的压缩包解压之后，没有bin目录，查看motan-demo-server/src/main/assembly/assembly.xml文件，<directory>${project.basedir}/src/main/bin</directory>，貌似代码中并没有这个目录。

**Comment by qdaxb** [comment]
那个文档是之前写的，已废弃，抱歉造成困扰了。

demo可以用ide打开，里面的类可以单独执行。

**Comment by ghost** [comment]
客气。
