### ISSUE TITLE
客户端启动的时候会产生2个连接

### ISSUE THREAD

**Issue by xuhuan** [weibocom/motan#411]
如图，客户端启动的时候会产生2个连接。
![image](https://cloud.githubusercontent.com/assets/1960194/24848269/7f0276cc-1df8-11e7-8419-b7d38ef6f137.png)

IDEA调试的时候也会同时注册2次，导致报错
```
Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 
```

**Comment by rayzhang0603** [comment]
client端建立两个链接是正常的，默认配置client会与server建立2-10个链接。
不过一个client建立多少条链接并不会影响系统启动

**Comment by xuhuan** [comment]
@rayzhang0603 出现的2个连接一个是连到默认端口0的连接，一个是指定的ip和端口。

**Comment by rayzhang0603** [comment]
端口0表示client自身，并不会建立连接。client只会根据注册中心提供的ip和端口建立连接，可以确认一下server在注册中心注册的结果是否有误。

可以参照demo模块，修改server和client的registry配置为你使用的注册中心配置，然后分别运行DemoRpcServer、DemoRpcClient。
如果不使用注册中心可以参照motan_demo_client_direct.xml使用direct直连server端口。

**Comment by xuhuan** [comment]
@rayzhang0603 感谢回复，目前使用没出现之前的问题了，这里先结束掉。
