### ISSUE TITLE
loadbalance LocalFirstLoadBalance

### ISSUE THREAD

**Issue by yxlHuster** [weibocom/motan#42]
1. LocalFirstLoadBalance.searchLocalReferer  
     long local = ipToLong(localhost); 
   放在循环里面是不是有点浪费？
2. LocalFirstLoadBalance.doSelectToHolder
       if (localReferers.isEmpty()) {
           Collections.sort(localReferers, new LowActivePriorityComparator<T>());
           refersHolder.addAll(localReferers);
       }
   也不太对劲

**Comment by qdaxb** [comment]
已修改 #46
