### ISSUE TITLE
mac下没联网时server端起不来

### ISSUE THREAD

**Issue by yanminmin** [weibocom/motan#427]
跟了下代码,因为拿不到本地ip,但又没有用127.0.0.1,所以一直报错,这个能不能优化下,改成找不到本地ip时就用127.0.0.1来代替

**Comment by yanminmin** [comment]
相关的代码:
调用java.net.InetAddress#getLocalHost导致得不到localhost,而是得到MacBook-Pro-2.local,然后得到的网址不正常
断网状态下,无法获取当前ip
com.weibo.api.motan.util.NetUtils#getLocalAddress(java.util.Map<java.lang.String,java.lang.Integer>)
然后导致rpc server直接启动不起来.

**Comment by rayzhang0603** [comment]
在/etc/hosts中把你的hostname配置成127.0.0.1应该就可以了

**Comment by yanminmin** [comment]
@rayzhang0603 配置了的,应该不是这个问题
127.0.0.1       localhost

**Comment by rayzhang0603** [comment]
要配置你设置的hostname才行
127.0.0.1 MacBook-Pro-2.local

**Comment by yanminmin** [comment]
com.weibo.api.motan.util.NetUtils#isValidAddress(java.net.InetAddress)这个方法里限制了,不能是LoopbackAddress

**Comment by yanminmin** [comment]
@rayzhang0603 我照着你的配置了,拿到了127.0.0.1,但是还是报错. InetAddress address = NetUtils.getLocalAddress(regHostPorts);的address为空.
另外不同的电脑都需要配置/etc/host的话,不太方便开发者.
当然,生产环境肯定不会遇到这个问题,主要是coder会遇到这种情况.

**Comment by rayzhang0603** [comment]
可以试试不配置成127.0.0.1，配成其他内网ip试试，例如10段或172段的任意ip。

**Comment by yanminmin** [comment]
@rayzhang0603 你是微博内部的员工吗?

**Comment by rayzhang0603** [comment]
@yanminmin 是的

**Comment by yanminmin** [comment]
后面会考虑这块的逻辑吗?

**Comment by rayzhang0603** [comment]
这种情况只发生在配置了hostname，但是又没有链接网络的情况。去掉hostname、主机联网，配置hosts
都可以解决。我认为对于这样的个例场景，有解决办法即可，没有必要在框架中增加不必要的逻辑。
