### ISSUE TITLE
关于maxWorkerThread和minWorkerThread的解释

### ISSUE THREAD

**Issue by pop-lee** [weibocom/motan#439]
在文档中，这两个参数描述服务器端的工作线程数，那么这个是针对于提供的每一个method的线程数，还是针对于对外提供的所有method的线程数之和呢？？

client端的配置文档中描述是针对于每一个客户端的线程数，那么同样的问题，是每一个ref的，还是所有ref的综合呢？

**Comment by rayzhang0603** [comment]
maxWorkerThread和minWorkerThread只对server 端生效，是针对server的端口维度，一个端口上提供的所有服务共用worker线程。
maxClientConnection和 minClientConnection对client端生效，表示对一个server节点可以建立的最大和最小链接数量，如果同一个service有多个server，则client会对每个server至少建立minClientConnection个链接。

**Comment by pop-lee** [comment]
3Q
