### ISSUE TITLE
为什么request_counter会大于设置的maxClientConnection

### ISSUE THREAD

**Issue by pop-lee** [weibocom/motan#441]
不知道是否理解的有问题，就是maxClientConnection设置了之后，客户端的并发请求应该是会受到这个得限制吧？可是会报如下类似的错误
com.weibo.api.motan.exception.MotanServiceException: error_message: ThreadProtectedRequestRouter reject request: request_counter=215 total_counter=215 max_thread=270, status: 503, error_code: 10002,r=null
这个判断条件我在源码里看到了，request_counter不能大于max_thread的1/2，这个request_counter是根据method计算出来的呀
请求方法默认应该是同步，那么maxClientConnection的限制并没有起作用呢
我的测试是本机搭建的环境，只提供了一个消费者和一个生产者

**Comment by rayzhang0603** [comment]
maxClientConnection不是限制并发调用的。maxClientConnection是限制client与server之间的链接数的，异步请求下一个链接就会并发很多请求。
这个报错表示server端有215个worker线程被占用，可以确认一下是否server业务处理耗时较高；如果确实是并发比较高可以调高worker数量
一般服务推荐maxWorkerThread=800，minWorkerThread=200
