### ISSUE TITLE
性能测试客户端配置文件中有错误

### ISSUE THREAD

**Issue by zhcosin** [weibocom/motan#460]
性能测试 motan-benchmark-client 的配置文件 benchmark.properties 中，后面几个 classname 的路径名与 package 路径有出入:
benchmark.properties: com.weibo.motan.test.benchmark.TestStringRunnable
真实路径: com.weibo.motan.benchmark.TestStringRunnable
即相差一个 test.

**Comment by rayzhang0603** [comment]
感谢反馈，应该是测试之后调整过，我们修改一下
