### ISSUE TITLE
机器挂载VPN的话,motan获取的是vpn网卡对应的ip地址,导致调用失败

### ISSUE THREAD

**Issue by mrdear** [weibocom/motan#463]
对于本机调试,motan总是获取的是vpn的地址
对于dubbo可以通过指定host来配置  
  <dubbo:protocol name="dubbo" host="192.168.137.78" port="20881" />

对于motan该怎么配置呢?

![image](https://user-images.githubusercontent.com/13889883/27124448-bfeae24c-5123-11e7-93ae-152fa80bea8c.png)

**Comment by rayzhang0603** [comment]
可以在basicService或者service配置中，配置host属性

    <motan:service host="xx.xx.xx.xx" .... />

或者设置主机的hostname也可以

**Comment by mrdear** [comment]
thks
