### ISSUE TITLE
Failed to retry subscribe, retry later, failedSubscribed.size=2, cause=null

### ISSUE THREAD

**Issue by lgoodbook** [weibocom/motan#470]
时不时来个这，受不了
![image](https://user-images.githubusercontent.com/15835602/27573695-ac52e76c-5b45-11e7-9dba-68ebef328968.png)

**Comment by rayzhang0603** [comment]
看这个异常client端应该有两个service没有订阅成功，按说应该有两个service不能使用，可以确认一下订阅失败的原因，看是不是注册中心中没有对应的server。
不过这个异常信息不太友好，后续我们会优化一下异常信息。

**Comment by lgoodbook** [comment]
确实是没有订阅成功，已解决
