### ISSUE TITLE
motan的consistent hash策略问题

### ISSUE THREAD

**Issue by ghostPM** [weibocom/motan#473]
从motan client的使用方式来看，属于直接注入rpc接口完成调用，所有cluster的节点选择高可用细节等都隐藏在接口的代理层实现后面，也支持consistent hash策略。
但在实际使用中，consistent hash的hash key可能是用户在运行时去指定的（例如我要根据username去进行hash），使用直接注入rpc接口的方式似乎无法解决动态hash key的问题。
不知道motan在设计时是否有考虑过支持上述类似场景？或者是否有更好的解决方案？

**Comment by rayzhang0603** [comment]
目前的一致性hash比较简单，也不是严格意义上的一致性hash，可以看作是粘滞调用。
如果需要实现定制的hash策略，可以考虑参考com.weibo.api.motan.cluster.loadbalance包下的LB实现，自定义实现一个SPI扩展。
关于spi扩展请参考[spi扩展](https://github.com/weibocom/motan/wiki/zh_developguide#编写一个motan扩展)
