### ISSUE TITLE
一个项目既作为服务端提供服务又作为客户端调用他人服务, 可以实现么?

### ISSUE THREAD

**Issue by chilejiang1024** [weibocom/motan#477]
如题, 一个项目使用motan提供服务给他人使用, 同时项目中又需要调用他人提供的motan服务. 现在可以实现么, 在一个xml中可以同时注册服务端和客户端么?

我把它们都写在一个xml中, 先写的服务端,后写的客户端, 调用的时候客户端总是向上一个注册的服务端发送请求, 然后我客户端注册的是他人的服务.

**Comment by rayzhang0603** [comment]
可以同时配置，是否配置在一个xml中不会有影响。你说的问题很可能是配置的不正确导致的，client发送请求是按照从注册中心订阅的server节点进行调用的，与你本地的配置顺序无关，可以根据info日志确认一下client发现回来的server节点是哪些。

**Comment by chilejiang1024** [comment]
已经搞定了, 可能是服务端配置有问题, 今天来部署了一下发现可以使用了. 我是写在了2个配置文件中, 因为他人服务还没有正式上线.
