### ISSUE TITLE
motan如何随tomcat关闭而停止

### ISSUE THREAD

**Issue by jm-jason** [weibocom/motan#479]
如题，项目在研究motan，但是遇到一个问题，就是tomcat关闭时候，motan午饭关闭，需要手动再次关闭。不知道是否提供了 接口，来使用代码关闭？

**Comment by rayzhang0603** [comment]
motan0.3.1版本提供了com.weibo.api.motan.closable.ShutDownHookListener，在web.xml中添加ShutDownHookListener即可

**Comment by jm-jason** [comment]
@rayzhang0603  谢谢！
