### ISSUE TITLE
看springsuppot的时候，parseMethods这里看不懂

### ISSUE THREAD

**Issue by dysonbird** [weibocom/motan#48]
在配置的md文件看到motan:method/这个标签,但是demo中的配置文件没有见到用motan:method/这个标签的,RefererConfig中的methods是怎么初始化的？能简单解答一下吗？

**Comment by syndory** [comment]
@dysonbird 请参考 #41 #45

**Comment by dysonbird** [comment]
@syndory 难道我问题问得不够清晰，你提供给我的完全对我的疑问没有作用的感觉，我是想了解清楚motan:referer/这个标签的初始化，MotanBeanDefinitionParser这个类中，看到parseMethods这个方法的时候卡住了，因为demo给出的配置文件都没有配置motan:method/这个属性，不知道在代码的哪里会初始化method。

**Comment by ghost** [comment]
@dysonbird 抱歉，确实没太看明白。

**Comment by sunnights** [comment]
method用于控制某个函数的行为，不配置表示不限制具体函数行为，motan-demo里没有对method进行配置
[client配置列表](https://github.com/weibocom/motan/blob/master/docs/wiki/zh_configuration.md)里面有

**Comment by dysonbird** [comment]
嗯嗯，可能我理解错了，我以为method是Interface中的method

**Comment by dysonbird** [comment]
@sunnights 我再看了一遍，发现配置中的method应该就是Interface中的method来的，如果没配置RefererConfig类中的methods是不是就是null了？

**Comment by sunnights** [comment]
@dysonbird 是的，RefererConfig中会检查method是否在接口中存在，你可以在demo的motan:referer配置下加一条<motan:method name="hello"/>看看效果
另外，method也可以在motan:service下配置

**Comment by qdaxb** [comment]
@sunnights 后续demo里可以加上这个配置。
