### ISSUE TITLE
打包时：zookeeper的RegistryFactory 被覆盖问题

### ISSUE THREAD

**Issue by jm-jason** [weibocom/motan#486]
由于Motan META-INF.services里的RegistryFactory 命名相同，导致在manve编译时Zookeeper的接口配置文件被覆盖，所以在运行时报错，找不到zookeeper协议。
请问一下，在打包时候，需要如何处理，才能正确打包？

**Comment by rayzhang0603** [comment]
如果是打成一个fat jar的话，META-INF/services下的motan相关扩展都应该使用追加模式打包，可以参考下面配置

         <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>2.3</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>                                
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.schemas</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/spring.handlers</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.weibo.api.motan.registry.Registry</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.weibo.api.motan.registry.RegistryFactory</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.weibo.api.motan.rpc.Protocol</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.weibo.api.motan.cluster.LoadBalance</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.weibo.api.motan.cluster.Cluster</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.weibo.api.motan.codec.Codec</resource>
                                </transformer>
                                <transformer
                                        implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                    <resource>META-INF/services/com.weibo.api.motan.codec.Serialization</resource>
                                </transformer>
                            </transformers>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

**Comment by jm-jason** [comment]
@rayzhang0603  这个我尝试了，但是遇到一个问题，解决不来。 我这个项目是尝试多模块开发，该模块依赖父节点，报 拒绝访问的异常。
结构：
   basicMods  parent
       core   基础模块

      testRPC 继承 core 。
异常如下： 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-shade-plugin:2.3:shade (default) on project testrpc: Error creating shaded jar: C:\Users\JasonMao\Documents\WorkSpace\basicMods\core\target\classes (拒绝访问。)

**Comment by jm-jason** [comment]
@rayzhang0603  已经解决，父节点 packing 配置成了 jar导致的错误
