### ISSUE TITLE
motan的服务接口参数类型可以是自定义的吗？

### ISSUE THREAD

**Issue by kran** [weibocom/motan#491]
文档里没有看到例子。
还有YarServer演示里：

    public List<Object> testList(List<Object> list) {
        System.out.println("in testlist");
        List<Object> retlist = new ArrayList<Object>(list);
        Collections.reverse(retlist);
        return retlist;
    }

    public Map<String, Object> testMap(Map<String, Object> map) {
        System.out.println("in testmap");
        Map<String, Object> retmap = new HashMap<String, Object>(map);
        retmap.put("size", map.size());
        return retmap;
    }

这样的参数在yar（php）的客户端如何传递？

**Comment by rayzhang0603** [comment]
可以参考下面的代码

    <?php
        $client = new Yar_Client("http://****:8003/openapi/yarserver/test");
        /* the following setopt is optinal */
        $client->SetOpt(YAR_OPT_CONNECT_TIMEOUT, 2000);
        #$client->SetOpt(YAR_OPT_TIMEOUT, 2000);
        #$client->SetOpt(YAR_OPT_PACKAGER, "JSON");
        #$client->SetOpt(YAR_OPT_PACKAGER, "PHP");
        $client->SetOpt(YAR_OPT_PACKAGER, "MSGPACK");
        /* call remote service */
        $result = $client->hello("motan yar");
        echo $result."\n";
        $result = $client->testString("test");
        echo $result."\n";
        $result = $client->testInt(1234);
        echo $result."\n";
        $result = $client->testInteger(5678);
        echo $result."\n";
        $result = $client->testVoid();
        echo $result."\n";
        $result = $client->testArgVoid();
        echo $result."\n";
        $result = $client->testBoolean(true);
        echo $result."\n";
        $result = $client->testArgVoid();
        echo $result."\n";
        $result = $client->testFloat(123.5678);
        echo $result."\n";
        $result = $client->testDouble(789.7982734);
        echo $result."\n";
        $result = $client->testList(array("kjier", 123,"ji3", 789.8));
        foreach($result as $key=>$value)
        echo $key."=>".$value."\n";
        $result = $client->testMap(array("aaa"=>"kjier", "bbb"=>123,"ji3", "ddd"=>789.8));
        foreach($result as $key=>$value)
        echo $key."=>".$value."\n";
    ?>

**Comment by kran** [comment]
@rayzhang0603 多谢
对于复合类型(自定义的类),在java和php端调用,是否可以实现?

**Comment by rayzhang0603** [comment]
暂不支持复合类型。

**Comment by kran** [comment]
谢谢解惑 @rayzhang0603
