### ISSUE TITLE
如何通过服务名称和服务的某一个方法名调用远程集群上已经注册的服务来获取方法执行的结果？

### ISSUE THREAD

**Issue by lijhua** [weibocom/motan#497]
问题这样描述，比如：
  服务的全限定名：com.weibo.motan.demo.service.MotanDemoService
  服务有一个方法 ：hello(){ .........}
  这个服务已经成功注册到zookeeper集群: 192.168.56.10:2181,192.168.56.11:2181,192.168.56.12:2181

 我在本地只知道上面这3个字符串信息，怎样通过远程调用来获取到这个hello方法的执行结果呢？

 怎样实现？麻烦给个方案，谢谢！

**Comment by rayzhang0603** [comment]
是不能使用motan client进行调用吗？
一般要调用server必须要指定group，按group调用。如果只有服务名和方法的话只能通过zk的路径查找所有group，然后找到服务名及提供服务的节点。zk中的路径为/motan/${group_name}/${service_name}/server/${server_node}
最后，建议使用motan client进行服务发现与调用，不建议直接查询zk信息

**Comment by lijhua** [comment]
我这边想实现的是一个服务管理中心，所有的服务列表及服务的集群状态在这里都能看到，然后接口测试人员可以根据开发人员提供的服务描述文档来验证某个接口。
group可以提供，这个没问题，那么按照你的要求server,group,method都知道了的情况下，怎么才能调用集群中的节点来拿到这个方法的执行结果呢？

**Comment by rayzhang0603** [comment]
调用的话需要进行对象序列化等，最好能直接通过api方式创建client并调用。
如果管理系统无法拿到java类的话，只能直接创建com.weibo.api.motan.transport.netty.NettyClient，然后自己组装com.weibo.api.motan.rpc.DefaultRequest，通过NettyClient的request方法进行调用。

**Comment by lijhua** [comment]
好的，已经按照这个思路在尝试了，谢谢！
