### ISSUE TITLE
j.u.c 并发包下线程安全类上加synchronized对findbugs不友好

### ISSUE THREAD

**Issue by XuJun0909** [weibocom/motan#50]
如：ExtensionLoader getSingletonInstance方法里 synchronized (singletonInstances)：
findbugs提示This method performs synchronization an object that is an instance of a class from the java.util.concurrent package (or its subclasses). Instances of these classes have their own concurrency control mechanisms that are orthogonal to the synchronization provided by the Java keyword synchronized. For example, synchronizing on an AtomicBoolean will not prevent other threads from modifying the AtomicBoolean.
虽然没什么问题，建议把synchronized 块重构为synchronized 方法。

**Comment by qdaxb** [comment]
synchronized块改为synchronized方法我认为没有必要，把synchronized对象改为一个new Object或许更合适一些。

后续我们会找时间修改这个问题，也可以直接提交PR。
