### ISSUE TITLE
ACL问题

### ISSUE THREAD

**Issue by appydm** [weibocom/motan#500]
现在motan注册consul，还不能使用ACL模式吗？如果扩展，怎么做？

**Comment by rayzhang0603** [comment]
可以考虑在com.weibo.api.motan.config.RegistryConfig、motan-core模块中的resources/META-INF/motan.xsd的abstractRegistryConfig中增加token字段，然后在com.weibo.api.motan.registry.consul.ConsulRegistry的构造函数中从url获取到token的值，按consul acl要求进行调用。
欢迎PR:)

**Comment by appydm** [comment]
我已经按照这种思路做了!谢谢
