### ISSUE TITLE
motan默认日志框架修改问题

### ISSUE THREAD

**Issue by sundylgz** [weibocom/motan#503]
motan目前使用的是log4j日志框架，我们的项目用logback，在更改过程用遇到问题，主要是motan-registry-zookeeper 模块中引用了 
             <dependency>
			<groupId>com.101tec</groupId>
			<artifactId>zkclient</artifactId>
			<version>0.3</version>
		</dependency>
该版本的zkclient 里面默认是写死了log4j，导致logback日志配置不成功，希望官方升级到最新版本
          <dependency>
                <groupId>com.101tec</groupId>
                <artifactId>zkclient</artifactId>
                <version>0.10</version>
            </dependency>
就可以解决完全依赖于log4j问题。

**Comment by rayzhang0603** [comment]
感谢反馈。后续版本会对依赖的jar包进行升级

**Comment by shiwolang** [comment]
https://logback.qos.ch/reasonsToSwitch.html

**Comment by ContyChen** [comment]
暂时可以使用log4j-over-slf4j 桥接到slf4j，解决logback配置的问题
