### ISSUE TITLE
URL类getBooleanParameter里如果value为空返回null

### ISSUE THREAD

**Issue by XuJun0909** [weibocom/motan#51]
考虑到返回类型为Boolean，修改为下面代码更好：
if (value == null) {
            return Boolean.FALSE ;
        }

**Comment by qdaxb** [comment]
感谢建议，我们会尽快修改这个问题。

**Comment by rayzhang0603** [comment]
value为null时，方法返回null是为了能够区分没有配置参数和配置参数值为false的情况，可以根据返回值做不同处理。如果需要参数为空返回默认值时，可以使用getBooleanParameter（String name ，boolean defaultValue)方法
