### ISSUE TITLE
异步调用返回的结果貌似混淆了

### ISSUE THREAD

**Issue by rayeaster** [weibocom/motan#515]
代码如下：
future = service.asyncCall(param);
listener = new FutureListener({...});
future.addListener(listener);

发现经常出现不同param的调用结果出现在同一个回调返回中，比如param1和param2分别对应的结果都出现在同一次operationComplete中(比如param1对应的那次)，那么相应的就是param2对应的operationComplete拿不到任何数据

@rayzhang0603

**Comment by rayzhang0603** [comment]
不同的请求用的同一个listener吗？如果是用的同一个listener可以看看是不是你自定义的listener处理逻辑的问题。

如果不是同一个listener是不会出现混淆的情况，不可能不同的listener add到同一个future上。
建议可以先直接用future获取结果，确认future自身结果是否正确，然后在确认逐步排查出现问题的地方

**Comment by hongpxiaozhu** [comment]
ResponseFuture responseFuture = rpcServiceAsync.executeAsync(param);
 FutureListener listener = new FutureListener() {
                @Override
                public void operationComplete(Future future) throws Exception {
                RpcResult rpcResult = (RpcResult) future.getValue();
                ...................
};
responseFuture.addListener(listener);

每个listener都是new出来的,应该不是您所说的同一个listener,但是就是出现了混淆。

rpcServiceAsync这个是注入到spring的，单例，是否会有影响。

@rayzhang0603

**Comment by rayeaster** [comment]
【直接用future获取结果】是同步block的吗

**Comment by rayzhang0603** [comment]
@hongpxiaozhu motan的refer都是单例使用。原来的同步方式底层一直就是异步调用，只不过是在返回时阻塞拿到结果而已。异步方式是直接把future返回了。

**Comment by rayzhang0603** [comment]
@rayeaster 直接使用future就可以发多个请求同步发送，然后在获取多个结果是在阻塞获取。同步调用是取得future后获取结果，异步调用是直接返回future，其实两种类型底层是相同的实现

**Comment by rayeaster** [comment]
【如果不是同一个listener是不会出现混淆的情况，不可能不同的listener add到同一个future上。】这个算bug吗？还是说上面的代码顺序错了？应该先new listener，然后再call得到future，然后再add listener到future？

**Comment by rayzhang0603** [comment]
你可以debug一下，或者输出一下对象id，future是一次请求一个对象，如果不重复调用这个future的addlistener方法，是不可能把其他listener添加上去的。
是不是listener在处理回调的逻辑有线程安全的问题？

**Comment by rayzhang0603** [comment]
建议使用一个简单listener逻辑，operationComplete中只做一下requestid和结果的输出，看是否有问题

**Comment by rayzhang0603** [comment]
另外，你说的`比如param1和param2分别对应的结果都出现在同一次operationComplete中` ，一个future只能有一个结果，所以在一次调用operationComplete中也只能有一getvalue，你的多个结果是从哪里获取的呢

**Comment by hongpxiaozhu** [comment]
ApplicationContext ctx = new ClassPathXmlApplicationContext("classpath:rpc/motan_client.xml");
		final RpcServiceAsync rpcServiceAsync = (RpcServiceAsync) ctx.getBean("rpcServiceAsync");
		
		final ActionParam param = new ActionParam();
		param.setMobile("13951556064");
		param.setDealcode("1234567890");
		param.setBuyerId(277474L);
		ResponseFuture responseFuture = rpcServiceAsync.executeRulesAsync(param);
		
		final ActionParam param2 = new ActionParam();
		param2.setMobile("13951556065");
		param2.setDealcode("1234567890");
		param2.setBuyerId(277474L);
		rpcServiceAsync.executeRulesAsync(param2);
		
		SetResult setResult = (SetResult) responseFuture.getValue();
		for (Object obj : setResult.getResults()) {
            Result result;
           if (obj instanceof Map) {
            	Map tmpMap = (Map) obj;
                System.out.println("rpc返回参数是Map：" + ((String)tmpMap.get("message")));

            } else {
                ruleResult = (RuleResult) obj;
                System.out.println("rpc返回参数是Result：" + result.getMessage());
            }
        }


@rayzhang0603 
刚才做了一个测试，重现了这个问题，两个不同的请求参数，当调用param后，立刻调用了param2，responseFuture 是param时获得的，但是结果返回给我了两个参数的所有结果，而没有隔离。

结果如下：
rpc返回参数是Result：13951556064===1234567890
rpc返回参数是Result：13951556064===1234567890
rpc返回参数是Result：13951556065===1234567890
rpc返回参数是Result：13951556065===1234567890
rpc返回参数是Result：13951556065===1234567890
rpc返回参数是Result：13951556064===1234567890

以上就是我们所碰到的现象，请能告知原因。

@rayzhang0603

**Comment by rayzhang0603** [comment]
你第二次请求用的还是第一次的response。。。。
responseFuture是每个请求一个不能复用。。
改成这样使用：

    ResponseFuture future1 = rpcServiceAsync.executeRulesAsync(param1);
    ResponseFuture future2 = rpcServiceAsync.executeRulesAsync(param2);
    System.out.println(future1.getValue() + ", " + future2.getValue());

异步调用方式可以参考[异步调用](https://github.com/weibocom/motan/wiki/zh_quickstart#异步调用)

**Comment by rayeaster** [comment]
[你第二次请求用的还是第一次的response]
然而第二次其实根本没有获取response，也没有获取value，只是做了一次调用

rpcServiceAsync.executeRulesAsync(param2);
SetResult setResult = (SetResult) responseFuture.getValue();

**Comment by rayzhang0603** [comment]
那就是说，motan在一次请求收到的SetResult对象中包括两次请求的内容，这应该是server 端处理的问题了。
motan只负责传递对象，不会对对象的值进行修改和组装的。
你可以在server端方法返回时输出一下server端的内容如果你的返回对象是SetResult看是不是server端端并发问题。

**Comment by rayeaster** [comment]
好的，谢谢，我们再验证一下
