### ISSUE TITLE
motan管理中心问题

### ISSUE THREAD

**Issue by appydm** [weibocom/motan#518]
我使用的consul，我的服务能注册上，能看见IP。但客户端连接上后，不能看见IP。我查阅了源代码，看见Client设置为null，那怎样能判断客户端的IP是否连接成功啊！源代码要怎么进行修改？

ConsulRegistryService.java

List<JSONObject> unavailableServer = getNodes(dcGroup, dcServiceName, "CRITICAL");
service.put("unavailableServer", unavailableServer);
service.put("client", null);

**Comment by appydm** [comment]
Zookeeper 的 client能获取到，consul不能获取到吗？

**Comment by rayzhang0603** [comment]
@Figthing consul没有zk的临时节点功能，所以client断开后不能自动进行清理，而且一般client的数量远多于server，所以consul注册中心client在订阅时并没有同时注册client相关信息。

client和consul使用的http调用，一般不是长链接，所以判断client是否链接上consul意义不是很大，如果想判断client是否能正常订阅可以通过设置referer的check=true参数，订阅失败获取不到节点时系统会启动失败。

如果确实需要consul中保存这个信息，可以扩展ConsulRegistry，在subscribeService、unsubscribeService时注册、注销一下client节点。

**Comment by appydm** [comment]
好的，谢谢
