### ISSUE TITLE
zipkin整合motan问题

### ISSUE THREAD

**Issue by sundylgz** [weibocom/motan#521]
用zipkin和motan整合，发现找不到依赖关系，里面的报表数据层次逻辑不对。我是这样做的A服务器调用B服务器，客户端C调用A服务，将这些数据上报zipkin，应该可以看到依赖关系，但是没有。

**Comment by rayzhang0603** [comment]
`里面的报表数据层次逻辑不对`
可以提供一下具体的信息吗，是统一的traceid不一致？

**Comment by sundylgz** [comment]
官方测试代码中可以重现这个问题，你可以添加一个HelloService2  HelloService调用HelloService2就有这个问题，将tracer信息上报到zipkin上就可以看到效果了。
