### ISSUE TITLE
Server side configuration

### ISSUE THREAD

**Issue by wilddylan** [weibocom/motan#528]
Can you provide `motan_server.xml` and `motan_client.xml` demo used in production env ???
Can you provide `motan_server.xml` and `motan_client.xml` demo used in distributed production env ???

Really really really need it! i'm new to this project.

------  Edit ------

And can you provide an image for distributed production structure? same as:

```
|----------|
|  Server 1 | (What's this server.xml)  ---------------> |----------|
|----------| 
                                                         |Clients1..n| (What's this client.xml)
|----------|
|  Server 2 | (What's this server.xml)  ---------------> |----------|
|----------|
```

And can you provide more information with load balance configuration and structure?

**Comment by rayzhang0603** [comment]
线上的配置根据业务类型配置也不相同，可以参考[微博新兵训练营](https://weibo.com/ttarticle/p/show?id=2309404038032062872510)中的相关内容，下面贴一些主要的参数说明。

## **registry配置：**


1）、regProtocol

zookeeper：使用zookeeper注册中心

consul：使用consul作为注册中心

local：本地注册中心，用于测试或不需要注册到远程注册中心的场景

direct：直连方式的伪注册中心，client端配置direct注册中心用于直连服务地址。

2）、check   ： _true_(默认值,下同)

false：即使注册失败，也不会抛出异常。例如不在ip白名单。建议线上环境配置为true，可以尽早发现注册问题。

3）、registrySessionTimeout  ：_60000ms_

server对注册中心的心跳周期，当服务状态变更时，注册中心会在${registrySessionTimeout}时间内感知



## **protocol配置（server端）：**

1）、id

配置bean的唯一标识，防止相同name冲突

2）、minWorkerThread  ：_20_

server端最小工作线程数，可根据平均qps进行设置

3）、maxWorkerThread ： _200_

server端最大工作线程数，可根据max qps进行设置

4）、workerQueueSize  

工作线程缓存队列。当工作线程达到max时，后续请求会进入queue中，根据业务request timeout进行设置，timeout较低的业务可以配置为0

5）、maxServerConnection ： _100000_

server端单服务端口最大允许建立的链接数。



## **protocol配置（client端）：**

1）、minClientConnection  ： _2_

client端对每一个server建立的最小链接数。根据并发qps、server节点数量、client节点数量配置

client初始化完毕后会预先建立minClientConnection个链接

2）、maxClientConnection  ：_10_

client端对每一个server建立的最大链接数。可根据max qps、client节点的数量、server端能承受的最大链接数进行设置

3）、loadbalance  ：_activeWeight_

负载均衡策略，根据业务场景配置。包括activeWeight、consistent、localFirst、random、roundrobin、configurableWeight

4）、haStrategy ： _failover_

高可用策略，根据业务场景配置。包括failover、failfast

5）、retries：_0_

配合failover高可用策略使用，指定重试次数。



## **service配置：**

1）、shareChannel ： _false_

true：可以和其他service共享端口，条件是protocol、codec、serialize等protocol配置必须相同

false：使用单独的worker线程池和单独的端口。使用于关键服务隔离

2）、export

对外提供服务的协议和端口，提供多个协议时用逗号分隔如export=“motan:8002,yar8003”

3）、accessLog  ：_false_

true:log每条请求日志。开启会对性能产生影响，如果开启建议使用motan异步log功能

4）、host

当有多个网卡时，可以用来指定提供服务的host或ip



## **referer配置：**

1）、directUrl

直连配置，形式为ip:port,ip:port

2）、requestTimeout  ：_200_

单次请求超时时间，failover策略下每次重试超时时间都为requestTimeout

3）、accessLog  ：_false_

同server端

4）、throwException  ：_true_

rpc请求失败是否抛出框架异常。业务异常不受此参数影响。false时，如果请求失败返回null。true时抛出框架异常。

**Comment by wilddylan** [comment]
感谢您快速的回复，我按照您提供的文档进行调试、测试后在与您反馈。官方文档比较杂乱，所以来这里要一个完善的Demo配置。
