### ISSUE TITLE
偶尔出现服务不可用，而且cpu很高

### ISSUE THREAD

**Issue by hebo1982** [weibocom/motan#531]
版本：0.3.1
jdk1.8.0_131
netty-3.2.5.Final

出现故障时一个异常日志：
017-09-13 11:25:03,741 ERROR [error 87] - NettyChannelHandler exceptionCaught: remote=/172.30.72.0:63338 local=/172.30.31.4:8002 event=java.io.IOException: Connection reset by peer
java.io.IOException: Connection reset by peer
sun.nio.ch.FileDispatcherImpl.read0(Native Method)
sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
sun.nio.ch.IOUtil.read(IOUtil.java:192)
sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:321)
org.jboss.netty.channel.socket.nio.NioWorker.processSelectedKeys(NioWorker.java:280)
org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:200)\
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:748)

8002 rpc 端口连接情况
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32179 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32290 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32869 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.72.0:63354 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32849 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:31968 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32095 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32592 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32787 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32655 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32731 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32368 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32504 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32348 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32710 CLOSE_WAIT  
tcp      294      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.72.0:63359 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32464 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32076 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32248 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32201 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32571 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32773 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32438 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32312 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32544 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32828 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:31990 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:31942 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32523 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32892 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32390 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32483 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32752 CLOSE_WAIT  
tcp        0      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.72.0:63430 ESTABLISHED 
tcp      293      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.72.0:63435 ESTABLISHED 
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32329 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32613 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32115 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32136 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32636 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32028 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32227 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32412 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32689 CLOSE_WAIT  
tcp        1      0 ::ffff:172.30.31.4:8002 ::ffff:172.30.31.1:32157 CLOSE_WAIT  

有个线程达到99%的cpu使用

   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                                                                    
  5670 root      20   0 16.291g 520700   4832 R 99.9  0.2   1591:18 java                                                                                                                                                                                       
     1 root      20   0 16.291g 520700   4832 S  0.0  0.2   0:00.02 java                                                                                                                                                                                       
    10 root      20   0 16.291g 520700   4832 S  0.0  0.2   0:00.68 java                                                                                                                                                                                       
    11 root      20   0 16.291g 520700   4832 S  0.0  0.2   1:24.11 java                                                                                                                                                                                       
    12 root      20   0 16.291g 520700   4832 S  0.0  0.2   1:24.70 java                                                                                                                                                                                       
    13 root      20   0 16.291g 520700   4832 S  0.0  0.2   1:23.28 java                                                                                                                                                                                       
    14 root      20   0 16.291g 520700   4832 S  0.0  0.2   1:23.90 java                                                                                                                                                                                       
    15 root      20   0 16.291g 520700   4832 S  0.0  0.2   1:24.14 java                                                                                                                                                                                       
    16 root      20   0 16.291g 520700   4832 S  0.0  0.2   1:24.08 java                                                                                                                                                                                       
    17 root      20   0 16.291g 520700   4832 S  0.0  0.2   1:24.48 java                 

线程，看似出现死锁
"New I/O client worker #1-1" #2075 daemon prio=5 os_prio=0 tid=0x00007f5638032000 nid=0x1626 runnable [0x00007f56c48d5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
	at sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:317)
	at sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:207)
	- locked <0x00000000e6057928> (a java.lang.Object)
	at java.nio.channels.spi.AbstractSelector$1.interrupt(AbstractSelector.java:213)
	at java.nio.channels.spi.AbstractSelector.begin(AbstractSelector.java:219)
	at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:92)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000000e6037240> (a sun.nio.ch.Util$3)
	- locked <0x00000000e6037230> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000000e6037098> (a sun.nio.ch.EPollSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:38)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:163)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

问题出现后，8002端口telnet是通的，但是服务连不上提示超时。
重启后问题消失。

**Comment by liuguozhuchina** [comment]
你cpu出现99%，这个问题需要抓取到java的线程看，不一定就是motan问题，也许是你内存太小，不够用，导致gc线程卡在那边，我们曾经出现过cpu巨高不小，最后发现是gc线程。具体怎么抓取线程中某个代码卡主，到网上搜了，我就不多说了。

**Comment by sundylgz** [comment]
你cpu出现99%，这个问题需要抓取到java的线程看，不一定就是motan问题，也许是你内存太小，不够用，导致gc线程卡在那边，我们曾经出现过cpu巨高不小，最后发现是gc线程。具体怎么抓取线程中某个代码卡主，到网上搜了，我就不多说了。

**Comment by hebo1982** [comment]
@sundylgz 
看下面的线程抓取的日志。

>  "New I/O client worker #1-1" #2075 daemon prio=5 os_prio=0 tid=0x00007f5638032000 nid=0x1626 runnable [0x00007f56c48d5000]
> java.lang.Thread.State: RUNNABLE
> at sun.nio.ch.EPollArrayWrapper.interrupt(Native Method)
> at sun.nio.ch.EPollArrayWrapper.interrupt(EPollArrayWrapper.java:317)
> at sun.nio.ch.EPollSelectorImpl.wakeup(EPollSelectorImpl.java:207)
> - locked <0x00000000e6057928> (a java.lang.Object)
> at java.nio.channels.spi.AbstractSelector$1.interrupt(AbstractSelector.java:213)
> at java.nio.channels.spi.AbstractSelector.begin(AbstractSelector.java:219)
> at sun.nio.ch.EPollSelectorImpl.doSelect(EPollSelectorImpl.java:92)
> at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
> - locked <0x00000000e6037240> (a sun.nio.ch.Util$3)
> - locked <0x00000000e6037230> (a java.util.Collections$UnmodifiableSet)
> - locked <0x00000000e6037098> (a sun.nio.ch.EPollSelectorImpl)
> at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
> at org.jboss.netty.channel.socket.nio.SelectorUtil.select(SelectorUtil.java:38)
> at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:163)
> at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
> at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:44)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> at java.lang.Thread.run(Thread.java:748)

**Comment by hebo1982** [comment]
http://ksoong.org/netty-highcpu
https://github.com/netty/netty/pull/2868

找到一个类似的问题，我这边测试一下看看。

**Comment by sundylgz** [comment]
motan版本中的netty存在这个bug，官方给出解决方案，https://github.com/netty/netty/pull/2868
After several times mail with Normal, this issue be fixed, pull request as https://github.com/netty/netty/pull/2868.

Base on above pull request, netty-3.6.10.Final is a fixed release.

If we change netty version to 3.6.10.Final

**Comment by hebo1982** [comment]
测试后motan 使用的 netty-3.2.5.Final，不会出现这个问题。
虽然跟https://github.com/netty/netty/pull/2868 很像，但并不是同一个问题。

目前还未找到我的问题重现办法。

**Comment by hebo1982** [comment]
https://github.com/ananas-hebo/motan/tree/0.3.1-update-netty/motan-transport-netty

讲netty升级到3.10.6.Final后运行一周没有再遇到类似问题。
需要调整一下StandardThreadExecutor.java，LinkedTransferQueue改为jdk自带的。

https://github.com/ananas-hebo/motan/commit/b8fc58ccc8312b319113ed5a8d2d2c643378a2bb#diff-67d907494b7009380ba650efaec3573e

注：3.7.0.Final 也有问题。
