### ISSUE TITLE
race issue

### ISSUE THREAD

**Issue by fucongchan** [weibocom/motan#532]
https://github.com/weibocom/motan/blob/2f5cc10db33d25ddf4de73584fb3bf50403e0243/motan-transport-netty/src/main/java/com/weibo/api/motan/transport/netty/StandardThreadExecutor.java#L104

由于没有保证原子性， 这里可能会存在一种情况， 当count+n个task同时提交， 这里产生竞争， count不断增大， 直到count>maxSubmittedTaskCount,  super.execute可能一次也没执行

**Comment by fucongchan** [comment]
这里对超过最大的并发任务限制是不可信赖的

**Comment by baojie5642** [comment]
没有问题

**Comment by baojie5642** [comment]
1.原子获得count，成为方法的局部变量，线程安全；2.用count与固定值maxSubmittedTaskCount比较，没有问题；3.根据刚才比较的结果确定正常提交还是使用拒绝策略，没有问题；4.海量线程也没问题，因为方法是线程所有的，没有不安全问题，所以上述的判断策略在多线程下可以起作用。
但是策略写的比较一般，可能是最新代码没有上传github。

**Comment by fucongchan** [comment]
@baojie5642  count自增， count与固定值maxSubmittedTaskCount比较， 以及后面的execute， 这一系列要保证原子操作， 才能保证正确

**Comment by fucongchan** [comment]
@rayzhang0603 please check as well...

**Comment by baojie5642** [comment]
花花，你变了

**Comment by baojie5642** [comment]
不用一系列原子，我上一段代码稍等：
public static String getName() {

        final boolean init = hasPut.get();

        if (init) {

            return loopGet();

        } else {

            if (hasPut.compareAndSet(false, true)) {

                name.set("you");

                return love.get();

            } else {

                return loopGet();

            }

        }

    }
问题代码和上述代码相似，使用原子操作来达到整体同步控制的目的，没必要全部整体是同步的。

**Comment by baojie5642** [comment]
修改成：
            name.set("you");

            return name.get();
