### ISSUE TITLE
安全性怎么控制，有白名单配置吗？

### ISSUE THREAD

**Issue by FutureElement** [weibocom/motan#555]
安全性怎么控制，有白名单配置吗？

**Comment by rayzhang0603** [comment]
暂时没有提供默认的权限管理，如果需要白名单管理建议通过自定义filter进行实现。
https://github.com/weibocom/motan/issues/192

**Comment by FutureElement** [comment]
有没有像dubbo一样可以取到调用上下文，知道调用者adress之类的信息？

**Comment by FutureElement** [comment]
有没有像dubbo一样可以取到调用上下文，知道调用者adress之类的信息？

**Comment by rayzhang0603** [comment]
在filter中可以直接获取到这些信息，这些信息都保存在request的attachments中。
获取远程调用方ip方法：
request.getAttachments().get(URLParamType.host.getName());

**Comment by FutureElement** [comment]
ok，感谢
