### ISSUE TITLE
motan2协议和默认的motan协议有什么区别吗？

### ISSUE THREAD

**Issue by FutureElement** [weibocom/motan#565]
motan2协议和默认的motan协议有什么区别吗？

**Comment by rayzhang0603** [comment]
motan2协议主要为了方便与其他语言互通，并对meta信息与请求内容进行了分离，方便代理层进行4层解析与转发。

目前其他语言的版本处在beta版本，文档也正在补充中，欢迎试用反馈或提建议，感谢～
[motan-go](https://github.com/weibocom/motan-go)
[motan-php](https://github.com/weibocom/motan-php)
[motan-openresty](https://github.com/weibocom/motan-openresty)
