### ISSUE TITLE
Motan使用ZK作为注册中心时，当服务所在机器ip变更时，注册中心仍然保留旧的ip，导致客户端连接失败

### ISSUE THREAD

**Issue by Succy** [weibocom/motan#589]
在使用zookeeper作为注册中心时，当服务所在机器的ip变换时，zk的节点下面保留的还是第一次发布服务时机器的ip，导致客户端发现的ip是以前的ip而连接不上服务。另外，尽管手动删除了zk下面/motan节点的所有内容，服务重新启动后，zk registry还是以前的ip ，[ZookeeperRegistry] Url (motan://192.168.1.12:8002/cn.succy.motan.api.HelloService?group=testgroup) will register to Registry [zookeeper://127.0.0.1:2181/default_rpc/com.weibo.api.motan.registry.RegistryService/1.0/service]
上面的ip就是之前的。请问该如何解决这个问题呢？

**Comment by rayzhang0603** [comment]
Motan注册的ip是通过`com.weibo.api.motan.util.NetUtils.getLocalAddress(Map<String, Integer> destHostPorts) `方法获取的本机ip地址，获取顺序为hostname对应的ip --> 根据连接目标端口得到的本地ip --> 轮询网卡，server端注册时可以通过xml配置host="***"来指定注册ip，也可以通过设置本机的hostname来指定注册的ip

**Comment by Succy** [comment]
@rayzhang0603 好的，谢谢，已经发现这个问题了，此外也是我个人的一个疏忽，由于之前不知道motan获取ip顺序，然而hosts文件又写死了一个hostname的ip，导致一直都是获取那个ip。
