### ISSUE TITLE
运行motan-demo报错

### ISSUE THREAD

**Issue by valleylord** [weibocom/motan#59]
运行motan-demo的motan-demo-client中的DemoRpcClient，spring装配，zookeeper注册中心，motan版本0.1.0，报错如下，

> Connected to the target VM, address: '127.0.0.1:49527', transport: 'socket'
> Disconnected from the target VM, address: '127.0.0.1:49527', transport: 'socket'
> Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'motanDemoReferer': FactoryBean threw exception on object creation; nested exception is com.weibo.api.motan.exception.MotanFrameworkException: error_message: Create registry false for url:zookeeper://127.0.0.1:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc, status: 503, error_code: 20004,r=
>     at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:175)
>     at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
>     at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1585)
>     at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:254)
>     at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
>     at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1051)
>     at com.weibo.motan.demo.client.DemoRpcClient.main(DemoRpcClient.java:29)
> Caused by: com.weibo.api.motan.exception.MotanFrameworkException: error_message: Create registry false for url:zookeeper://127.0.0.1:2181/com.weibo.api.motan.registry.RegistryService?group=default_rpc, status: 503, error_code: 20004,r=
>     at com.weibo.api.motan.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:63)
>     at com.weibo.api.motan.cluster.support.ClusterSupport.getRegistry(ClusterSupport.java:129)
>     at com.weibo.api.motan.cluster.support.ClusterSupport.init(ClusterSupport.java:89)
>     at com.weibo.api.motan.config.handler.SimpleConfigHandler.buildClusterSupport(SimpleConfigHandler.java:52)
>     at com.weibo.api.motan.config.RefererConfig.createClusterSupport(RefererConfig.java:184)
>     at com.weibo.api.motan.config.RefererConfig.initRef(RefererConfig.java:128)
>     at com.weibo.api.motan.config.RefererConfig.getRef(RefererConfig.java:85)
>     at com.weibo.api.motan.config.springsupport.RefererConfigBean.getObject(RefererConfigBean.java:41)
>     at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
>     ... 6 more
> Caused by: org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 200
>     at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:880)
>     at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:98)
>     at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:92)
>     at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:80)
>     at com.weibo.api.motan.registry.zookeeper.ZookeeperRegistryFactory.createRegistry(ZookeeperRegistryFactory.java:44)
>     at com.weibo.api.motan.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:56)
>     ... 14 more

但是，motan-demo-server没有报错，是不是我哪里配错了？或者是环境问题？

**Comment by syndory** [comment]
server没用zk注册，client用了。改一下client寻找服务的方式
请参考 #45

**Comment by sunnights** [comment]
这个可能是因为初始化zkclient的连接超时时间过短（200ms）导致的，目前zkclient获取的是requestTimeout，默认200ms，需要修正为connectTimeout

**Comment by valleylord** [comment]
这个问题不是每次都能重现的，偶尔可能成功，有可能是@sunnights说的timeout问题。我的测试机器有点破

**Comment by valleylord** [comment]
这个问题，我在测试中发现，正确的时候，zookeeper里面有server注册的服务，如下，

> [zk: localhost:2181(CONNECTED) 5] ls /motan/motan-demo-rpc/com.weibo.motan.demo.
service.MotanDemoService/server
[192.168.232.154:28002, 192.168.232.154:28001]

错误的时候，zookeeper里面找不到server注册的服务，如下，

> [zk: localhost:2181(CONNECTED) 5] ls /motan/motan-demo-rpc/com.weibo.motan.demo.
service.MotanDemoService/server
Node does not exist: /motan/motan-demo-rpc/com.weibo.motan.demo.
service.MotanDemoService/server

感觉是因为某些原因，server的服务在zookeeper上没有注册成功。

**Comment by qdaxb** [comment]
已经在0.1.1版中修复这个问题，可以配置registry的connectTimeout参数，可以把registry的connectTimeout配大一点（例如5秒）再试试。
