### ISSUE TITLE
如何手动注入  @MotanReferer

### ISSUE THREAD

**Issue by cccvip** [weibocom/motan#594]
1 习惯性的注入bean可以将
 @Bean
    public FilterRegistrationBean filterRegistrationBean(){
        FilterRegistrationBean registrationBean=new FilterRegistrationBean();

        Cuilter customFilter=new Cuilter();

        registrationBean.setFilter(customFilter);
        registrationBean.addUrlPatterns("/*");
        registrationBean.setName("customFilter");

        return registrationBean;
    }
2 那么获取motan这个怎么使用呢？？

**Comment by rayzhang0603** [comment]
@MotanReferer就是为了解决注解注入的，直接使用这个注解就好，使用方式可以参考demo模块的com.weibo.motan.demo.client,SpringBootRpcClientDemo, com.weibo.motan.demo.client.HelloController

**Comment by cccvip** [comment]
1我希望能这样子获取
@Override
public void init(FilterConfig filterConfig) throws ServletException {
	ServletContext servletContext = filterConfig.getServletContext();
	ApplicationContext ctx = WebApplicationContextUtils.getWebApplicationContext(servletContext);
	productService = (ProductService)ctx.getBean("productService");
}
2 因为用的SpringBoot放弃了所有的XML的配置，反而不知道如何获取Service了。 我这样的方法不行还是因为我的思路错误

**Comment by rayzhang0603** [comment]
直接使用@controller注解，然后在对应需要注入的成员上加上 @MotanReferer注解不就可以了吗。可以参考demo模块中的例子

```java
@RestController
public class HelloController {

    @MotanReferer(basicReferer = "motantestClientBasicConfig", group = "testgroup", directUrl = "127.0.0.1:8002")
    MotanDemoService service;
}
```

**Comment by cccvip** [comment]
您还是没有理解我的意思，我知道您推荐的是可以的。不过我想在filter中使用，到达controller层之前，某些请求已经被过滤掉。 所以我才想使用ServletContext servletContext = filterConfig.getServletContext(); 获取Bean的方式获取.

**Comment by rayzhang0603** [comment]
MotanReferer这个注解并不是在spring的上下文中添加bean，所以不能直接通过spring的上下文获取。
你说的场景，我也没有想到比较优雅的方法，可以试试单独定义一个bean，将MotanReferer作为成员在封装一下

**Comment by cccvip** [comment]
行，谢谢解答！
