### ISSUE TITLE
release note问题

### ISSUE THREAD

**Issue by zhangweixin** [weibocom/motan#603]
可否像dubbo类似在发布版本的时候加上release note，这样就可以知道发布的版本有哪些新功能，有哪些bug修复，每次都找不到发布日志，不知道有哪些改进以及新功能，谢谢！

**Comment by rayzhang0603** [comment]
每次发布新版本会更新代码中changelog，可以参考这个
https://github.com/weibocom/motan/blob/master/CHANGELOG.md

**Comment by zhangweixin** [comment]
en,看到了，谢谢！
