### ISSUE TITLE
HA负载均衡的副作用

### ISSUE THREAD

**Issue by rockonthesun** [weibocom/motan#604]
公司里边的cloud foundry 用的HA 去做负载均衡，想把motan 客户端配置成directUrl="HA的ip:port" 去替代zookeeper。不知道这样做会不会有什么副作用， 因为我看到motan源码和zookeeper, consul 集成的比较好

**Comment by rayzhang0603** [comment]
directUrl不方便通过配置变更，一般只用在测试场景。建议使用direct的注册中心来进行直连，这样可以使用placeholder占位符表示协议，方便以后变更。另外 directurl也可以支持多组ip，多ip地址用逗号分隔。

例如：

    <motan:registry regProtocol="${myRegistryProtocol}" name="registry" address="${registryAddress}" connectTimeout="2000"/>

properties可以配置:
myRegistryProtocol=direct
#myRegistryProtocol=zookeeper
registryAddress=127.0.0.1:8888,127.0.0.1:8889
#registryAddress=127.0.0.1:2181

**Comment by idevz** [comment]
生产环境不建议使用 directUrl，如果用传统的 HA 做负载均衡，而通过 directUrl 去直连 HA，那 Motan 本身擅长的 Client side的服务治理功能将被大大弱化。整个体系基于 Motan 通过注册中心去管理所有 Motan 服务，而不是传统的 HA，那样感觉又回到了传统的 HTTP 时代，负载均衡，高可用等服务治理都通过四七层来实现。

**Comment by rockonthesun** [comment]
首先，非常感谢回复！
“那 Motan 本身擅长的 Client side的服务治理功能将被大大弱化”
可以更具体说明下被弱化的功能么。我能想到的是motan优雅的停止服务，还有客户端定时发送心跳检测包，以检测服务端是否可用。以及管理后台提供的RPC服务查询、流量切换功能。

可不可以帮忙补充魔毯和四七层的服务治理各自主要优缺点

**Comment by idevz** [comment]
我大致说下我对这个问题的理解，一起探讨下，架构这个东西不落到实处都是虚妄，每种方案本身其实都是了适合某种场景的一种取舍，并没有啥好坏，优缺之分。
基于你上面列举的这些点，我做如下补充：
首先传统集中化的 HA 方案是一个中心化的转发节点，流量转发配置是死的，变更需要重启 HA，而基于此的服务治理，基本只能靠传统日志分析，监控，整个过程很难做到精准实时，
而Client Side 是去中心化的方案，关注的是 Client自身根据通过注册中心的集群服务状态和一系列的 负载均衡策略来决定往哪儿去，不止解决了请求分发的问题，因为去除了四七层，
你可以精准把握每一个 Client 对 Server 发起的直连请求，这就有很大的想象空间了，可做的事情就太多了，不是简单几个好处能列举出来的，
举个通过双发请求消除请求长尾的实践来说明这一点，传统的 HA 方式，请求先到 HA，再转发，所以 Client 并不知道自己请求到的是哪个 Server，链接不直达，
所以面对由于各种问题（比如网络抖动，服务器状态变化等）引起的请求缓慢，出现的请求长尾，难以有效消除，甚至还有超时等情况，只能盲目重试，但是如果是 Client 直连 Server，响应时间超过某一阈值
时，我们可以发起备份请求（双发），如果后发的请求在先发请求之前响应，则可直接将之前的慢请求丢弃，有效解决了长尾问题。
诸如此类只有当我们对每个请求都具备精准控制的能力才能做到，这是传统 HA 所不具备的。
值得一提的Motan Client Side 的服务治理是整个 Motan 跨语言服务化体系中比较重要的一环，欢迎持续关注。

**Comment by rockonthesun** [comment]
明白了，去中心化和精准把握每一个client对server发起的直连请求，确实有了太多的发挥的空间。
非常感谢，受益匪浅！

**Comment by chenxb2015** [comment]
呵呵呵
