### ISSUE TITLE
服务注册两次问题，导致项目无法启动

### ISSUE THREAD

**Issue by zjpjohn** [weibocom/motan#622]
[zookeeper://127.0.0.1:2181/default_rpc/com.weibo.api.motan.registry.RegistryService/1.0/service]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getM180c88024339, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getMerchantSaasByMobile, paramtersDesc=java.lang.String, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getMfc757f6b68e5, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getMerchantAdminByName, paramtersDesc=java.lang.String, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getMea6681473405, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getMerchantSaasBySaasId, paramtersDesc=java.lang.Long, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:updade6215142c9d, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=updateStoreMerchantAdmin, paramtersDesc=com.cloud.o2o.domain.StoreMerchantAdmin, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:addSbacc51cbb6fc, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=addStoreMerchantAdmin, paramtersDesc=com.cloud.o2o.domain.StoreMerchantAdmin, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:upda5cc895196bab, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=updateMerchantAuthInfo, paramtersDesc=com.cloud.o2o.domain.MerchantAuthInfo, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getS1041497c3049, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getStoreMerchantAdmin, paramtersDesc=com.cloud.o2o.domain.StoreMerchantAdmin, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getM3b6877b76b02, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getMerchantSubAdmin, paramtersDesc=long, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getM5709499a07ff, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getMerchantAdminByMobile, paramtersDesc=java.lang.String, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:upda559d1d71a8e6, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=updateMerchantInfo, paramtersDesc=com.cloud.o2o.domain.MerchantSaasInfo, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getMb40aa9682053, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getMerchantAuthBySaasId, paramtersDesc=java.lang.Long, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:dele7f207ffaf277, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=deleteStoreMerchantAdmin, paramtersDesc=com.cloud.o2o.domain.StoreMerchantAdmin, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:getSf6a632e6ca36, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=getStoreByMerchantAdmin, paramtersDesc=com.cloud.o2o.domain.MerchantAdmin, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:addM412d0399591f, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=addMerchantAuthInfo, paramtersDesc=com.cloud.o2o.domain.MerchantAuthInfo, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:updaa64125f820a4, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=updateMerchantAdmin, paramtersDesc=com.cloud.o2o.domain.MerchantAdmin, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:addM2724388d6750, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=addMerchantAdmin, paramtersDesc=com.cloud.o2o.domain.MerchantAdmin, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - add method sign:addM9c0662d68382, methodinfo:MethodInfo [group=o2o-yunying, interfaceName=com.cloud.o2o.service.MerchantInfoMotanService, methodName=addMerchantInfo, paramtersDesc=com.cloud.o2o.domain.MerchantSaasInfo, version=1.0]
[ INFO ] [2017-12-21 19:28:51] info [55] - RequestRouter addProvider: url=motan://192.168.84.1:8082/com.cloud.o2o.service.MerchantInfoMotanService?group=o2o-yunying all_public_method_count=27
[ INFO ] [2017-12-21 19:28:51] info [59] - NettyEndpointFactory create share_channel server: url=motan://192.168.84.1:8082/com.cloud.o2o.service.MerchantInfoMotanService?group=o2o-yunying
[ WARN ] [2017-12-21 19:28:51] warn [67] - NettyServer ServerChannel already Open: url=motan://192.168.84.1:8082/?group=o2o-yunying
[ INFO ] [2017-12-21 19:28:51] info [55] - DefaultRpcExporter node init Success: [DefaultRpcExporter] url=motan://192.168.84.1:8082/com.cloud.o2o.service.MerchantInfoMotanService?group=o2o-yunying
[ INFO ] [2017-12-21 19:28:51] info [55] - DefaultRpcProtocol export Success: url=motan://192.168.84.1:8082/com.cloud.o2o.service.MerchantInfoMotanService?group=o2o-yunying
[ INFO ] [2017-12-21 19:28:51] info [59] - [ZookeeperRegistry](motan://192.168.84.1:8082/com.cloud.o2o.service.MerchantInfoMotanService?group=o2o-yunying) will register to Registry [zookeeper://127.0.0.1:2181/default_rpc/com.weibo.api.motan.registry.RegistryService/1.0/service]
[ WARN ] [2017-12-21 19:28:51] warn [67] - com.cloud.o2o.service.MerchantInfoMotanService configService is malformed, for same service (motan://192.168.84.1:8082/o2o-yunying/com.cloud.o2o.service.MerchantInfoMotanService/1.0/service) already exists 
[ WARN ] [2017-12-21 19:28:51] org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext [550] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 

[ ERROR] [2017-12-21 19:28:51] org.springframework.boot.SpringApplication [815] - Application startup failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'merchantInfoMotanServiceImpl' defined in file
导致项目启动不起来，这个项目两面有有多个motan provider类，但是只有这一个出现问题，这个类中有17个方法，是否是因为方法过多引起服务注册两边。但是把这个类注释掉以后，想能够正常启动

1.0.0 和1.1.0这两个版本都存在这样的问题

**Comment by rayzhang0603** [comment]
service方法多少与注册无关的，能提供一下具体配置吗？有没有可能在不同的jar包中配置了两遍？或者同时使用了xml和注解加载两种方式？
如果能过本地调试的话，可以试试在ServiceConfig.doExport()方法确认一下服务导出两次的原因

**Comment by zjpjohn** [comment]
项目使用Springboot启动的 
1. 在类上注解了
@MotanService
public class MerchantInfoMotanServiceImpl implements MerchantInfoMotanService 
这个类只在这个项目中才有
2.在yml中的配置如下
motan:
     scan:
       annotation-packages: com.cloud.o2o.yunying
     protocol:
       name: motan
       maxContentLength: 1048576
       isDefault: true
     registry:
       address: 127.0.0.1:2181,127.0.0.1:2182,127.0.0.1:2183
       reg-protocol: zookeeper
       register: true
       connect-timeout: 5000
       request-timeout: 3000
    service:
       export: motan:8082
       group: o2o-yunying
       application: o2o-yunying-provider
       request-timeout: 3000
其余采用默认配置

**Comment by rayzhang0603** [comment]
把类上的注解去掉试试。
注解@motanservice和xml中的service配置是等价的，这两种只配置一个就行

**Comment by zjpjohn** [comment]
整个应用没有xml配置  全部是注解方式

**Comment by zjpjohn** [comment]
我再查查  我把源码clone下来 测一测
