### ISSUE TITLE
netty包冲突，请问如何解决??

### ISSUE THREAD

**Issue by ZhouXunYou** [weibocom/motan#624]
![default](https://user-images.githubusercontent.com/11326793/34350809-aba53bce-ea53-11e7-832f-5d63a92dc353.png)
![default](https://user-images.githubusercontent.com/11326793/34350820-c68cf288-ea53-11e7-87a0-27de5dd28546.png)

**Comment by sunnights** [comment]
你好，motan-tranport-netty依赖netty的3.2.5版本，无法进行升级，你可以选择统一配置成3.2.5版本，或者使用motan-tranport-netty4，netty3可以配置成3.7.0版本

**Comment by ZhouXunYou** [comment]
tks
