### ISSUE TITLE
motan能支持泛型调用吗？

### ISSUE THREAD

**Issue by GeniusQ** [weibocom/motan#632]
接口声明并实现
<T> void test(T obj) 

客户端调用
tester.test(new Date());

服务器返回
ProviderProtectedMessageRouter handler Error: provider not exist serviceKey=xxx.ITester method=test(java.lang.Object), status: 503, error_code: 10001,r=null

**Comment by rayzhang0603** [comment]
motan支持范型调用，这个异常表示server端没有找到对应的service实现。serviceKey由group、接口全名、version组成，client调用时这三个参数必须与server端注册的一致。你可以检查一下server和client 的这三个配置值是否一致

**Comment by GeniusQ** [comment]
实在抱歉，我这边复查了一下，client配置中端口号写错了。
感谢回复。
