### ISSUE TITLE
motan可以server和 client 相互提供rpc服务器吗?

### ISSUE THREAD

**Issue by maregeo** [weibocom/motan#636]
比如有 3个项目 webapp1   motan-api  webapp2  
webapp1 提供给webapp2  注册登录服务器
webapp2 提供给webapp1  查询订单服务器

可以这样吗？

**Comment by rayzhang0603** [comment]
motan能够支持这种相互依赖的场景，需要在basicreferer或者referer中配置check=false，这样当获取不到server节点时仍然可以正常启动服务。
不过推荐还是通过服务解耦的方式解决这个问题

**Comment by maregeo** [comment]
非常感谢~！！！
