### ISSUE TITLE
添加广播模式以及一致性hash配置建议

### ISSUE THREAD

**Issue by cj520120** [weibocom/motan#638]
@rayzhang0603 
 我在业务中经常需要有状态服务，所以需要采用一致性hash，例如A服务提供了一组用户相关接口，其他业务在调用A的相关接口时对相同用户需要路由到该服务的固定机器，目前motan未发现对这块进行支持，希望可以加入，下面是我进行的扩展，请评估下可行性以及相关建议

- [  一致性hash] 
 <pre>
// 一致性hash 方法配置，该方法用于配置服务方法hash参数
 
@Retention(RetentionPolicy.RUNTIME)
@Target({ElementType.METHOD})
public @interface MethodHash {
    // hash参数索引
    int value() default 0;
}

import java.security.MessageDigest;
import java.util.*;

// 一致性HASH方法,该方法修改于dubbo
public class ConsistentHash<T> {
    private ConsistentHashSelector<T> selectors = null;
    private final int replicaNumber = 160;

    public void refresh(List<T> consistentInvokers, InvokerKeyFunction<T> invokerKeyFunction) {
        this.selectors = new ConsistentHashSelector<>(consistentInvokers, invokerKeyFunction, replicaNumber);

    }

    public T select(Object[] args) {
        return this.select(args, 0);
    }

    public T select(Object[] args, int hashIndex) {
        T ref = null;
        if (this.selectors != null) {
            ref = this.selectors.select(args != null & args.length > hashIndex ? args[hashIndex] : null);
        }
        return ref;
    }

    public static final class ConsistentHashSelector<T> {
        private final TreeMap<Long, T> virtualInvokers;
        private final int replicaNumber;

        public ConsistentHashSelector(List<T> invokers, InvokerKeyFunction<T> invokerKeyFunction, int replicaNumber) {
            this.replicaNumber = replicaNumber;
            this.virtualInvokers = new TreeMap<>();
            List<T> copyInvokers = new ArrayList<>(invokers);
            Collections.sort(copyInvokers, (T o1, T o2) -> invokerKeyFunction.key(o1).compareTo(invokerKeyFunction.key(o2)));
            copyInvokers.forEach(invoker -> {
                int count = this.replicaNumber / 4;
                for (int i = 0; i < count; i++) {
                    byte[] digest = md5(invokerKeyFunction.key(invoker) + "_" + i).getBytes();
                    for (int j = 0; j < 4; j++) {
                        long m = hash(digest, j);
                        virtualInvokers.put(m, invoker);
                    }
                }
            });
        }

        public T select(Object arg) {
            String key = arg == null ? "" : arg.toString();
            byte[] digest = md5(key).getBytes();
            long hash = hash(digest, 0);
            if (!virtualInvokers.containsKey(hash)) {
                SortedMap<Long, T> tailMap = virtualInvokers.tailMap(hash);
                if (tailMap.isEmpty()) {
                    hash = virtualInvokers.firstKey();
                } else {
                    hash = tailMap.firstKey();
                }
            }
            return virtualInvokers.get(hash);
        }

        private long hash(byte[] digest, int number) {
            return (((long) (digest[3 + number * 4] & 0xFF) << 24) | ((long) (digest[2 + number * 4] & 0xFF) << 16) | ((long) (digest[1 + number * 4] & 0xFF) << 8) | (digest[0 + number * 4] & 0xFF)) & 0xFFFFFFFFL;
        }

        private String md5(String sign) {
            char hexDigits[] = {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'a', 'b', 'c', 'd', 'e', 'f'};
            try {
                byte[] strTemp = sign.getBytes();
                MessageDigest mdTemp = MessageDigest.getInstance("md5");
                mdTemp.update(strTemp);
                byte[] md = mdTemp.digest();
                int j = md.length;
                char str[] = new char[j * 2];
                int k = 0;
                for (int i = 0; i < j; i++) {
                    byte byte0 = md[i];
                    str[k++] = hexDigits[byte0 >>> 4 & 0xf];
                    str[k++] = hexDigits[byte0 & 0xf];
                }
                return new String(str);
            } catch (Exception e) {
                return null;
            }
        }
    }

    @FunctionalInterface
    public static interface InvokerKeyFunction<T> {
        String key(T invoker);
    }
}

 @SpiMeta(name = "hash")
public class ConsistentHashLoadBalance<T> implements LoadBalance<T> {
    private ConsistentHash<Referer<T>> consistentHash;
    private List<Referer<T>> referers;

    @Override
    public void onRefresh(List<Referer<T>> referers) {
        this.referers = referers;
        ConsistentHash<Referer<T>> tempConsistentHash = new ConsistentHash<>();
        tempConsistentHash.refresh(referers, t -> t.getUrl().getProtocol() + "://" + t.getUrl().getHost() + ":" + t.getUrl().getPort());
        this.consistentHash = tempConsistentHash;
    }

    @Override
    public void setWeightString(String weightString) {

    }

    protected Referer<T> doSelect(Request request, int index) {
        return this.consistentHash.select(request.getArguments(), index);
    }

    @Override
    public Referer<T> select(Request request) {
        return this.select(request, 0);
    }

    @Override
    public void selectToHolder(Request request, List<Referer<T>> refersHolder) {
        this.selectToHolder(request, refersHolder, 0);
    }

    public void selectToHolder(Request request, List<Referer<T>> refersHolder, int index) {
        List<Referer<T>> referers = this.referers;

        if (referers == null) {
            throw new MotanServiceException(this.getClass().getSimpleName() + " No available referers for call : referers_size= 0 "
                    + MotanFrameworkUtil.toString(request));
        }

        if (referers.size() > 1) {
            doSelectToHolder(request, refersHolder, index);

        } else if (referers.size() == 1 && referers.get(0).isAvailable()) {
            refersHolder.add(referers.get(0));
        }
        if (refersHolder.isEmpty()) {
            throw new MotanServiceException(this.getClass().getSimpleName() + " No available referers for call : referers_size="
                    + referers.size() + " " + MotanFrameworkUtil.toString(request));
        }
    }

    public Referer<T> select(Request request, int index) {
        List<Referer<T>> referers = this.referers;
        if (referers == null) {
            throw new MotanServiceException(this.getClass().getSimpleName() + " No available referers for call request:" + request);
        }
        Referer<T> ref = null;
        if (referers.size() > 1) {
            ref = doSelect(request, index);

        } else if (referers.size() == 1) {
            ref = referers.get(0).isAvailable() ? referers.get(0) : null;
        }

        if (ref != null) {
            return ref;
        }
        throw new MotanServiceException(this.getClass().getSimpleName() + " No available referers for call request:" + request);
    }

    protected void doSelectToHolder(Request request, List<Referer<T>> refersHolder, int index) {
        if (this.consistentHash != null) {
            refersHolder.add(this.consistentHash.select(request.getArguments(), index));
        }
    }

}

@SpiMeta(name = "hash")
public class ConsistentHashHaStrategy<T> extends AbstractHaStrategy<T> {
    private final static ConcurrentHashMap<String, ConcurrentHashMap<String, Integer>> METHOD_HASH_INDEX = new ConcurrentHashMap<>();

    @Override
    public Response call(Request request, LoadBalance<T> loadBalance) {
        if (loadBalance instanceof ConsistentHashLoadBalance) {
            ConsistentHashLoadBalance<T> consistentHashLoadBalance = (ConsistentHashLoadBalance<T>) loadBalance;
            String methodDesc = com.weibo.api.motan.util.ReflectUtil.getMethodDesc(request.getMethodName(), request.getParamtersDesc());
            ConcurrentHashMap<String, Integer> map = METHOD_HASH_INDEX.computeIfAbsent(request.getInterfaceName(), (className) -> {
                ConcurrentHashMap<String, Integer> methodHashMap = new ConcurrentHashMap<>();
                try {
                    Class<?> invokerClass = com.weibo.api.motan.util.ReflectUtil.forName(className);
                    Method[] methods = invokerClass.getMethods();
                    for (Method method : methods) {
                        String methodKey = com.weibo.api.motan.util.ReflectUtil.getMethodDesc(method);
                        MethodHash methodHash = method.getDeclaredAnnotation(MethodHash.class);
                        if (methodHash != null && methodHash.value() > 0 && methodHash.value() > method.getParameterCount()) {
                            throw new MotanServiceException("hash must<= " + method.getParameterCount() + " method parameter count." + request.getInterfaceName() + "." + request.getMethodName());
                        }
                        methodHashMap.put(methodKey, methodHash == null ? 0 : methodHash.value());
                    }
                } catch (ClassNotFoundException e) {
                    throw new MotanFrameworkException("hash service is not found." + className);
                }
                return methodHashMap;
            });
            Response response = consistentHashLoadBalance.select(request, map.getOrDefault(methodDesc, 0)).call(request);
            return response;
        } else {
            throw new MotanServiceException("hash call must set loadbalance is 'hash'");
        }

    }

}</pre>
- [  广播调用] 
<pre>
//提供广播模式  
@SpiMeta(name = "broadcast")
public class BroadcastLoadBalance<T> extends AbstractLoadBalance<T> {
    private Referer<T> referer;

    @Override
    public void onRefresh(List<Referer<T>> referers) {
        if (referers != null && referers.size() > 0) {
            Class<T> tClass = referers.get(0).getInterface();
            URL url = referers.get(0).getUrl().createCopy();
            url.setHost("broadcast");
            url.setPort(0);
            this.referer = new BroadcastReferer(tClass, url, referers);
        } else {
            this.referer = null;
        }
        super.onRefresh(Arrays.asList(referer));
    }

    @Override
    protected Referer<T> doSelect(Request request) {
        return referer;
    }

    @Override
    protected void doSelectToHolder(Request request, List<Referer<T>> refersHolder) {
        if (this.referer != null) {
            refersHolder.add(this.referer);
        }
    }

    static class BroadcastReferer<T> extends AbstractReferer<T> {
        public List<Referer<T>> referers;

        public BroadcastReferer(Class<T> clz, URL url, List<Referer<T>> referers) {
            super(clz, url);
            this.referers = referers;
        }

        @Override
        public boolean isAvailable() {
            return referers.stream().filter(t -> t.isAvailable()).findFirst() != null;
        }

        @Override
        protected Response doCall(Request request) {
            referers.stream().filter(t -> t.isAvailable()).forEach(t -> t.call(request));
            return new DefaultResponse(null, request.getRequestId());
        }

        @Override
        protected boolean doInit() {
            return true;
        }

        @Override
        public void destroy() {
            referers.forEach(t -> t.destroy());
        }
    }
}

@SpiMeta(name = "broadcast")
public class BroadcastHaStrategy<T> extends AbstractHaStrategy<T> {
    @Override
    public Response call(Request request, LoadBalance<T> loadBalance) {
        if (loadBalance instanceof BroadcastLoadBalance) {
            return loadBalance.select(request).call(request);
        } else {
            throw new MotanServiceException("broadcast call must set loadbalance is 'broadcast'");
        }
    }
}</pre>

**Comment by rayzhang0603** [comment]
有下面几个建议：
1、一致性hash只是负载均衡策略，建议只进行loadbalance的扩展，不要与HA策略绑定。
2、广播模式可以考虑多个referer并行调用

另外，上面的一致性hash算法在节点变更时依然可能产生调用偏移。在需要一致性hash的场景，最好对注册中心也进行一下扩展，支持静态server方式。

**Comment by cj520120** [comment]
非常感谢您的建议 @rayzhang0603

**Comment by winner1207** [comment]
@winner1207  mark一下，我们的业务场景也需要用到广播的方式
