### ISSUE TITLE
motan是否支持其他序列化方式

### ISSUE THREAD

**Issue by valleylord** [weibocom/motan#65]
版本0.1.0，看目前的文档，motan目前似乎只支持hessian序列化方式，还支持其他序列化方式么？未来有预期增加序列化方式么？如果我要增加一种序列化方式，我可以如何写一些代码来扩展motan？

**Comment by Ive4** [comment]
<motan:protocol name="motan" serialization="fastjson"/> 其他的估计继承 com.weibo.api.motan.codec.Serialization 然后@SpiMeta(name = "xxx")  ：xxx为serialization名字自定义，然后也许就可以使用了，目前看他们源码是这样做的，不行的话那就要更深层次研究下，我正在搞

**Comment by sundylgz** [comment]
支持 hession2 和  fastjson

**Comment by sundylgz** [comment]
支持hessian2 和阿里巴巴开源的 fastjosn
