### ISSUE TITLE
pherialize-1.2.1.jar 这个包在仓库找不到了

### ISSUE THREAD

**Issue by JerryChaox** [weibocom/motan#674]
![image](https://user-images.githubusercontent.com/20492061/37898993-d5609db8-311c-11e8-86ce-246835a1ced2.png)

**Comment by rayzhang0603** [comment]
https://nexus.ailis.de/content/groups/public/de/ailis/pherialize/pherialize/1.2.1/

**Comment by JerryChaox** [comment]
感谢
