### ISSUE TITLE
Using Motan , heap memory is not released 

### ISSUE THREAD

**Issue by amitrajbaral** [weibocom/motan#676]
I am using motan to call some apis, i am calling it with big data and hundreds of request per second , even after completion of the program and i received response, heap memory is not freed and it is using somewhere around 2000MB in the server , so next execution, it will increase, hence crash the system with java heap out of memory. Is there any solution on this?

**Comment by sunnights** [comment]
you can use jmap to find out which instance occupies most of the memory, and lookup why it didn't release by your code.

**Comment by amitrajbaral** [comment]
Got it, thank you
