### ISSUE TITLE
motan的最新版本问题

### ISSUE THREAD

**Issue by asunlzy** [weibocom/motan#678]
请问motan最新并且稳定的能用在生产环境的版本号是什么？

**Comment by asunlzy** [comment]
我要下载motan1.1.0版本的代码，请问下载的url是什么？

**Comment by asunlzy** [comment]
上面3个问题请统一回复一下，谢谢。

**Comment by sunnights** [comment]
在maven仓库搜motan即可找到最新的正式版本及下载链接
http://mvnrepository.com/artifact/com.weibo/motan-core

关注https://github.com/weibocom/motan/releases 也可以下载最新版本及相关代码
