### ISSUE TITLE
微服务之间隔离问题

### ISSUE THREAD

**Issue by fallsea** [weibocom/motan#681]
有A和B两个不同的微服务，同一个客户端需要根据不同的需求调用不同的微服务。

微服务的service接口有可能是一样的，请问目前是否支持这种隔离处理和调用，目前测试使用协议、分组、模块都不行。

![qq 20180410084838](https://user-images.githubusercontent.com/30261057/38530263-3283d30e-3c9c-11e8-9fc1-7f27441aea94.png)

**Comment by sunnights** [comment]
client是根据订阅的group分组来决定调哪个服务的  
你的需求可以将A、B两个微服务分别配不同的group，如group-A, group-B  
client写两个referer，一个referer的group配group-A，另一个配group-B  
这样使用不同的referer就能调不同的微服务

**Comment by fallsea** [comment]
@sunnights 我也是这样想的，也这样测试过，由于有些service名称和路径是一样的，导致客户端启动初始化只能初始化一个referer

**Comment by sunnights** [comment]
实测没有问题啊，不知道你具体卡在哪个地方，报什么错？
```
<motan:referer id="motanDemoReferer"
    interface="com.weibo.motan.demo.service.MotanDemoService"
    group="motan-demo-rpc" basicReferer="motantestClientBasicConfig"/>
<motan:referer id="motanDemoReferer2"
    interface="com.weibo.motan.demo.service.MotanDemoService"
    group="motan-demo-rpc-2" basicReferer="motantestClientBasicConfig">
</motan:referer>

MotanDemoService service = (MotanDemoService) ctx.getBean("motanDemoReferer");
MotanDemoService service2 = (MotanDemoService) ctx.getBean("motanDemoReferer2");
```

**Comment by fallsea** [comment]
@sunnights 多谢，找到原因了，我使用注解的模式，必须在注解上加上`group`才可以。


最开始以为只需要在这个对象`BasicRefererConfigBean`里面处理就可以了。

```
@MotanReferer(basicReferer = "easyadminTaskClientBasicConfig",group="easyadmin-task")
 private FunctionAsync function;
```

**Comment by fallsea** [comment]
@sunnights 多谢，已经解决了，我使用的是注解方式，客户端配置的扫描包没有配置正确
