### ISSUE TITLE
motan有多机房集群感知、集群容灾切换能力吗？

### ISSUE THREAD

**Issue by longXboy** [weibocom/motan#686]
可以像spring cloud里的ribbon或者istio里的envoyproxy那样设置多个机房集群(region-zone-cluster)，然后单个集群不可用了之后自动切换吗？如果有的话，内部是怎么实现的呢？

**Comment by sunnights** [comment]
配置里的group参数可以用来区分不同机房，client默认只能调group配置相同的服务（即同机房）  
当某个group压力大或不可用时，可以进行[流量切换](https://github.com/weibocom/motan/wiki/zh_userguide#%E6%B5%81%E9%87%8F%E5%88%87%E6%8D%A2%E9%9C%80%E8%A6%81%E7%AE%A1%E7%90%86%E5%91%98%E6%9D%83%E9%99%90)

**Comment by longXboy** [comment]
谢谢
