### ISSUE TITLE
如何让长时间的请求，等处理完再响应

### ISSUE THREAD

**Issue by Python-IBM** [weibocom/motan#699]
官方技术人员，你们好！motan在请求大数据长时间访问时，就会超时，这时tomcat就“死”掉了，不断的调整设置超时大小不是最好的方式。请问motan如何实现请求service接口之后，而不是一直在请求，等处理完数据之后再响应给浏览器？

**Comment by rayzhang0603** [comment]
你好，没有看明白你的使用场景及需求。。如果不想同步等待调用结果可以使用[异步调用](https://github.com/weibocom/motan/wiki/zh_quickstart#异步调用)，如果业务逻辑处理比较耗时，也可以考虑在业务层面进行异步处理。

**Comment by Python-IBM** [comment]
比如下载报表，basicReferer请求超时设置了60秒，但这时数据很大，还在查询，还没返回结果，此时请求超过了60秒，client端自动端开对service的访问。不用管是用同步还是异步，都会出现请求超时。我想要的结果是请求过去了，不要一直长连接等待响应。而是的等大数据查询完毕了，就把结果响应给client端，client端再响应给浏览器下载Excel。

**Comment by Python-IBM** [comment]
调大超时不是最终的解决方案，报表的数据是不断增涨的。我当时也考虑不用rpc的这种应答方式，但逻辑都写好了，希望能在官方的框架上得到更好的解决方案。不过还是感谢官方技术人员，我根据业务场景来寻选择你说的两种方式。
