### ISSUE TITLE
motan统计日志问题？

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#71]
配置了 accessLog 属性，client 端调用了1000次接口，server端serverserviceStatsLog.log日志是： [motan-totalAccessStatistic] app: motan module: motan total_count: 0 slow_count: 0 biz_excp: 0 other_excp: 0 avg_time: 0.00ms biz_time: 0.00ms avg_tps: 0，为何server，client端的total_count一直是0呢？BUG？

**Comment by sunnights** [comment]
你好，这个是开源版本的一个bug，内部的motan默认对Server和Client都开启了AccessStatisticFilter，开源版本中暂时去掉了
你可以在AccessStatisticFilter的`@SpiMeta(name = "statistic")`后添加如下代码来设置默认开启
`@Activation(key = { MotanConstants.NODE_TYPE_SERVICE, MotanConstants.NODE_TYPE_REFERER })`
后续版本将修复该bug

**Comment by thisxulz** [comment]
好的，这个是会在0.1.2版本修复吗？

**Comment by sunnights** [comment]
会的

**Comment by thisxulz** [comment]
OK，3Q

**Comment by whatisgolang** [comment]
这个在021版本似乎还没默认打开？
