### ISSUE TITLE
Why didn't AbstractPoolClient base on io.netty.channel.pool.ChannelPool?

### ISSUE THREAD

**Issue by pifuant** [weibocom/motan#715]

**Comment by pifuant** [comment]
@rayzhang0603

**Comment by sunnights** [comment]
the motan framework shouldn't depend on specific class in netty or other application framework

**Comment by pifuant** [comment]
general pool client
但是， 这样又无形重复造轮子， 如果换种方式， AbstractPoolClient只提供抽象接口， 以及通用的接口实现， 其他交给子类去进行细节实现， 如果通过io.netty.channel.pool.ChannelPool
