### ISSUE TITLE
motan自动打开开关

### ISSUE THREAD

**Issue by woshizhouqiang** [weibocom/motan#716]
想通过监听spring 的 ContextRefreshedEvent事件， 自动打开motan 开关， 发现无效；
于是看源码， 发现 motan 的 ServiceConfigBean 也实现了ApplicationListener<ContextRefreshedEvent>
ContextRefreshedEvent事件触发 ，会执行下面的代码，注册上motan 开关的监听器
          
     MotanSwitcherUtil.registerSwitcherListener(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, new SwitcherListener() {
            @Override
            public void onValueChanged(String key, Boolean value) {
                if (key != null && value != null) {
                    if (value) {
                        available(null);
                    } else {
                        unavailable(null);
                    }
                }
            }
        });
所以自己定义的ContextRefreshedEvent 事件执行顺序必须在ServiceConfigBean之后，
但是ServiceConfigBean 没有实现 Ordered接口指定顺序， 默认的执行顺就是最后执行，
所以通过监听ContextRefreshedEvent事件打开motan 开关是无效的。

所以我觉得ServiceConfigBean 是不是可以实现Ordered, 给定一个执行顺序， 谢谢。

**Comment by rayzhang0603** [comment]
一般service会依赖一些其他前置条件，所以期望的行为是service的export工作尽量靠后进行，所以暂时不会考虑实现ordered。

motan的开关机制，目的是想要确保服务在启动完成，并进行验证、预热后在提供服务，所以并不推荐在spring上下文初始化时就注册并对外提供服务。

如果确实希望系统启动后自动打开开关提供服务，推荐在完成springcontext的初始化之后单独进行。另外，提前打开心跳开关也是可以在注册时自动生效的，可以参考AbstractRegistry.register(URL url) line 82的实现

**Comment by woshizhouqiang** [comment]
嗯嗯， 明白。 

我用的是consul 注册中心， 提前打开开关会报错。zookeeper 则不会。  
ConsulRegistry.doAvailable(URL url)line 85行。


    @Override
    protected void doAvailable(URL url) {
        if (url == null) {
            heartbeatManager.setHeartbeatOpen(true);
        } else {
            throw new UnsupportedOperationException("Command consul registry not support available by urls yet");
        }
    }

**Comment by rayzhang0603** [comment]
@woshizhouqiang 嗯，非常感谢反馈，我们会在后续版本中处理一下consul的这个问题
