### ISSUE TITLE
motan目前是否支持一个port对应多个service

### ISSUE THREAD

**Issue by flygit** [weibocom/motan#72]
版本0.1.1的demo中,没有找到一个port对应多个service的注册启动方法.
目前是否支持这个功能? 或后续版本中有没有计划支持这个功能?

**Comment by thisxulz** [comment]
可以的，需要在配置service时增加shareChannel="true"

**Comment by lordzoucl** [comment]
是否可以统一定义一个默认的port支持多个service？

**Comment by thisxulz** [comment]
Demo里面默认配置是8002，这个端口只是一个通信端口，至于是否默认port，可以自己内部去约束的

**Comment by qdaxb** [comment]
@lordzoucl 因为共享channel对service的配置有要求，需要使用相同的协议、编码等，并且有可能不同的service之间有相互影响，所以默认是不共享端口的。

**Comment by jqs1124** [comment]
@will-xlz  设置shareChannel="true"后有没有什么隐患
