### ISSUE TITLE
spring+motan，main函数启动，用注解发布不了服务

### ISSUE THREAD

**Issue by dujiaolianglong** [weibocom/motan#724]
不用springboot，用spring+motan，motan服务用注解，用main函数启动，不成功，也没抱任何错

**Comment by dujiaolianglong** [comment]
知道的帮解答下，谢谢

**Comment by sunnights** [comment]
可以参考 https://github.com/weibocom/motan/blob/master/motan-demo/motan-demo-server/src/main/java/com/weibo/motan/demo/server/AnnotationRpcServerDemo.java

**Comment by dujiaolianglong** [comment]
用注解 @MotanService  发布 服务，怎么配置多个服务组？

**Comment by dujiaolianglong** [comment]
已解决，谢谢
