### ISSUE TITLE
motan和motan2有什么区别，

### ISSUE THREAD

**Issue by dujiaolianglong** [weibocom/motan#727]
motan和motan2协议有什么区别，simple序列化和默认的hessian序列化有什么区别，
我在文档中怎么找不见这些的解释

**Comment by sunnights** [comment]
motan协议只支持java语言  
motan2协议的设计是为了支持跨语言

**Comment by dujiaolianglong** [comment]
simple序列化和默认的hessian序列化有什么区别

**Comment by sunnights** [comment]
hessian只支持java  
simple序列化支持跨语言，只支持部分数据类型
