### ISSUE TITLE
RefererCommonHandler问题

### ISSUE THREAD

**Issue by lhl4546** [weibocom/motan#728]
RefererCommonHandler中的call方法没有给DefaultRequest设置paramtersDesc，导致DefaultRpcCodec在encodeRequest时报错，报错行为169行：output.writeUTF(request.getParamtersDesc());
motan版本1.1.1

**Comment by sunnights** [comment]
RefererCommonHandler目前只支持motan2协议，主要是提供给跨语言的场景使用  
motan协议暂不支持

**Comment by lhl4546** [comment]
看这个CommonHandler的实现应该可以支持前面有人提到的泛化调用了，可以摆脱语言层面的接口限制
