### ISSUE TITLE
请问eclipse 配置文件报错

### ISSUE THREAD

**Issue by gxf1027** [weibocom/motan#731]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:motan="http://api.weibo.com/schema/motan"
	xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans-2.5.xsd
   http://api.weibo.com/schema/motan http://api.weibo.com/schema/motan.xsd">

    
    <bean id="serviceImpl" class="quickstart.FooServiceImpl" />
    
    <motan:service interface="quickstart.FooService" ref="serviceImpl" export="8002" />
</beans>

上面就是给的示例
但
eclipse 配置文件报错，
Multiple annotations found at this line:
	- cvc-complex-type.2.4.c: The matching wildcard is strict, but no declaration can be found for element 'motan:service'.
	- schema_reference.4: **Failed to read schema document 'http://api.weibo.com/schema/motan.xsd'**, because 1) could not find the document; 2) the document could not be read; 
	 3) the root element of the document is not <xsd:schema>.

请问有解决方法吗

**Comment by rayzhang0603** [comment]
motan的xsd文件在motan项目下motan-core/src/main/resources/META-INF/motan.xsd，可以在eclipse中导入这个配置文件

**Comment by gxf1027** [comment]
谢啦！
