### ISSUE TITLE
Server 如何配置 Filter 用来完成统计、并发限制等功能？

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#75]
如题,motan:service/ 里面自定义的filter属性好像没作用？
filter="com.xxx.filter.MotanFilter"

**Comment by sunnights** [comment]
你好，motan的扩展机制是通过Java的SPI机制实现的，自定义filter（如`AccessURLFilter`）需要以下几步：
1. `AccessURLFilter`扩展motan的`Filter`类实现`filter`方法
在`AccessURLFilter`类上加入以下注解
    `
    @SpiMeta(name = "url")
    @Activation()  // 目前版本需要添加Activation注解，后续版本会修复
`
2. 在项目的`resources`目录下添加`META-INF/services`包
包中添加文本文件`com.weibo.api.motan.filter.Filter`
文件内容为自定义filter的全类名`com.weibo.motan.demo.client.AccessURLFilter`
3. 配置文件中在`motan:service`或`motan:referer`中添加`filter="url"`

develop guide中会完善这些内容

**Comment by thisxulz** [comment]
好的，已配置成功，谢谢！
