### ISSUE TITLE
@MotanService导致spring MethodInterceptor 不生效

### ISSUE THREAD

**Issue by pinhon** [weibocom/motan#751]
当添加了@MotanService之后，这个类不能被spring MethodInterceptor 拦截到，这个有处理的方案吗

**Comment by rayzhang0603** [comment]
可以考虑使用filter扩展方式实现对method进行处理，参考[filter扩展](
https://github.com/weibocom/motan/wiki/zh_developguide#%E6%89%A9%E5%B1%95motan%E7%9A%84filter)
