### ISSUE TITLE
ProviderProtectedMessageRouter的请求拒绝策略

### ISSUE THREAD

**Issue by zrbcool** [weibocom/motan#755]
近期我们在线上使用motan服务时发生了拒绝请求的情况，在github中找issue及阅读源码，记录在下面链接

**ref**: [motan线程保护机制及合理设置motan配置](https://github.com/zrbcool/motan/blob/thread-issue-demo/docs/wiki/motan%E7%BA%BF%E7%A8%8B%E4%BF%9D%E6%8A%A4%E6%9C%BA%E5%88%B6%E5%8F%8A%E5%90%88%E7%90%86%E8%AE%BE%E7%BD%AEmotan%E9%85%8D%E7%BD%AE.md)

经过试验我们发现，当一个motan服务service类中只有一个方法时，拒绝策略直接返回true，而即使线程池满也没有任何报错跟异常行为，从现象上看是阻塞客户端的请求了，请问下作者，这块是如何设计考虑的，是在客户端阻塞等待了吗？如果是这样，可能会在线上导致雪崩，不知道weibo内部是怎样应对这个问题的？谢谢

**Comment by zrbcool** [comment]
自己做了些试验，初步结论如下：

- 当motan默认分配的线程池中的100个线程全忙的时候，线程池拒绝策略会抛出异常，异常被上层捕获并在当前线程中执行，而当前线程是netty4当中workerGroup，
![image](https://user-images.githubusercontent.com/11828936/45675221-6d9c9400-bb61-11e8-8c98-cf1a15835f05.png)

- 在motan当中创建workerGroup时使用了无参的构造函数，最终会根据系统可用cpu核数*2创建workerGroup，我当前的计算机是12核，所以这个数字是24
![image](https://user-images.githubusercontent.com/11828936/45675242-78efbf80-bb61-11e8-9a1f-083f87f3a051.png)

所以问题变成了，
当单方法的service并发量超过配置的motan线程池最大数，则线程池的拒绝策略会向上抛出异常，而异常在IO线程中（Netty4的workerGroup）捕获并处理，这里在捕获逻辑中依然调用了processMessage(ctx, (NettyMessage) msg)，但是是在workerGroup线程池当中执行，而这个线程池只有24个（与运行环境配置有关cpu*2）
问题是：
当workerGroup全忙的时候，是不是motan服务已经失去了处理请求的能力，表现是什么？

**Comment by rayzhang0603** [comment]
`ProviderProtectedMessageRouter` 这个类的设计初衷是减少同端口下不同服务、不同方法相互之间的影响，防止部分方法将server端worker线程池占满，因此只有一个方法时，这个类中的保护机制不生效。

只有一个方法时，最终worker线程池的reject会生效。

一般服务提供方和调用方都需要有针对自身的保护机制，例如client端的熔断、server端的限流，两种策略可以结合使用

**Comment by zrbcool** [comment]
已经切换到1.1.1版本，看到代码已经调整为：
![image](https://user-images.githubusercontent.com/11828936/45680842-9414fc00-bb6e-11e8-83d9-a0d776ac5784.png)
目前没有疑问了， 十分感谢！
