### ISSUE TITLE
本地订阅远端服务器上的生产者

### ISSUE THREAD

**Issue by ttrrrr** [weibocom/motan#759]
本地开发环境订阅注册在远端服务器zookeeper上的服务，会报错error_message: NettyChannel connect to server timeout。然后url变成了远端服务器的内网地址了，然而在远端发布生产者服务的时候是指定了公网ip的zookeeper ip+port。挺急的在线等

**Comment by ttrrrr** [comment]
服务器环境centos 7.4 防火墙也是关闭的

**Comment by sunnights** [comment]
可以参考 #214，配置host将外网ip注册到zk上

**Comment by ttrrrr** [comment]
非常感谢解决了我的问题
