### ISSUE TITLE
更新架包注册zookeeper问题？

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#76]
0.0.1 zookeeper 注册服务没有问题，换成0.1.1以后，注册不上了，BUG吗？

**Comment by sunnights** [comment]
能给出具体出错信息吗

**Comment by thisxulz** [comment]
没有报错，但是motan-manager查询页面，没有查询到注册信息，也确实不可用，同一个server服务，只是换了架包版本。。

**Comment by sunnights** [comment]
新版本中加入了服务的优雅停机特性，
请参考 [优雅的停止服务](https://github.com/weibocom/motan/wiki/zh_userguide#%E4%BC%98%E9%9B%85%E7%9A%84%E5%81%9C%E6%AD%A2%E6%9C%8D%E5%8A%A1)，在Server启动后调用开关来使Service正常对外提供服务

**Comment by thisxulz** [comment]
。。。。就是需要手动开启是吗？确实行了。。
