### ISSUE TITLE
类型转换错误

### ISSUE THREAD

**Issue by allenwtl** [weibocom/motan#763]
java.lang.ClassCastException: 
hprose.util.LinkedCaseInsensitiveMap cannot be cast to com.lock.common.domain.MemberDoorLock
序列化协议是  serialization="hprose" 
能够正确返回list，但是遍历list的时候for(A a:list) 就报错

**Comment by allenwtl** [comment]
motan-extension  version  1.1.1
motan-core   RELEASE  
@sunnights   大佬帮忙解决一下

**Comment by andot** [comment]
com.lock.common.domain.MemberDoorLock 这个类型你没注册，反序列化时找不到该类，被反序列化为map了。你把这个类型注册一下就好了。

**Comment by allenwtl** [comment]
难道 我自己定义的所有业务类  都要人工去进行注册吗

**Comment by allenwtl** [comment]
关键是 查询单个 就可以  返回的是 MemberDoorLock

**Comment by allenwtl** [comment]
主要是motan 没有主动提供这样 自动注册的功能 还要自己写

**Comment by allenwtl** [comment]
为啥不能统一框架做了 还要自己一个一个写

**Comment by Bodil-X** [comment]
最后是怎么解决的，不会所有需要序列化的类都手动调用一遍

**Comment by Bodil-X** [comment]
最后是怎么解决的，不会所有泛型需要序列化的类都要调用一遍```HproseClassManager.register()``` 方法吧?
