### ISSUE TITLE
motan还有其他序列化么？

### ISSUE THREAD

**Issue by 89333367** [weibocom/motan#768]
目前知道使用下面方式，切换序列化类
```
<dependency>
  <groupId>com.weibo</groupId>
  <artifactId>serialization-extension</artifactId>
  <version>1.1.1</version>
</dependency>
```
```
<motan:protocol id="***" name="motan" serialization="hprose" ....
```
还想知道，是否支持fst序列化？
还有
```
<motan:protocol 
```
这个标签是否只在服务提供者这边配置，服务调用者那边不需要这个标签了吧？就算配置了也不生效？

**Comment by rayzhang0603** [comment]
1、目前不支持fst序列化，欢迎PR～
2、protocol标签client端、server端都需要配置。server端一般配置工作线程数等参数，client端一般配置最大、最小链接数以及HA、LB等，可以参考[配置说明](
https://github.com/weibocom/motan/wiki/zh_userguide#%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)

**Comment by 89333367** [comment]
> 1、目前不支持fst序列化，欢迎PR～
> 2、protocol标签client端、server端都需要配置。server端一般配置工作线程数等参数，client端一般配置最大、最小链接数以及HA、LB等，可以参考[配置说明](https://github.com/weibocom/motan/wiki/zh_userguide#%E9%85%8D%E7%BD%AE%E8%AF%B4%E6%98%8E)

那么问题来了，如果服务端，我配置了
```
<motan:protocol id="***" name="motan" serialization="hessian2" ....
```
客户端配置了
```
<motan:protocol id="***" name="motan" serialization="hprose" ....
```
序列化方式不一样。那么能正常使用么？
或者，服务端用的是1.1.1版本，并且是netty4的，客户端由于以前有老的项目，使用的是0.3的版本，netty是3版本，能正常使用么？

**Comment by rayzhang0603** [comment]
1、序列化不一致时显然不能

2、motan的交互只跟协议、序列化、service的version等相关，不同版本之间、不同transport实现（netty3、netty4）之间都可以正常使用。

**Comment by 89333367** [comment]
> 1、序列化不一致时显然不能
> 
> 2、motan的交互只跟协议、序列化、service的version等相关，不同版本之间、不同transport实现（netty3、netty4）之间都可以正常使用。

多谢耐心回答。
