### ISSUE TITLE
关于流量切换

### ISSUE THREAD

**Issue by winner1207** [weibocom/motan#785]
目前业务需要将client调用group1失败后，自动调用group2的服务，流量切换目前只能在manager手动配置，是否可以通过filter的方式让程序自动切换？

**Comment by rayzhang0603** [comment]
目前的filter机制无法实现这个功能，从haStrategy部分进行扩展应该可以实现类似功能。

我们有计划增加backupGroup这样的功能，类似于主从的自动切换，来解决你提到的问题，可以关注后续的release。

有什么好的建议欢迎讨论。

**Comment by winner1207** [comment]
追问一下，如何在haStrategy自定义扩展中获取指定group的Referer呢？

**Comment by rayzhang0603** [comment]
@winner1207 我们评估了一下，这个需求很难通过简单扩展解决。应该会涉及到增加backupGroup的配置项、处理多分组referers的LB等多处修改，建议等官方实现。

**Comment by winner1207** [comment]
好的，感谢回复

**Comment by winner1207** [comment]
@rayzhang0603 可以临时用java代码初始化一组备用组的client，然后使用referConfig来调用，贴上代码
<pre>
/**
 * Created by wangyitao on 2019/1/21.
 * 调用motanChatService扩展可用性策略：备用组，基于默认 failover【失效切换】改造
 */
@SpiMeta(name = "motanChatServiceBackup")
public class MotanChatServiceBackupHaStrategy<T> extends FailoverHaStrategy<T> {

    private static Logger logger = Logger.getLogger(MotanChatServiceBackupHaStrategy.class);

    @Override
    public Response call(Request request, LoadBalance<T> loadBalance) {
        Response response = null;
        try {
            response = super.call(request, loadBalance);
            return response;
        } catch (MotanServiceException ex1) {
            //捕捉到异常后，判断是否触发熔断机制，做降级处理：此处的降级策略为由替补组执行
            logger.error("ready to switch chat backup group ! request:" + EchatJsonUtil.toJSON(request));
            try {
                RefererConfig<MotanChatService> refererConfig = ChatBackupRpcUtil.getRefererConfig();
                if (refererConfig == null) {
                    throw new MotanServiceException("motan chat backup group is null, switch error ! ");
                }
                List<ClusterSupport<MotanChatService>> clusterSupports = refererConfig.getClusterSupports();
                if (clusterSupports == null || clusterSupports.size() == 0) {
                    throw new MotanServiceException("motan chat backup clusterSupports is null, switch error ! ");
                }
                Cluster<MotanChatService> cluster = clusterSupports.get(0).getCluster();
                if (cluster == null) {
                    throw new MotanServiceException("motan chat backup cluster is null, switch error ! ");
                }
                response = cluster.call(request);
                return response;
            } catch (MotanServiceException ex2) {
                throw ex2;
            }
        } catch (Exception e) {
            throw e;
        }
    }
}
</pre>

**Comment by rayzhang0603** [comment]
@winner1207 这个方案对特定的场景我觉得挺好。

这种方式通用性略低，不太适合框架中集成，但对我们实现思路会有所启发，很赞～
