### ISSUE TITLE
filter属性可以配置多个吗？

### ISSUE THREAD

**Issue by fallsea** [weibocom/motan#787]
我有2个自定义的`opentracing`

`filter=opentracing,sysparameter`，配置后，启动没有任何异常，就是客户端无法服务端接口成功，改成配置一个就没有问题了，请问这个怎么解决呢？

**Comment by rayzhang0603** [comment]
filter是可以配置多个的，而且大部分生产场景都是使用多个filter。

你可以debug调试一下这两个filter执行的情况，确认

1、两个filter的filter(final Caller<?> caller, final Request request)方法是否都执行了。

2、filter处理完成后，是否调用了caller.call(request)，只有调用这个方法才会真正执行调用请求。

**Comment by fallsea** [comment]
@rayzhang0603 非常感谢，已经解决了 ，是因为执行第一个`filter` ，返回的`Response`对象为空导致第二个调用失败了。
