### ISSUE TITLE
motan消费端部署在tomcat中，无法正常shutdown tomcat

### ISSUE THREAD

**Issue by feilaoda** [weibocom/motan#79]
执行tomcat的shutdown.sh，无法正常关闭tomcat，只能kill进程。有什么办法吗？

**Comment by syndory** [comment]
有没有错误提示信息什么的？

**Comment by thisxulz** [comment]
这应该是tomcat的问题吧？

**Comment by sunnights** [comment]
你好，motan中使用了ScheduledExecutorService线程池，其中的一些线程在后台一直运行来做一些辅助工作，执行tomcat的shutdown脚本时，无法关闭这些线程，因此导致tomcat无法正常关闭

**Comment by feilaoda** [comment]
@sunnights  我研究一下看看能不能关闭这些线程池？

**Comment by qdaxb** [comment]
@feilaoda 这确实是当前版本的一个问题，如果解决了的话欢迎提交pr。

**Comment by mikeqian** [comment]
是不是可以提供一个stop方法，执行的时候把所有相关的线程池都关掉，前提是这些线程池都注册到了一个统一的坑里面。

**Comment by huangruisheng** [comment]
出现线程池的地方：
 static {
        Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            public void run() {
                LoggerUtil.info("Run shutdown RefererSupports scheduledExecutor now");
                scheduledExecutor.shutdown();
            }
        }, "RefererSupports-scheduledExecutor"));
    }

Netty出现的地方  
     Runtime.getRuntime().addShutdownHook(new Thread(new Runnable() {
            public void run() {
                LoggerUtil.info("Run shutdown NettyClient scheduledExecutor now");
                channelFactory.releaseExternalResources();
            }
        }, "NettyClient-scheduledExecutor"));
    }

**Comment by ghost** [comment]
mark.
用Phantom References可以实现吗?

**Comment by haiger** [comment]
Phantom References只在GC的时候才有用。

**Comment by misselvexu** [comment]
blame thread pool ~

**Comment by rayzhang0603** [comment]
motan0.3.1版本提供了com.weibo.api.motan.closable.ShutDownHookListener，在web.xml中添加ShutDownHookListener即可

**Comment by wangguowu** [comment]
web项目中集成了motan，关闭tomcat的时候要手动点两次Terminal才能彻底关掉，感觉第一次是关tomcat，第二次是关长连接？我用的是idea。ShutDownHookListener加到web.xml中，debug观察也被执行了
