### ISSUE TITLE
服务端断链后，抛出的连接超时异常可以处理吗？

### ISSUE THREAD

**Issue by hengyuboy** [weibocom/motan#795]

**Comment by hengyuboy** [comment]
客户端可以主动断开链接吗？

**Comment by rayzhang0603** [comment]
client超时异常时会自动断链

**Comment by hengyuboy** [comment]
可以主动断开链接吗？

**Comment by hengyuboy** [comment]
> client超时异常时会自动断链

可以主动断开链接吗？

**Comment by rayzhang0603** [comment]
主动断开是什么场景？

**Comment by hengyuboy** [comment]
> 主动断开是什么场景？

我这边客户端在一段时间没有心跳后，就会主动断开通信，接入其他的客户端

**Comment by hengyuboy** [comment]
> > 主动断开是什么场景？
> 
> 我这边客户端在一段时间没有心跳后，就会主动断开通信，接入其他的客户端

是服务端，重新接入一个服务端

**Comment by hengyuboy** [comment]
> 直接调用client的close方法不就断开了？

有相应的demo吗？

**Comment by hengyuboy** [comment]
> 你要是参照MotanApiClientDemo创建的client，可以通过`motanDemoServiceReferer.destroy();`销毁client

好的，明白了
