### ISSUE TITLE
请问 motan能否支持sleuth框架？

### ISSUE THREAD

**Issue by xlorne** [weibocom/motan#798]
我们打算支持motan的分布式事务控制，我们的分布式框架上需要rpc框架能够支持sleuth框架. 🙂

**Comment by xlorne** [comment]
https://cloud.spring.io/spring-cloud-sleuth/single/spring-cloud-sleuth.html

**Comment by xlorne** [comment]
在openzipkin下没有找到motan的实现 
https://github.com/openzipkin/brave/tree/master/instrumentation

**Comment by rayzhang0603** [comment]
motan支持Opentracing，满足OT规范的tracer都可以接入，可以参考[Opentracing扩展](
https://github.com/weibocom/motan/wiki/zh_quickstart#%E4%BD%BF%E7%94%A8opentracing)

也可以参考motan opentracing扩展的实现机制，通过spi扩展来定制filter实现，可以参考[扩展filter](
https://github.com/weibocom/motan/wiki/zh_developguide#%E6%89%A9%E5%B1%95motan%E7%9A%84filter)

**Comment by xlorne** [comment]
OK    那我们来尝试一下吧。感谢
