### ISSUE TITLE
@MotanAsync 问题

### ISSUE THREAD

**Issue by ywf4026** [weibocom/motan#799]
我看官方文档关于异步化调用的使用是这样的：
package quickstart;

@MotanAsync
public interface FooService {
    public String hello(String name);
}

一般api jar包都是服务提供方提供的，如果要加上这个注解的话，是不是要让服务方的jar包升级？
如果服务方暂时给不了升级包，那我还有其他方式来使用异步调用吗？

我看dubbo的异步调用方式不需要这么做，还是跟同步调用使用一样。

**Comment by rayzhang0603** [comment]
注解是为了自动生成异步调用的接口，如果不使用注解，可以在client端自己定义一个增加`Async`后缀的接口，referer配置时直接使用这个异步接口就可以了。

自动生成的异步接口类扩展自原接口，对所有原声明的方法名增加`Async`后缀，返回值改为`com.weibo.api.motan.rpc.ResponseFuture`， 例如demo中的`MotanDemoService`接口通过注解自动生成的异步接口如下：

```java
public interface MotanDemoServiceAsync extends MotanDemoService {
  ResponseFuture helloAsync(String name);

  ResponseFuture renameAsync(User user, String name);
}
```

client端的配置可以参考demo-client模块中的`motan_demo_async_client.xml`

**Comment by ywf4026** [comment]
> motan_demo_async_client


    <motan:referer id="motanDemoReferer" directUrl="127.0.0.1:8002"
                   interface="com.xxx.motan.demo.service.MotanDemoServiceAsync"
                   connectTimeout="300" requestTimeout="300" basicReferer="motantestClientBasicConfig"/>

这样会有一个问题：
假设服务方的接口的所在包是这个：com.weibo.motan.demo.service
我自定义一个MotanDemoServiceAsync所在的包肯定不是上面那个，比如是这个com.xxx.motan.demo.service

我测试发现，com.xxx.motan.demo.service这个服务在注册中心肯定是找不到的

这个问题怎么解决？
