### ISSUE TITLE
开发文档会包含一些什么内容呢！预计什么时候可以见到？ 核心模块/功能的注释会有吗？

### ISSUE THREAD

**Issue by jspp** [weibocom/motan#8]
期待

**Comment by qdaxb** [comment]
主要包括开发环境搭建、参与开发的流程和一些注意事项，不会涉及太多代码逻辑。

**Comment by jspp** [comment]
ok
也希望这个项目可以长期维护和更新！

**Comment by happygao521** [comment]
希望motan项目技术上不要太精简了！ netty还用的3.x版本呀

happy.gaoxingkun

发件人： 欧阳
发送时间： 2016-04-26 10:23
收件人： weibocom/motan
主题： Re: [weibocom/motan] 开发文档会包含一些什么内容呢！预计什么时候可以见到？ 核心模块/功能的注释会有吗？ (#8)
Closed #8.
