### ISSUE TITLE
自定义filter的spi不生效

### ISSUE THREAD

**Issue by EE6** [weibocom/motan#805]
按照文档实现一个filter的spi扩展，没有生效

**Comment by EE6** [comment]
@Spi(scope = Scope.SINGLETON)
@SpiMeta(name = "logtraceidrefer")
@Activation(key = {MotanConstants.NODE_TYPE_REFERER })
public class logTraceIdMotanSpi implements Filter{

    protected Logger logger = LoggerFactory.getLogger(this.getClass());

    @Override
    public Response filter(Caller<?> caller, Request request) {
        RpcContext rpcContext = RpcContext.getContext();
        rpcContext.setClientRequestId(MDC.get("log_trace_id"));

        logger.info("LogTraceIdFilter clientRequestId: " + MDC.get("log_trace_id"));
        return caller.call(request);
    }
}




@Spi(scope = Scope.SINGLETON)  
@SpiMeta(name = "logtraceidservice") 
@Activation(key = { MotanConstants.NODE_TYPE_SERVICE})
public class LogTraceIdFilter implements Filter{

    protected Logger logger = LoggerFactory.getLogger(this.getClass());

    @Override
    public Response filter(Caller<?> caller, Request request) {
        RpcContext rpcContext = RpcContext.getContext();
        String clientRequestId = rpcContext.getClientRequestId();
        logger.info("LogTraceIdFilter clientRequestId: " + clientRequestId);
        MDC.put("log_trace_id", clientRequestId);
        return caller.call(request);
    }
}

**Comment by rayzhang0603** [comment]
可以确认一下:
- 是否在项目中添加了` ${classpath}/META-INF/services/com.weibo.api.motan.filter.Filter`文件，文件中是否添加了这两个类的类全名，例如`**.**.LogTraceIdFilter`
- referer配置中是否配置了`filter="logtraceidrefer"`，service配置中是否配置了`filter="logtraceidservice"`

**Comment by EE6** [comment]
> 可以确认一下:
> 
> * 是否在项目中添加了` ${classpath}/META-INF/services/com.weibo.api.motan.filter.Filter`文件，文件中是否添加了这两个类的类全名，例如`**.**.LogTraceIdFilter`
> * referer配置中是否配置了`filter="logtraceidrefer"`，service配置中是否配置了`filter="logtraceidservice"`

项目中添加了${classpath}/META-INF/services/com.weibo.api.motan.filter.Filter 文件中也添加了类全名，refer中也配置了name.
这两个类在两个不同的项目上，在项目A的LogTraceIdFilterA中把值放入RpcContext，在项目B的LogTraceIdFilterB中拿到RpcContext的值是否可行？

**Comment by rayzhang0603** [comment]
你可以先确定filter是否被加载了。

RPCContext是本地传递信息使用的，不是针对远程。client侧要这样设置id才可以被远程server获取到`request.setAttachment(URLParamType.requestIdFromClient.getName(), "xxxx");`

**Comment by EE6** [comment]
> 你可以先确定filter是否被加载了。
> 
> RPCContext是本地传递信息使用的，不是针对远程。client侧要这样设置id才可以被远程server获取到`request.setAttachment(URLParamType.requestIdFromClient.getName(), "xxxx");`

（谢谢告知远程service获取数据的正确方法）

Filter接口的实现类里的静态代码可以被加载，但是filter(Caller<?> caller, Request request)方法里的代码却没有执行。目前还找不到原因

**Comment by rayzhang0603** [comment]
可以断点一下`ProtocolFilterDecorator`类的`getFilters`方法，先看看对应的service是否filter 名称配置的是否正确，对应的spi是否被正确加载。

如果正确加载了filter的话，在断点调试你实现的filter的`filter`方法看看

**Comment by EE6** [comment]
@rayzhang0603  谢谢回复，问题已解决。
原因是${classpath}/META-INF/services/com.weibo.api.motan.filter.Filter 中的${classpath}未配置正确。
