### ISSUE TITLE
关于 优雅的停止服务 问题？

### ISSUE THREAD

**Issue by thisxulz** [weibocom/motan#81]
你好，关于 client 端 和 server 端服务的优雅停止，目前是只能自己去开发一个调度系统吧？官方是否考虑在后台管理中加入这部分功能呢？感觉还是比较有必要的

**Comment by qdaxb** [comment]
简单的优雅停止可以通过暴露http接口+脚本或者其它方式实现，管理后台近期的方向是服务监控、流量调度以及监控，未来可以考虑增加控制节点状态，不过仅仅单纯控制优雅停止似乎意义不大，仍然需要搭配一个额外的调度系统来实现服务的代码更新、上下线等等。

能详细描述一下具体的场景吗？

**Comment by thisxulz** [comment]
就是希望多个业务系统上下线接口的时候能够由管理后台去控制，业务系统正常注册上线接口，管理后台可以批准这个接口正常使用，或者关闭使用，大概就是这样，不过确实服务监控和统计目前更为重要些
