### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by lhl4546** [weibocom/motan#812]
AnnotationBean.postProcessBeforeInitialization()方法有2个try catch，建议将Exception改为Throwable，有些rpc接口导致的NoClassDefFoundError这里捕获不到，从而加大了问题排查难度，如果这里能捕获到这个异常的话则能直接定位到具体是哪个rpc接口导致的错误

**Comment by rayzhang0603** [comment]
嗯，这样异常信息会比spring打印出的异常栈更精准一些，后续会进行调整。
