### ISSUE TITLE
motan是否支持异步调用，有示例代码么？

### ISSUE THREAD

**Issue by valleylord** [weibocom/motan#82]
看motan的配置手册，似乎是支持异步调用的，有示例代码么？谢谢

**Comment by qdaxb** [comment]
传输层是异步的，不需要配置。但是业务调用的代码是阻塞的。

比如说`hello.say("world");`这个方法耗时200ms，那么通过motan做了rpc化之后，client的调用代码也会耗费200ms（不考虑网络开销）；但当遇到网络超时等情况时，client会在超时之后抛出异常终止请求，而不是一直阻塞。

我们也在考虑如何更优雅的实现业务代码调用client方法的异步化，如果有想法欢迎交流。

**Comment by valleylord** [comment]
我想你们一定研究过dubbo，dubbo是这样的写法，

```
                demoService.hello("world");
                fooFuture = RpcContext.getContext().getFuture();
```

motan关于这个问题有什么考虑么？

**Comment by qdaxb** [comment]
@valleylord see #112
