### ISSUE TITLE
单向请求

### ISSUE THREAD

**Issue by lhl4546** [weibocom/motan#828]
motan会不会考虑支持单向请求，请求发送出去之后不需要等待应答

**Comment by wingyiu** [comment]
@lhl4546 用async?得到Future后不get()？

**Comment by lhl4546** [comment]
这么巧?

**Comment by lhl4546** [comment]
请求-应答涉及许多步骤，用async然后不get只是让调用者看起来没接收应答，实际上服务提供方仍要发送应答，调用方也仍要接收并处理应答

**Comment by rayzhang0603** [comment]
单向请求会在motan2协议中实现，motan2协议已经预留了单向请求的标记位。预计会在之后的2个小版本中支持此功能。
