### ISSUE TITLE
Netty4 吞吐量优先（Netty4 Throughput optimization）

### ISSUE THREAD

**Issue by single-wolf** [weibocom/motan#835]
目前 com.weibo.api.motan.transport.netty4.NettyServer 在 ChannelHandler 中 都是使用writeAndFlush ，这在 netty4 已被证明影响吞吐量的方法 See [https://github.com/netty/netty/issues/1759](https://github.com/netty/netty/issues/1759) and [https://github.com/netty/netty/issues/5152](https://github.com/netty/netty/issues/5152)
是否可以考虑加 吞吐量优先可选配置，结合 FlushConsolidationHandler 实现？

**Comment by single-wolf** [comment]
在自己PC跑了下 motan-benchmark ，以下对比可能稍有误差（The result of benchmarks running with my PC ）
### motan.transport.netty

| 并发数 | 测试场景  | 平均TPS | 平均响应时间(ms) |
|--------|-----------|---------|--------------| 
| concurrents | case  | avg TPS | avg time(ms) |
| 10     | Empty     | 10366   | 0.964        |
| 10     | Pojo      | 9597    | 1.41         |
| 10     | 1KString  | 9616    | 1.039        |
| 10     | 10KString | 4420    | 2.261        |
### motan.transport.netty4 （awesome）
| 并发数 | 测试场景  | 平均TPS | 平均响应时间(ms) |
|--------|-----------|---------|--------------| 
| concurrents | case  | avg TPS | avg time(ms) |
| 10     | Empty     | 16016   | 0.624        |
| 10     | Pojo      | 14070   | 0.71         |
| 10     | 1KString  | 13747   | 0.727        |
| 10     | 10KString | 4537    | 2.203        |
### motan.transport.netty4 +NettyServer addLast(FlushConsolidationHandler)
| 并发数 | 测试场景  | 平均TPS | 平均响应时间(ms) |
|--------|-----------|---------|--------------| 
| concurrents | case  | avg TPS | avg time(ms) |
| 10     | Empty     | 16574   | 0.603        |
| 10     | Pojo      | 14919   | 0.669        |
| 10     | 1KString  | 14674   | 0.681        |
| 10     | 10KString | 4453    | 2.244        |
### motan.transport.netty4 +NettyServer addLast(FlushConsolidationHandler) + NettyClient addLast(FlushConsolidationHandler)
| 并发数 | 测试场景  | 平均TPS | 平均响应时间(ms) |
|--------|-----------|---------|--------------| 
| concurrents | case  | avg TPS | avg time(ms) |
| 10     | Empty     | 19451   | 0.513        |
| 10     | Pojo      | 16634   | 0.6          |
| 10     | 1KString  | 14694   | 0.68         |
| 10     | 10KString | 4538    | 2.202        |

上述可能存在误差，望有环境能帮忙跑一个更准确的（Expecting more accurate results）

**Comment by sunnights** [comment]
感谢反馈！  
RPC场景中一般会优先考虑低延迟
吞吐量优先的机制我们后续会根据压测结果，考虑在netty4的版本中增加相关扩展配置
