### ISSUE TITLE
请问下使用注解方式配置后，在客户端通过@MotanReferer注入服务时，注解里面需要配置的属性有没有地方可以做个全局的配置？

### ISSUE THREAD

**Issue by fuyangrong** [weibocom/motan#838]
`@MotanReferer(basicReferer = "dbMotanClientBasicConfig", group = "dbservice", directUrl = "127.0.0.1:8002")
    private UpmsUserService userService;`
basicReferer 、group 、directUrl 这三个属性有地方可以做全局配置吗，不然每次注入UpmsUserService服务的时候都要重复写一遍，后期不好修改。

**Comment by rayzhang0603** [comment]
motan的配置目前都是service维度的，暂时没有全局配置。

这种情况一般都是把固定配置放在basicrefer中，例如group等信息，这样只需要修改对应的basicrefer就可以了。

另外，directurl不是basicrefer的属性，一般只在调试等场景使用，不建议线上使用。

**Comment by fuyangrong** [comment]
哦哦，明白了。我看文档上注解方式配置的例子上这么配置的，还以为directUrl也是必须配置的。我用了zookeeper注册中心，不是直连。感谢回复！
