### ISSUE TITLE
motan 对 gRPC 的支持

### ISSUE THREAD

**Issue by arjenzhou** [weibocom/motan#840]
看了 example 的代码，似乎 motan 没有对 gRPC 进行封装，与 gRPC 官方给出的差不多，只是多了一个 Spring 加载的过程。

请问 motan 是只能以这种方式使用 gRPC 吗？今后有没有封装的打算？

**Comment by rayzhang0603** [comment]
motan对grpc的支持主要是集成motan的服务发现与治理功能（motan的负载均衡、高可用、filter机制等），方便使用motan的服务与已存在的grpc服务之间打通。所以在client和server的使用上仍然保持grpc service定义的方式。我个人觉得这种方式还可以，暂时还没有进一步封装的计划。

当然，也非常欢迎提供更好的封装思路或者方案，大家一同探讨。

**Comment by arjenzhou** [comment]
@rayzhang0603 
我发现 [GrpcClientDemo](https://github.com/weibocom/motan/blob/master/motan-demo/motan-demo-client/src/main/java/com/weibo/motan/demo/client/GrpcClientDemo.java) 没有依赖于 [GrpcClient](https://github.com/weibocom/motan/blob/master/motan-extension/protocol-extension/motan-protocol-grpc/src/main/java/com/weibo/api/motan/protocol/grpc/GrpcClient.java)，请问为什么没有这么做？
