### ISSUE TITLE
motan服务停止后，zookeeper 需要30s后才从/server 节点删除注册信息

### ISSUE THREAD

**Issue by cqhaohao** [weibocom/motan#844]
问题：motan服务停止后，zookeeper 需要30s后才从/server 节点删除注册信息

是否可以当服务停止后立即删除zookeeper的服务注册节点？

**Comment by rayzhang0603** [comment]
如果直接停止服务的话，zk的session失效时才会移除节点，可以设置registry的registrySessionTimeout参数来调整。

也可以试一下server端停止服务前先关闭心跳开关

    MotanSwitcherUtil.setSwitcherValue(MotanConstants.REGISTRY_HEARTBEAT_SWITCHER, false);

使用zk作为注册中心时，关闭心跳会立即从unavailableServer中删除节点。

**Comment by cqhaohao** [comment]
非常感谢
