### ISSUE TITLE
关于流量切换  ps 有群号吗？

### ISSUE THREAD

**Issue by vwyuheng** [weibocom/motan#85]
有关流量切换我想请教下就是，我把流量从a分组切换到b分组，但是我客户端配置的是a分组，流量怎么会能调过去呢？能否详细说明下这个流量切换究竟切换这块，跟客户端服务端配置的group有什么样的关联？

**Comment by sunnights** [comment]
流量切换是在Client端进行的，Client在启动时除了向注册中心订阅其所在group下的正常服务节点（Server），还订阅了group下的Command信息，在后台设置的指令信息就是修改注册中心中的对应group下的Command信息
Client端收到指令修改通知后，会触发指令解析流程，若匹配流量切换条件，则获取指令中的目标流量分组列表，并逐个订阅对应group下的Server（即b分组下的Server列表）
当新分组中的Server节点变更时，Client便会收到流量切换后的节点列表（包括b分组下的Server节点），然后再根据负载均衡策略选择其中一个节点发起服务调用

**Comment by vwyuheng** [comment]
比如 ，我配置 \* to ip的话是否就是 所有的流量都打到这个指定的ip上吗？  我试了下好像没有生效

**Comment by sunnights** [comment]
路由规则首先要满足流量切换配置的`分组group`和`服务Service`条件，
Client收到新的节点列表后，会逐个判断Server的ip是否符合路由规则，如果不符合，会将节点剔除掉

**Comment by vwyuheng** [comment]
@sunnights 这个怎么使用呢，我试了下 还是无法生效

**Comment by sunnights** [comment]
举个例子，`aaa`分组下有`10.0.0.1:8001`节点提供`demoService`服务，`bbb`分组下有`10.0.0.2:8001` `10.0.0.3:8001`节点提供`demoService`服务，现在Client端`10.0.0.1`配置的是`aaa`分组，正常调用的话是调用`10.0.0.1:8001`

现在想将aaa分组中所有服务流量的50%调到bbb分组，在流量切换中如下配置：
1. 来源流量：RPC分组（`aaa`），服务（`*`）
2. 流量去向：RPC分组（`aaa` `bbb`），权重分配（`1` `1`）
3. 路由规则：不需要配置
确认后即可完成流量切换，此时Client会调用的Server有`10.0.0.1:8001` `10.0.0.2:8001` `10.0.0.3:8001`

若不想将流量调到`10.0.0.3`机器上，则可在`路由规则`界面中输入`* to !10.0.0.3`，此时Client会调用的Server有`10.0.0.1:8001` `10.0.0.2:8001`

另外，若有多条指令符合匹配条件，默认只生效匹配的第一条规则

**Comment by sunnights** [comment]
额，忘了说了，流量切换功能需要注册中心支持，目前版本的zookeeper还不支持，请关注PR #49

**Comment by vwyuheng** [comment]
哈哈，我说怎么回事，我就是按照你说的场景测试的，不好使

**Comment by vwyuheng** [comment]
@sunnights  目前版本的zk 是说zookeeper的版本不支持，还是说开源的motan的版本不支持，指令切换注册中心修改成consul就可以吗？

**Comment by sunnights** [comment]
@vwyuheng 开源的motan不支持，下周新版本上线后zk和consul会支持流量切换相关的功能

**Comment by vwyuheng** [comment]
好的，感谢您的回答 @sunnights
