### ISSUE TITLE
failover+activeWeight 失败切换的时机问题

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#853]
半个月前，我测试failover+activeWeight 当节点失效会立即进行切换 而轮询因为zk中的数据session时间后会删除 导致期间内 请求还是被轮询到失效节点。
但刚才本地开启不同线程模拟多节点发现failover+activeWeight的失效切换也会在一段时间内向失效节点发请求，待zk数据删除后切换成功。
请问为什么会如此？效果不同的原因是什么？

**Comment by rayzhang0603** [comment]
首先节点失效机制跟LB没有关系，不论是activeWeight还是轮询行为都是一样的。

服务节点失效跟两个因素有关，一个是注册中心，只要从注册中心下掉了server节点，client都不会在调用；另一个是自动失效机制，这个机制是为了防止虽然server节点在注册中心列表，但实际已经无法使用的场景，其实是一种应急的保护策略（server节点突然宕机、断网等）。

触发节点失效机制的条件是同一个节点连续请求失败超过10次，之后的请求就不会在发给这个server节点，同时会启动对这个server节点的心跳（非业务请求，不影响服务），当心跳成功后会恢复对这个server节点的业务调用。

一般服务正常下线的流程，是在server节点还可以提供服务的时候，先关闭心跳开关，这样server节点会从注册中心摘除，给client端留一定缓冲时间，等server端不再有请求流量时，然后在下线server节点。

**Comment by back-zhao** [comment]
1、LB里的对server的isAvailable 的判断 会过滤失效节点么？server还要失效10个请求？
2、activeWeight时 异常后的重试请求 算server10个请求的计数么

**Comment by rayzhang0603** [comment]
1、会过滤失效节点。但节点是先失败了10个请求，才会被标记为失效节点的
2、同一个节点，只要有业务请求失败就会计数，有业务请求成功就会清零。不过重试是选择其他节点重试（除非就一个server节点）

重要的一点，节点失效机制只是为了应对突发的链路层问题，不是常态业务请求需要依赖的机制。在一个节点突然宕机的情况下，请求失败是在所难免的，这个机制不是为了保证不失败，而是为了减轻异常发生后的后果。

**Comment by back-zhao** [comment]
明白了！感谢！

**Comment by back-zhao** [comment]
最后有个疑问，当重试次数设置为10次，类似这种想法，保证请求不丢失，会有什么弊端么

**Comment by rayzhang0603** [comment]
没有这个必要，连续失败10次是针对一个server节点的，而重试会重试到不同节点，一般重复2次就够了，除非机房故障，否则server节点也不应该很多台同时宕掉。

重试次数太多在某些场景下（server端业务耗时陡增）可能会产生巨大的雪崩效应，不建议超过2次

**Comment by back-zhao** [comment]
ok,谢谢
