### ISSUE TITLE
建个QQ交流群208291449(放这里可能不太合适)

### ISSUE THREAD

**Issue by feilaoda** [weibocom/motan#86]
准备在公司的产品中使用motan，希望有更多的人一起交流
放这里可能不太合适，可以随时删掉这个issue。

**Comment by Ive4** [comment]
这个暂时在生产中使用不太合适，还是等完善一些在使用吧，看了下使用的风格和dubbo类似，所以暂时可以使用duboo，之后再切换回来也不会太痛，我是想使用这个来对接thrift
