### ISSUE TITLE
请问com.weibo.api.motan.rpc.URL里的numbers这个成员变量的作用是什么呢

### ISSUE THREAD

**Issue by wzy2008a** [weibocom/motan#864]
我看了下代码，只要long、int类型的参数都放到了numbers里，这样做的目的是否只是从性能角度为了后面请求获取参数不用再做转换?因为parameters这个value是String类型的

**Comment by sunnights** [comment]
是的，numbers的作用是为了缓存相关信息

**Comment by wzy2008a** [comment]
好的，谢谢！
