### ISSUE TITLE
跨语言调用的问题！

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#866]
1、请问Motan2+fastjson模式，Java server直接返回对象，对与PHP Client来说可以调用么
2、Breeze+Motan2 有明确的示例么？

**Comment by rayzhang0603** [comment]
1、不能，php client还没有实现fastjson序列化。
2、Breeze序列化的demo可以参考demo模块中的[Motan2Server](https://github.com/weibocom/motan/blob/master/motan-demo/motan-demo-server/src/main/java/com/weibo/motan/demo/server/Motan2Server.java)和[Motan2RpcClient](https://github.com/weibocom/motan/blob/master/motan-demo/motan-demo-client/src/main/java/com/weibo/motan/demo/client/Motan2RpcClient.java)。一般配置中添加`serialization="breeze"`设置就可以了。对序列化对象的要求可以参考[breeze文档](https://github.com/weibreeze/breeze/wiki/zh_overview)


Breeze相关项目包括不同语言实现和生成器，可以看[这里](https://github.com/weibreeze)

**Comment by back-zhao** [comment]
JavaBean 和Breeze生成对象之间转换问题有默认实现么？

**Comment by rayzhang0603** [comment]
https://github.com/weibreeze/breeze/wiki/zh_autoGenSchema

**Comment by back-zhao** [comment]
好的！谢谢
