### ISSUE TITLE
Java Server PHPClient调用 配置zk集群问题

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#869]
PHPClient配置go_agent调用java server时只配zk集群的一个节点可以调用。配置zk集群则go_agent都没有在zk对应目录下写入节点。请问该如何配置zk集群?。zk配置文件如下：
motan-registry:
  zk-registry:
    protocol: zookeeper
    host: 10.xx.xx.xx:2181,10.xx.xx.xx:2181,10.xx.xx.xx:2181
    port: 2181
    registrySessionTimeout: 10000
    requestTimeout: 5000

**Comment by rayzhang0603** [comment]
注册中心为单个地址时，使用host&port参数，多地址时请使用address参数。例如

    address: 10.210.21.1:8002,10.210.21.2:8002

**Comment by rayzhang0603** [comment]
注册中心为单个地址时，使用host&port参数，多地址时请使用address参数。例如

    address: 10.210.21.1:8002,10.210.21.2:8002

**Comment by back-zhao** [comment]
ok,谢谢
