### ISSUE TITLE
请教下motan流量复制

### ISSUE THREAD

**Issue by ywf4026** [weibocom/motan#873]
如果想做motan的流量复制，有没有好的方案和建议？

谢谢了

**Comment by rayzhang0603** [comment]
可以根据场景选择在client侧或server侧实现一个filter，在filter中对request进行deep copy，然后在按自己的需求处理。

我觉得可以注意一下这几个问题：

1. 不要影响正常请求。例如：异步处理、不要影响正常业务逻辑等
2. 不要对服务产生较大的负担。例如：cpu负载、网络或磁盘io、gc、oom等
3. 异常情况下可以快速停止流量复制。

实现filter扩展可以参考[filter扩展](https://github.com/weibocom/motan/wiki/zh_developguide#扩展motan的filter)，以及`com.weibo.api.motan.filter`下自带filter的实现。

**Comment by ywf4026** [comment]
多谢指教~
