### ISSUE TITLE
异常传递时异常类型丢失问题

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#874]
有两种情况产生了自定义异常类型丢失：
1、扩展Filter 有些公共处理时在response.setException
2、接口抛出业务异常
client端抛出的都是MotanServiceException。
Motan能传递自定义异常？

**Comment by rayzhang0603** [comment]
motan框架一共有3类异常，MotanFrameworkException、MotanServiceException、MotanBizException。

其中framework异常一般表示会影响整个框架的功能的异常，例如初始化时产生的一些异常；service异常一般与单个service或单个请求相关，例如服务不存在、请求超时等
biz异常一般表示业务处理中出现的异常，这种异常会把原始异常作为caused，client端会直接把原始业务异常抛出，所以接口抛出的业务异常并不会丢失。

在filter处理时，如果想要让client端在业务中感知的异常，可以通过MotanBizException来进行传递

**Comment by back-zhao** [comment]
好的，谢谢
