### ISSUE TITLE
关于Java使用CommonHandler进行泛化调用

### ISSUE THREAD

**Issue by back-zhao** [weibocom/motan#877]
请问有关于Java使用CommonHandler进行泛化调用的示例么？调用Motan2+Simple的Java Server

**Comment by rayzhang0603** [comment]
demo模块的[Motan2RpcClient](https://github.com/weibocom/motan/blob/master/motan-demo/motan-demo-client/src/main/java/com/weibo/motan/demo/client/Motan2RpcClient.java)中有使用CommonHandler调用的例子，配置文件可以参考motan2_demo_client.xml

**Comment by back-zhao** [comment]
谢谢
