### ISSUE TITLE
RequestIdGenerator获得请求id溢出问题

### ISSUE THREAD

**Issue by liuguozhuchina** [weibocom/motan#89]
RequestIdGenerator 该类 请求获得id 是否存在溢出可能性？有可能出现到最大值后都是负数。

 public class RequestIdGenerator {
    private static volatile AtomicLong offset = new AtomicLong(0);

```
private static final ReentrantLock lock = new ReentrantLock();

/**
 * 获取 requestId
 *
 * @return
 */
public static long getRequestId() {
    long increId = offset.incrementAndGet();
    if (increId < 0) {
        try {
            lock.lock();
            if (offset.get() < 0) {
                offset.set(0);
            }
            return offset.incrementAndGet();
        } catch (Exception e) {
            //ignore error
        } finally {
            lock.unlock();
        }
    }
    return offset.get();

}

public static long getRequestIdFromClient() {
    // TODO 上下文 requestid
    return 0;

}
```

}

**Comment by xiegengcai** [comment]
如果当前值是Long.MAX_VALUE时，调用这个方法就返回Long.MIN_VALUE（负数）了

**Comment by liuguozhuchina** [comment]
原先类如下：
public class RequestIdGenerator {
    private static AtomicLong offset = new AtomicLong(0);

```
/**
 * 获取 requestId
 * 
 * @return
 */
public static long getRequestId() {
    return System.currentTimeMillis() * 100000 + offset.incrementAndGet();
}

public static long getRequestIdFromClient() {
    // TODO 上下文 requestid
    return 0;

}
```

}

如果调用次数达到Long.MAX_VALUE 后就是负数，那么这个方法就有问题

**Comment by rayzhang0603** [comment]
id生成是有溢出的问题。
这个id的作用是client异步请求时做唯一标识，其实只需要在client端可以唯一区分一次请求就行，所以负数也可以用作id，功能上不会产生影响。
在实际使用中还是希望这个id能和时间相关，所以可以改成前10位是时间戳，后10位用来循环自增计数。
后续版本会修正这个问题，也可以提相关pr

**Comment by tangdi** [comment]
我提交了一个PR，但是感觉循环递增的思路有些问题。如果后几位count是循环递增，理论上有可能发生的情况是：timestamp2 _10000 - timestamp1_10000 = MAX_COUNT. 这种情况下，timestamp2 产生的 requestId 等于timestamp1 产生的requestId. 

我建议request Id 还是只由offset 生成，timestamp 可以放在另一个request field 里。

**Comment by rayzhang0603** [comment]
@tangdi 非常感谢您一起完善Motan。关于requestid，我觉得如果直接使用offset，会导致频繁进行上线的系统同一个ip在一段时间内经常产生重复的id，不利于与trace系统的对接。所以我还是觉得requestid中如果有时间因素会比较好一点。你说的碰撞问题，我觉得可以把max_count设置为1000000就可以了。

**Comment by tangdi** [comment]
@rayzhang0603  谢谢你的回复。Motan是个很精美的RPC框架，阅读源码时我从中收获良多。
