### ISSUE TITLE
我想添加（weighted）Least Connections 负载均衡器实现，可以怎么做呢

### ISSUE THREAD

**Issue by cszxyang** [weibocom/motan#895]
目前服务器会主动推送一些信息到客户端吗，如当前活跃的连接数之类的？
还有 AbstractLoadBalance 的 doSelect 和 doSelectToHolder 有什么区别，像这种抽象方法可不可以加上注释 😂

**Comment by rayzhang0603** [comment]
1、目前服务端不会推送信息到客户端。
2、doselect是选取一个节点，doSelectToHolder是选择一组节点，这两个方法是方便不同HA策略使用，例如失败重试的HA，可以使用doSelectToHolder选一组节点，失败后直接重试。

如果想实现自定义的LB算法可以按[扩展机制](https://github.com/weibocom/motan/wiki/zh_developguide#扩展机制)来实现个LoadBalance扩展，可以参考`com.weibo.api.motan.cluster.loadbalance`包下的其他LB实现。

另外，有些我个人的理解，供参考：
rpc一般都是长链接，很多场景下server端链接数不能很好的代表server节点的压力；
LB算法要尽量简单，避免某些未知情况下导致线上流量不可控；
复杂的流量策略，最好是由类似策略中心来统一控制

**Comment by cszxyang** [comment]
> 1、目前服务端不会推送信息到客户端。
> 2、doselect是选取一个节点，doSelectToHolder是选择一组节点，这两个方法是方便不同HA策略使用，例如失败重试的HA，可以使用doSelectToHolder选一组节点，失败后直接重试。
> 
> 如果想实现自定义的LB算法可以按[扩展机制](https://github.com/weibocom/motan/wiki/zh_developguide#%E6%89%A9%E5%B1%95%E6%9C%BA%E5%88%B6)来实现个LoadBalance扩展，可以参考`com.weibo.api.motan.cluster.loadbalance`包下的其他LB实现。
> 
> 另外，有些我个人的理解，供参考：
> rpc一般都是长链接，很多场景下server端链接数不能很好的代表server节点的压力；
> LB算法要尽量简单，避免某些未知情况下导致线上流量不可控；
> 复杂的流量策略，最好是由类似策略中心来统一控制

感谢回复 😄 
> rpc一般都是长链接，很多场景下server端链接数不能很好的代表server节点的压力；
> LB算法要尽量简单，避免某些未知情况下导致线上流量不可控；
> 复杂的流量策略，最好是由类似策略中心来统一控制

受教了，魔坦有做类似的流量策略吗，我去学习一下哈哈
