### ISSUE TITLE
Zookeeper认证问题

### ISSUE THREAD

**Issue by MrBack** [weibocom/motan#909]
motan注册中心使用zookeeper时，当zookeeper添加认证后（比如digest方式） ，motan如何设置来工作呢？文档里没找到相关例子

**Comment by MrBack** [comment]
阅读ZookeeperRegistry 类，没有发现创建节点等zk操作有认证相关代码

**Comment by rayzhang0603** [comment]
目前的版本不支持认证。后续会计划升级zkclient，并支持digest类型的认证。

**Comment by MrBack** [comment]
zookeeper添加digest认证后，经本地测试zkCli.sh、ZkCLient(版本与motan一致)都不能创建节点、查询节点等操作。但是motan-Server启动后还是成功创建了节点，绕过了认证。motan是怎么做到绕过认证的呢？

**Comment by rayzhang0603** [comment]
motan现在的zk registry没有基于认证做任何特殊的逻辑。server注册时创建的是临时节点，是不是跟这个有关

**Comment by MrBack** [comment]
设置zookeeper digest权限时 权限目录设置了“/” 只代表zookeeper 一级目录有权限。该zookeeper中已存在/motan 所以motan功能正常运行。这是我对zookeeper的digest认证的错误认识导致的.抱歉
