### ISSUE TITLE
motan支持类似于dubbo那样的泛化调用吗？

### ISSUE THREAD

**Issue by yu199195** [weibocom/motan#921]
如果可以，soul网关将支持一下motan协议  ：https://github.com/dromara/soul/issues/308

**Comment by rayzhang0603** [comment]
motan目前不支持使用map表示的泛型对象。

motan2协议下（支持由client端指定序列化方式），client端可以指定使用breeze序列化，将http请求的json格式参数转换为`com.weibo.breeze.message.GenericMessage`的方式来实现泛型调用。

**Comment by yu199195** [comment]
那就是，还是支持泛化调用的吧，有相关的列子，或者文档吗？ 貌似wiki上没有

**Comment by rayzhang0603** [comment]
https://github.com/weibocom/motan/issues/892 这里有泛化调用的例子，不过breeze序列化目前还不支持schema传输，所以对象转成json时，只支持序号表示成员字段，无法还原成对应字段名。
