### ISSUE TITLE
StandardThreadExecutor 拒绝策略使用不是DiscardPolicy时会导致重复执行

### ISSUE THREAD

**Issue by coding-tortoise** [weibocom/motan#928]
public void execute(Runnable command) {
		int count = submittedTasksCount.incrementAndGet();

		// 超过最大的并发任务限制，进行 reject
		// 依赖的LinkedTransferQueue没有长度限制，因此这里进行控制 
		if (count > maxSubmittedTaskCount) {
			submittedTasksCount.decrementAndGet();
			getRejectedExecutionHandler().rejectedExecution(command, this);
			return; //**如果是DiscardPolicy上面就会直接抛异常，如果是其他拒绝策略会往下走，会导致多次执行,所以这边应该直接return**
		}

		try {
			super.execute(command);
		} catch (RejectedExecutionException rx) {
			// there could have been contention around the queue
			if (!((ExecutorQueue) getQueue()).force(command)) {
				submittedTasksCount.decrementAndGet();

				getRejectedExecutionHandler().rejectedExecution(command, this);
			}
		}
	}
=========================================
getRejectedExecutionHandler().rejectedExecution(command, this);
这边如果不是DiscardPolicy做了拒绝策略后会继续再执行，如果是DiscardPolicy就会直接抛异常，所以这边应该直接return。

**Comment by rayzhang0603** [comment]
感谢反馈，后续版本中会fix这个问题
