### ISSUE TITLE
service调用报错

### ISSUE THREAD

**Issue by winterbest** [weibocom/motan#930]
![image](https://user-images.githubusercontent.com/2382425/99137658-41103400-2667-11eb-980a-3a0d43c21c75.png)
设置了worker数，还是报错
![image](https://user-images.githubusercontent.com/2382425/99137900-b67c0480-2667-11eb-9bb5-b7540465f217.png)
请问大佬有遇到过吗

**Comment by rayzhang0603** [comment]
一般出现'node is not available'时，应该是连续请求失败10次，临时把这个节点置为不可用了。服务节点被置为不可用时有‘NettyClient unavailable Error’关键字的错误日志，可以通过这个日志来确认。

建议看看这条异常之前的请求错误日志，看看具体什么原因导致请求连续失败吧。比如连续超时之类的。


如果是server端处理worker不够会产生‘reject’相关的异常日志。
