### ISSUE TITLE
motan-manager启动不起来,难道是我的环境有问题么,换了一下版本就能启动起来了

### ISSUE THREAD

**Issue by 742762355** [weibocom/motan#931]
![image](https://user-images.githubusercontent.com/37976043/100432422-8fe0b380-30d4-11eb-8a9f-dcdc4095d39d.png)

**Comment by rayzhang0603** [comment]
之前因为security的安全风险问题merge了一个升级security版本的pr，应该是Spring-security和Spring的版本有不兼容的地方。后续会调整一下spring的版本

**Comment by 742762355** [comment]
111
