### ISSUE TITLE
开源的Motan有没有生产环境中用过?

### ISSUE THREAD

**Issue by nsspw** [weibocom/motan#94]
1.开源的Motan有没有生产环境中用过?
2.我看了demo，似乎每个接口暴露都需要一个端口，能不能像dubbo多个接口用一个端口暴露？

**Comment by sunnights** [comment]
1. 目前正在做开源版本的对接，以后将以开源版本为主
2. 请参考 #24

**Comment by nsspw** [comment]
ok,thanks
