### ISSUE TITLE
双发机制有开源吗？

### ISSUE THREAD

**Issue by kensou97** [weibocom/motan#948]
在网上看到了关于[motan双发机制的介绍](https://zhuanlan.zhihu.com/p/59946621)，请问这部分代码开源了吗？没找到呢..

**Comment by rayzhang0603** [comment]
这部分暂时没有开源。

当时为兼容jdk1.7，双发部分是使用线程池来实现的，并不算是一个理想的实现方式，后续计划使用jdk1.8的completable Future来重构这部分，但因为需求优先级的原因尚未进行重构，所以也一直没有开源出这部分扩展。

如果想了解双发的实现可以参考[motan-go的实现](https://github.com/weibocom/motan-go/blob/master/ha/backupRequestHA.go)，这部分能力已经集成在motan的mesh中，实现细节虽有一些差异，但是思路是相同的。

**Comment by kensou97** [comment]
> 这部分暂时没有开源。
> 
> 当时为兼容jdk1.7，双发部分是使用线程池来实现的，并不算是一个理想的实现方式，后续计划使用jdk1.8的completable Future来重构这部分，但因为需求优先级的原因尚未进行重构，所以也一直没有开源出这部分扩展。
> 
> 如果想了解双发的实现可以参考[motan-go的实现](https://github.com/weibocom/motan-go/blob/master/ha/backupRequestHA.go)，这部分能力已经集成在motan的mesh中，实现细节虽有一些差异，但是思路是相同的。

好的多谢
