### ISSUE TITLE
[Question]使用apache commons.pool + 自定义Future有什么特殊考虑吗？

### ISSUE THREAD

**Issue by ghost** [weibocom/motan#97]
请教一下Motan传输层的设计理念。
使用自己定义的Future和apache commons pool，而不是JDK提供的Future和线程池，这样做有什么特殊考虑吗？

**Comment by leizhiyuan** [comment]
应该是为了以后扩展.基本上写框架的都会对依赖的框架包装一层,而不是直接依赖第三方,这样以后如果有变更,或者需要扩展新功能,就更加方便.

**Comment by qdaxb** [comment]
原因跟 @leizhiyuan 说的一致
