### ISSUE TITLE
client端能否支持让用户自定义线程池?

### ISSUE THREAD

**Issue by loongs-zhang** [weibocom/motan#970]
看`com.weibo.api.motan.transport.netty4.NettyClient`里写死了线程池的配置，建议开放出来，让用户可以自定义，最好能像`dubbo`那样抽个`SPI扩展点`出来。
```java
private static final NioEventLoopGroup nioEventLoopGroup = new NioEventLoopGroup();
```

**Comment by rayzhang0603** [comment]
目前motan主要SPI都集中在框架自身机制上，一般不倾向于针对某个具体实现再增加对应的子SPI（比如netty3的SPI、netty4的SPI、或者针对各种注册中心实现的子SPI等），这样做的好处是可以避免SPI泛滥，方便SPI扩展点的长期维护。

如果针对netty4模块的实现有SPI定制需求，建议参考`com.weibo.api.motan.transport.netty4.NettyEndpointFactory`实现`EndpointFactory`扩展点，创建client时使用自己定制的client。

```java
@SpiMeta(name = "my_netty4")
public class MyNettyEndpointFactory extends AbstractEndpointFactory {
    @Override
    protected Server innerCreateServer(URL url, MessageHandler messageHandler) {
        return new NettyServer(url, messageHandler);
    }

    @Override
    protected Client innerCreateClient(URL url) {
        return new MyNettyClient(url); // 这里参考NettyClient自行实现定制的netty4 client即可。
    }
}
```

**Comment by loongs-zhang** [comment]
谢谢，我试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ray ***@***.***&gt;
发送时间: 2022年3月28日 11:44
收件人: weibocom/motan ***@***.***&gt;
抄送: dragon-zhang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [weibocom/motan] client端能否支持让用户自定义线程池? (Issue #970)





 
目前motan主要SPI都集中在框架自身机制上，一般不倾向于针对某个具体实现再增加对应的子SPI（比如netty3的SPI、netty4的SPI、或者针对各种注册中心实现的子SPI等），这样做的好处是可以避免SPI泛滥，方便SPI扩展点的长期维护。
 
如果针对netty4模块的实现有SPI定制需求，建议参考com.weibo.api.motan.transport.netty4.NettyEndpointFactory实现EndpointFactory扩展点，创建client时使用自己定制的client。
 @SpiMeta(name = "my_netty4") public class MyNettyEndpointFactory extends AbstractEndpointFactory {     @Override     protected Server innerCreateServer(URL url, MessageHandler messageHandler) {         return new NettyServer(url, messageHandler);     }     @Override     protected Client innerCreateClient(URL url) {         return new MyNettyClient(url); // 这里参考NettyClient自行实现定制的netty4 client即可。     } }
