### ISSUE TITLE
[type: new feature] support spring `@AliasFor` extend

### ISSUE THREAD

**Issue by loongs-zhang** [weibocom/motan#993]

**Comment by rayzhang0603** [comment]
支持@AliasFor主要是为了要解决什么问题？pr里的`AnnotatedElementUtils.findMergedAnnotation`方法是since 4.2的，老版本的spring-core不兼容

**Comment by loongs-zhang** [comment]
for finish https://github.com/apache/shenyu/issues/3805 motan part

**Comment by loongs-zhang** [comment]
thanks

**Comment by loongs-zhang** [comment]
@rayzhang0603 hi, I want to ask when this can be released ?

**Comment by rayzhang0603** [comment]
There are still some development requirements, it will probably be released in October.

**Comment by loongs-zhang** [comment]
Thanks again !
